### ISSUE TITLE
connecting devices through a node js gateway

### ISSUE THREAD

**Issue by hwestbrook** [aws/aws-iot-device-sdk-js#1]
Hi Guys, 

I have a setup where I have a bunch of devices behind a gateway running node js. Currently the node application receives messages and then ferries those to the cloud and receives messages from the cloud and then sends those to the devices. 

Is there anway to use this SDK to enable a gateway device to pass messages between aws iot and my devices behind the node gateway?

**Comment by gkwicker** [comment]
This should be possible.  One approach would be for the gateway to register separate Thing Shadows for each device behind the gateway.  When messages arrive via either status or delta events, the 'thingName' parameter can be used to distinguish which device it is destined for.

The 'temperature-control.js' example illustrates the use of multiple Thing Shadows in an application.

**Comment by gkwicker** [comment]
Hi Heath, 

We haven't heard back from you on this issue and hope that we were able to answer your question. 
We're going to close this issue for now. If you'd like to ask further questions on this topic, please feel free to re-open it.

**Comment by hwestbrook** [comment]
Hey Gary, 

Sorry not to get back to you. Yes, I think this will solve my issue.

Thanks!
