### ISSUE TITLE
Thing Shadow Class Example missing closing bracket 

### ISSUE THREAD

**Issue by martinkronberg** [aws/aws-iot-device-sdk-js#101]
thingShadows.on('connect', function() {

doesn't have a closing bracket

**Comment by chaurah** [comment]
Hi @martinkronberg,
     Apologies if I am missing something completely here, but could you point me to which file you're seeing the issue in? I couldn't find any place where the closing brackets are missing in the examples. Are you having any trouble in running the samples?

Rahul

**Comment by martinkronberg** [comment]
the Thing Shadow Class example in the readme. line 66 doesn't have a close bracket.

**Comment by liuszeng** [comment]
Hi @martinkronberg ,

Thank you very much for pointing that out. We will fix that in the next release.

Thanks,
Liusu

**Comment by fengsongAWS** [comment]
Fixed in v2.0.0
