### ISSUE TITLE
Invalid "keyPath" option supplied.     at module.exports (/opt/app-root/src/node_modules/aws-iot-device-sdk/common/lib/tls-reader.js:92:13)

### ISSUE THREAD

**Issue by ujjvaljoshi44** [aws/aws-iot-device-sdk-js#105]
Working fine in my local but facing above issue when Trying to use aws-iot-device-sdk on parse cloud.

**Comment by chaurah** [comment]
Hi @ujjvaljoshi44,
      That particular error is returned when the SDK is unable to find the private key at the provided path. Can you verify whether the path you have provided is correct and that the SDK has access to the file at that path?

Please let us know if you are able to work out the issue. Thank you for using AWS IoT.

Rahul

**Comment by fengsongAWS** [comment]
Hi @ujjvaljoshi44 ,
How did you access file path in parse cloud? There might be some specific way in parse to access file or certificate. We have not tested Node.js SDK on parse yet so please feel free to elaborate your way of doing that.

Thanks,
Fengyi

**Comment by fengsongAWS** [comment]
Please reopen this issue if you still have problems.

**Comment by macorifice** [comment]
Hi, i have the same problem, if i download iot package and launch start.sh it can recognize certificates and connect correctly, if i do the same thing from an index in a node project: 
`Error: Invalid "keyPath" option supplied.
emulators_1  |     at module.exports (/app/node_modules/aws-iot-device-sdk/common/lib/tls-reader.js:92:13)
emulators_1  |     at new DeviceClient (/app/node_modules/aws-iot-device-sdk/device/index.js:456:7)
emulators_1  |     at Object.DeviceClient [as device] (/app/node_modules/aws-iot-device-sdk/device/index.js:217:14)
emulators_1  |     at Timeout.publisher [as _onTimeout] (file:///app/src/index.mjs:36:27)
emulators_1  |     at listOnTimeout (internal/timers.js:549:17)
emulators_1  |     at processTimers (internal/timers.js:492:7)`

**Comment by jmklix** [comment]
Since you are in a different folder you need to change the file path to key. You can use either the full or relative path, but you must change all of the arguments in the start.sh with the correct paths. 

For future reference please open new issues rather than commenting on old ones.

**Comment by gauravdhra** [comment]
I have similar issue  here https://github.com/aws/aws-iot-device-sdk-js/issues/346

**Comment by gauravdhra** [comment]
@jmklix  @fengsongAWS 
Please have a look in the similar issue of mine  here https://github.com/aws/aws-iot-device-sdk-js/issues/346

**Comment by gauravdhra** [comment]
We have not tested Node.js SDK on parse yet so please feel free to elaborate your way of doing that.

> We have not tested Node.js SDK on parse yet so please feel free to elaborate your way of doing that.

I a using nodejs sdk having same issue here #346
