### ISSUE TITLE
Could you add browser example in repo?

### ISSUE THREAD

**Issue by dospolov** [aws/aws-iot-device-sdk-js#108]
Hello guys,
I saw you have couple example apps in "example" folder, but they are all node.js built. To make it working for the browser you suggest to use browserify, but this approach has a lot of difficulties for windows user:
- your npm script "browserize": "./scripts/browserize.sh" does not work from cmd
- couple packages has a dependencies of node-gyp and bcrypt which are also buggy on windows (I got stuck on it)

Could you demonstrate simplest IOT app features in the browser and add this sample to "example" folder?

**Comment by fengsongAWS** [comment]
Hi @dospolov ,
Thanks for your interest in AWS IoT Node.js SDK. 
We are aware of this issue and currently have it in our roadmap. In the meanwhile, you can refer to this  [link](https://github.com/aws/aws-iot-device-sdk-js/issues/74) see if that helps you solve your problem. 
Thanks again for your interest and please stay tuned for the updates.
Fengyi

**Comment by dospolov** [comment]
@fengsongAWS  thanks

**Comment by azurelogic** [comment]
+1 - We ended up having to use https://github.com/jimmyn/aws-mqtt-client because the browserize script didn't work standalone and we're using webpack. @fengsongAWS, a separate version of this SDK built for the browser would be greatly appreciated.

**Comment by fengsongAWS** [comment]
CMD script and web pack sample provided in v2.0.0
