### ISSUE TITLE
Normal action when subscribing to forbidden topic

### ISSUE THREAD

**Issue by thchia** [aws/aws-iot-device-sdk-js#112]
When attempting to subscribe to a topic that is forbidden according to the IAM policy, what is normal behaviour?

I have this: 

```
device.on('connect', () => {
          device.subscribe('testTopic', (error, result) => {
            if (error) {
              console.log(error)
            }
          })
        })
```
And my policy document is:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iot:Connect"
            ],
            "Resource": "arn:aws:iot:us-west-2:XXX:client/myUniqueId"
        },
        {
            "Effect": "Allow",
            "Action": [
                "iot:Publish",
                "iot:Receive",
                "iot:GetThingShadow",
                "iot:UpdateThingShadow"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "iot:Subscribe"
            ],
            "Resource": "arn:aws:iot:us-west-2:XXX:topicfilter/notTopic"
        }
    ]
}
```
Two things are happening: `device.on('close')` is being called and the error passed to the subscribe callback function is `Error: client disconnecting`

Is it normal behaviour for on(close) to be called when attempting to subscribe to a forbidden topic? I can't find any definitive documentation on this. Thanks

**Comment by liuszeng** [comment]
Hi @thchia ,

Thank you very much for using AWS IoT Node.js SDK.

The IAM policy attached to your IAM user or the IoT Policy attached to your IoT certificate defines the permissions that the identity gives you. Clients connected to AWS IoT needs to be authorized to access the resources. If the client tries to access forbidden resource, the server side will close the connection. This is triggering the 'close' event in the SDK as you see in your test.

Thanks,
Liusu

**Comment by thchia** [comment]
Ok, thanks for the clarification.
