### ISSUE TITLE
Running device-example twice simultaneously does not work

### ISSUE THREAD

**Issue by michaelswanson25** [aws/aws-iot-device-sdk-js#114]
I'm running the device-example with Node on Windows. 

The problem is that if I run two device-example copies at the same time, they will not communicate to each other (one publishes on topic_1 and receives on topic_2, and the reverse for the second process).

To debug, I can use the AWS console:

If i run it with testMode = 0, it will publish on topic_1 and I can see it in the AWS console working.  If in the AWS Console, I publish on topic_2, the same node process will receive the message.

If I start up a second copy of Device-example, it will receive the message on topic_1 if i publish in the AWS console.

If  I start up both of them and use the AWS console to publish on topic_1 and then on topic_2, only one will work.

It's as if there is a race condition on who can receive messages.

**Comment by fengsongAWS** [comment]
Thanks for your interest in AWS IoT Node.js Device SDK.
What is your configuration for both copies of samples？Are you using the same client ID for both at the same time?
Thanks

**Comment by michaelswanson25** [comment]
I am using the same client ID, same keys, CA, region, etc.  I'm only running them with a different testMode.  Will this work?

**Comment by fengsongAWS** [comment]
The client ID should be UUID for each MQTT connection. Connections with same client ID will get disconnected from server in turns. So, the problem should be fixed when the client IDs are different.

Thanks,

**Comment by michaelswanson25** [comment]
I got it to work by changing the client ID (it wasn't clear to me that this was client supplied and not tied to a  Thing).  Thanks.
