### ISSUE TITLE
Problem using Browserify bundle in Webpack project

### ISSUE THREAD

**Issue by miltonhultgren** [aws/aws-iot-device-sdk-js#115]
Hi! 

We're working on a project based on react-boilerplate which uses Webpack.

Importing the Iot SDK directly gives us errors that util.inherit is not a function so we tried using the browserize script to create a bundle.

Importing the bundle makes webpack complain about this:

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './evpkdf' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 742:0-76 1841:0-455 2059:0-76 2101:0-76 2140:0-76 2510:0-76

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './md5' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 742:0-76 1841:0-455 2059:0-76 2101:0-76 2140:0-76 2510:0-76

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './cipher-core' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 742:0-76 1754:0-42 1841:0-455 1905:0-42 1919:0-42 1933:0-42 1943:0-42 1948:0-42 1957:0-42 1968:0-42 1978:0-42 1987:0-42 1992:0-42 2059:0-76 2101:0-76 2140:0-76 2510:0-76

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './enc-base64' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 742:0-76 1841:0-455 2059:0-76 2101:0-76 2140:0-76 2510:0-76

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './core' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 742:0-76 784:0-26 1597:0-26 1634:0-26 1698:0-44 1754:0-42 1782:0-26 1841:0-455 1844:0-26 1858:0-26 1905:0-42 1919:0-42 1933:0-42 1943:0-42 1948:0-42 1957:0-42 1968:0-42 1978:0-42 1987:0-42 1992:0-42 2001:0-44 2059:0-76 2101:0-76 2140:0-76 2176:0-26 2235:0-26 2276:0-37 2308:0-26 2351:0-39 2427:0-50 2459:0-39 2510:0-76 2560:0-26

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './hmac' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1698:0-44 1841:0-455 2001:0-44

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './sha1' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1698:0-44 1841:0-455 2001:0-44

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './sha256' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455 2276:0-37

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './sha224' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './sha512' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455 2427:0-50

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './sha384' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './sha3' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './ripemd160' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './pbkdf2' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './mode-cfb' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './mode-ctr' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './mode-ctr-gladman' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './mode-ecb' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './pad-ansix923' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './pad-iso10126' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './pad-iso97971' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './pad-zeropadding' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './pad-nopadding' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './format-hex' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './aes' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './tripledes' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './rc4' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './rabbit' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './rabbit-legacy' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './x64-core' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455 2351:0-39 2427:0-50 2459:0-39

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './lib-typedarrays' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './enc-utf16' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

ERROR in ./lib/aws-iot-sdk-browser-bundle.js
Module not found: Error: Can't resolve './mode-ofb' in '/home/CORPUSERS/86002462/CET/feedback-frontend/community/lib'
 @ ./lib/aws-iot-sdk-browser-bundle.js 1841:0-455

Any idea what could be going wrong? I was under the impression that Browserify packs all the needed dependencies into the bundle so I don't see why it would try to look for the modules outside.

**Comment by fengsongAWS** [comment]
The AWS IoT Javascript SDK is not fully tested with Webpack. This is a feature we would like to cover in the future and it is currently in our roadmap. I will update this issue once we got a working solution on it. Please let us know if you have some thoughts on it and feel free to submit a pull request if you have. 

Thanks,
Fengyi

**Comment by jbutz** [comment]
I'm using webpack v2.2.1 and I am not doing anything with browserify and I have everything building.

```js
// How I import AWS IoT Device SDK
import AWSIoTData from 'aws-iot-device-sdk';
```

```js
// what I added to my webpack.config.js
node: {
    tls: 'empty',
    fs: 'empty'
}
```

I haven't tested everything yet, but at least it builds.

**Comment by miltonhultgren** [comment]
We tried doing that but got errors once we ran the app saying that utils.inherits is not a function!

**Comment by 0xc0d3r** [comment]
I've created an app using create-react-app and installed aws-iot-device-sdk. Now I am trying use this sdk in browser environment and getting the same issue. Then I went through the docs and generated browser bundle for this sdk and added that js file in public/index.html. No luck, still getting the issue. Any inputs to get rid of this issue

**Comment by fengsongAWS** [comment]
Sample provided in v2.0.0
