### ISSUE TITLE
IoT Register Throttling

### ISSUE THREAD

**Issue by akutta** [aws/aws-iot-device-sdk-js#116]
We do not seem to receive the error messages back when IoT begins to throttle our connections.  Instead, we effectively drop off into a void.

In addition, being able to more finely specify which topics are registered on thing.register would increase the timing at which we get throttled

**Comment by fengsongAWS** [comment]
Hi @akutta ,

Can you elaborate more on your questions?
Which API are you using that causes throttling issue?
thing.register() is used to register any thing shadow and subscribed to some reserved topics in order to perform shadow operation. Could you also explain your use case of "more finely specify which topics are registered"?

Thanks

**Comment by akutta** [comment]
We are purely using the register api.  IoT has a cap of 500 subscribes / second.  Due to the number of topics auto-subscribed to by register, namely the aws specific ones, we quickly reach this cap.

Per account, we have the equivalent of 4 thing shadows we are interested in.  This number varies depending on the number of things registered to an account.  If we have 40 users login simultaneously, that is over the cap and IoT begins to throttle us.

This message is swallowed in the client sdk / not exposed to the client sdk.  But we do see it in the CloudWatch logs of IoT.

We have slightly worked around the throttling issue by forking the sdk and removing some of the topics that are auto-subscribed to, namely `delete` and `update.`  We no longer subscribe to `update` due to our fork subscribing to `document.`  If we could specify to subscribe to just a subset of the available reserved topics, that would be helpful.  Alternatively, not restrict thing.subscribe from subscribing to aws specific topics.

**Comment by fengsongAWS** [comment]
The server does not have control over which topics that user subscribe to, so the sdk has no idea of being informed of being throttled. This is different in shadow where server would publish "too may request" to rejected topic. 

The AWS IoT Limits only allow 50 subscription per account and that is 7 shadows at most. If you have 40 users, should it hit the 50 subscription limit beforehand?

As a work around, you could fork and modify SDK source code that allows thing shadow API subscribe aws topics by removing the check reserved topics.

**Comment by akutta** [comment]
Subscriptions per connection is 50.
We are maintaining a connection per client, which causes us to hit the 500
subscriptions / second limit. I'm not sure what you mean by 7 shadows at
most, I assume this is 7 topics/shadow.

So, if I understand correctly, there is no way of telling that the server
is throttling the subscriptions.  Correct?  It's the server that is
throttling, so having a way to know if we are being throttled is important.


On Mar 7, 2017 5:44 PM, "fengyi" <notifications@github.com> wrote:

The server does not have control over which topics that user subscribe to,
so the sdk has no idea of being informed of being throttled. This is
different in shadow where server would publish "too may request" to
rejected topic.

The AWS IoT Limits only allow 50 subscription per account and that is 7
shadows at most. If you have 40 users, should it hit the 50 subscription
limit beforehand?

As a work around, you could fork and modify SDK source code that allows
thing shadow API subscribe aws topics by removing the check reserved topics.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aws/aws-iot-device-sdk-js/issues/116#issuecomment-284898188>,
or mute the thread

**Comment by gkwicker** [comment]
Hi @akutta,

The MQTT protocol doesn't provide a specific way for a broker to communicate a throttled response back to the client _à la_ the [HTTP 429 status](https://httpstatuses.com/429), so from the client point of view, the MQTT SUBACK message is the only feedback available.  If it doesn't receive this, it should assume that the broker hasn't received the subscription message and it may want to retry the request.  

Note that if you're working with a very large set of clients, you might want to implement an exponential back-off strategy here to avoid triggering additional throttling, and/or file an [AWS Limit Increase](http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) request to make sure that you won't have any issues.  Decreasing the number of subscriptions generated by the `thingShadow.register()` API (as you've already done) may also help, and we're looking at adding this capability as an option in the API.

From the account point of view, as you mentioned, you can view IoT protocol throttling in [Amazon CloudWatch](https://aws.amazon.com/cloudwatch/) Metrics.

Thanks for using AWS IoT, and please let us know if you have any other questions.

**Comment by fengsongAWS** [comment]
Thanks for your interest in AWS IoT Device SDK. We will close this issue for now and please feel free to open another thread if you have more questions.
