### ISSUE TITLE
`ReferenceError: isUndefined is not defined`

### ISSUE THREAD

**Issue by conroywhitney** [aws/aws-iot-device-sdk-js#117]
First off, thank you for the work you've put into this library and all of the documentation and examples.

When using the `aws-iot-device-sdk` from within a [`create-react-app`](https://github.com/facebookincubator/create-react-app) (which utilizes `babel` and `webpack`) on `node v6.9.1`, calling `awsIoT.device({})` throws the following error:

```
ReferenceError: isUndefined is not defined
```

All irony aside, this seems to be related to the line at the top of `device/index.js`:

```
const isUndefined = require('../common/lib/is-undefined');
````

Changing this `const` to `var` solves the issue, but then raises the same issue for `mqtt`, and so on, and so forth, for all of the lines that use `const xyz = require('xyz')` -- as you fix one, another breaks.

I am submitting a PR which updates all of the `const ... require()` imports to use `var`. This completely solved the issue for me -- hopefully it will for anyone else running into the same issue.

Let me know if there's anything I can do to help.

**Comment by fengsongAWS** [comment]
hi @conroywhitney ,

Thanks for your interest in AWS IoT JavaScript SDK. We haven't tested the sdk with react App but this is a very useful use case for us. It would be great if you can elaborate how you involve the sdk within `create-react-app` and how does `const` raise this error so that we can implement more on this feature in the future.

**Comment by conroywhitney** [comment]
Hey @fengsongAWS,

Sorry for the delay. I started a new project from scratch using `create-react-app` and did not have any problems, so I am going to close this issue. I was unable to figure out what was wrong with my original attempt, but if I run into it again, I'll re-open a new issue.

For what it's worth, here's a `create-react-app` example using `aws-iot-device-sdk-js`:

https://github.com/conroywhitney/serverless-buzz-chat-example

Thanks for your help!
Conroy
