### ISSUE TITLE
Not able to connect to AWS IoT using SDK example thing-example or device-example

### ISSUE THREAD

**Issue by iotgeek** [aws/aws-iot-device-sdk-js#119]
Hi,
I am facing problem connecting to AWS IoT. 
I have created a thing (Smart7688), created certificates and copied onto my device( LinkIt Smart 7688), attached policies with certificates, attached certficates with my thing Smart7688 as well.

I am getting offline, close, reconnect logs while running the node.js examples present in the SDK. I have edited the cmdline.js to give my certificate and key names. I can see in the logs   rejectUnauthorized: true, what does this mean ?

With the -D option enabled, I am getting the below details. Can you please provide me information on what is going wrong here ?

root@mylinkit:~/node_modules/aws-iot-device-sdk# node examples/device-example.js
 -f ~/certs --test-mode=1 -D
{ keyPath: '/root/certs/f0107f3745-private.pem.key',
  certPath: '/root/certs/f0107f3745-certificate.pem.crt',
  caPath: '/root/certs/root-CA.crt',
  clientId: 'Smart7688',
  region: 'us-east-1',
  baseReconnectTimeMs: 4000,
  keepalive: 30,
  protocol: 'mqtts',
  port: 8883,
  host: 'data.iot.us-east-1.amazonaws.com',
  debug: true,
  reconnectPeriod: 4000,
  fastDisconnectDetection: true,
  key: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 52 53 41 20 50 52 49 56 41 54 45 20 4b 45 59 2d 2d 2d 2d 2d 0a 4d 49 49 45 6f 77 49 42 41 41 4b 43 41 51 45 41 30 7a ... >,
  cert: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0a 4d 49 49 44 57 6a 43 43 41 6b 4b 67 41 77 49 42 41 67 49 56 41 4f ... >,
  ca: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0d 0a 4d 49 49 45 30 7a 43 43 41 37 75 67 41 77 49 42 41 67 49 51 47 ... >,
  requestCert: true,
  rejectUnauthorized: true }
attempting new mqtt connection...
offline
connection lost - will attempt reconnection in 4 seconds...
close
reconnect
offline
connection lost - will attempt reconnection in 8 seconds...
close
reconnect
offline

**Comment by fengsongAWS** [comment]
Hi @iotgeek ,
What is your IoT Policy? Did you allow actions in your Policy? More instructions could be found here.
http://docs.aws.amazon.com/iot/latest/developerguide/iot-policies.html
Thanks

**Comment by iotgeek** [comment]
Here is my policy content

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "arn:aws:iot:us-east-1:399190066782:topic/8j/light/data"
    }
  ]
}

**Comment by fengsongAWS** [comment]
From your Policy, you only allowed iot full action acting on "arn:aws:iot:us-east-1:399190066782:topic/8j/light/data" resource. You can start with "*" in "Resource" and see if it works. Then you could restrict the resource with the thing names and topics if you want. 

Thanks

**Comment by arvindh92** [comment]
Even I get the the below error. Replaced policy to '*' as mentioned.

Error: connect ETIMEDOUT 52.11.249.158:8883
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

I tried accessing the end point through openSSL and was able to access it.

Thanks.

**Comment by fengsongAWS** [comment]
Please reopen this issue if you still have problems.

**Comment by Krishnavyas07** [comment]
I am having the same issue.  I have created a thing with the name Edison. 
root@Edison:~/aws-iot-device-sdk/examples# node device-example.js -f ~/cert --test-mode=1 -i Edison -H data.iot.us-east-1.amazonaws.com  -D
{ keyPath: '/home/root/cert/private.pem.key',
  certPath: '/home/root/cert/certificate.pem.crt',
  caPath: '/home/root/cert/root-CA.crt',
  clientId: 'Edison',
  region: 'us-east-1',
  baseReconnectTimeMs: 4000,
  keepalive: 30,
  protocol: 'mqtts',
  port: 8883,
  host: 'data.iot.us-east-1.amazonaws.com',
  debug: true,
  reconnectPeriod: 4000,
  fastDisconnectDetection: true,
  key: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 52 53 41 20 50 52 49 56 41 54 45 20 4b 45 59 2d 2d 2d 2d 2d 0a 4d 49 49 45 6f 67 49 42 41 41 4b 43 41 51 45 41 69 42 ... >,
  cert: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0a 4d 49 49 44 57 6a 43 43 41 6b 4b 67 41 77 49 42 41 67 49 56 41 50 ... >,
  ca: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0d 0a 4d 49 49 45 30 7a 43 43 41 37 75 67 41 77 49 42 41 67 49 51 47 ... >,
  requestCert: true,
  rejectUnauthorized: true }
attempting new mqtt connection...
offline
connection lost - will attempt reconnection in 4 seconds...
close
reconnect
connection lost - will attempt reconnection in 8 seconds...
close
reconnect
connection lost - will attempt reconnection in 16 seconds...
close
----------------------------------------------------
Where as my policy content is 

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "*"
    }
  ]
}
--------------------------------------------------
 but i am still having that error. can you please help me figure out whats wrong here? @fengsongAWS @iotgeek

**Comment by groteworld** [comment]
@Krishnavyas07, could you please put your console output and policy content in ``` (triple backtick quotes)? I think part of your policy content file is missing due to github's markdown.

**Comment by Krishnavyas07** [comment]
@groteworld i have done that. can you help me figure out what is wrong here?

**Comment by fengsongAWS** [comment]
Could you check following things?
1. Can you check if you activated your cert?
2. Can you check if you have the IoT thing created in the same region as your host? From what I saw here is us-east-1. 
3. Did you attach the correct policy to the cert you use?

**Comment by Krishnavyas07** [comment]
@fengsongAWS Thank you! the issue was solved.

**Comment by equizno345** [comment]
@ICanAct How did you solve the issue?

**Comment by graebm** [comment]
![relevent](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)
