### ISSUE TITLE
Can not subscribe to a reserved topic

### ISSUE THREAD

**Issue by bentranmyriota** [aws/aws-iot-device-sdk-js#122]
Hi, I am trying to subscribe a topic from a web app and get an error message "Uncaught cannot subscribe to topic array since one of them is a reserved topic '$aws/things/xxxxxxxxxxxxxxxxx/shadow/get/accepted'.  Here is my code:
`  this.thingShadow.on("connect", () => {
            this.thingShadow.subscribe(["$aws/things/xxxxxxxxxxxxxxxxx/shadow/get/accepted"], {}, (error: any) => {
            console.log("subscribe ", error);
        });`

**Comment by fengsongAWS** [comment]
hi @bentranmyriota ,
Thanks for your interest in AWS IoT Device SDK. As the error indicated, the shadow topics (topics with prefix '$') are reserved topic and cannot be subscribed. Since you already use shadow service, you can register your shadow and using shadow API to do get, update etc.

**Comment by bentranmyriota** [comment]
Hi, thanks for reply. According to this http://docs.aws.amazon.com/iot/latest/developerguide/topics.html, I should be able to subscribe to get/accepted topic. Speaking of registering to a shadow, I had tried to get thing shadow using thingShadow.get() method. However, all i got back was clientID value. Can you be kind showing me how to get thing shadow?

**Comment by fengsongAWS** [comment]
Hi @bentranmyriota ,
The Node.js SDK does not support subscribe to reserved topic by customer because shadow already subscribed for you if you register it. We will provide more flexibility on reserved topic subscription in the future. thingShadow.get() will fire a get operation and you can listen on status events to receive your shadow payload after get as shown in the example.
```
thingShadows.on('status', 
    function(thingName, stat, clientToken, stateObject) {
       console.log('received '+stat+' on '+thingName+': '+
                   JSON.stringify(stateObject));
//
// These events report the status of update(), get(), and delete() 
// calls.  The clientToken value associated with the event will have
// the same value which was returned in an earlier call to get(),
// update(), or delete().  Use status events to keep track of the
// status of shadow operations.
//
    });
```

**Comment by groteworld** [comment]
@bentranmyriota, is this a web app that is on the IoT device? If not, it is probably best to use [aws/aws-sdk-js](https://github.com/aws/aws-sdk-js) and its [IotData API](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IotData.html). From that you can use [getThingShadow()](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IotData.html#getThingShadow-property) to retrieve the shadow

Hope that helps as well!

**Comment by bentranmyriota** [comment]
Hi,
   Thanks for the advice. I have moved to use aws/aws-sdk-js a while back. 
    FYI, the web app is not on the Iot Device. I tried to subscribe to the iot server in a hope of getting notifications whenever the iot Device pushes an update to the server
