### ISSUE TITLE
lambda mqtt pub to AWS Kinesis

### ISSUE THREAD

**Issue by Sabiha05** [aws/aws-iot-device-sdk-js#123]
I want to develop a lambda function which will connect to the AWS Kinesis and publish an MQTT message. How can I do that using node.js?

**Comment by fengsongAWS** [comment]
Hi @Sabiha05 ,

Lambda function does not support long live connection. You can use AWS Node.js SDK which use HTTP protocol to publish topics. For further information regarding Kinesis and Lambda services, please refer to https://aws.amazon.com/kinesis/ and https://aws.amazon.com/lambda/. Or you could raise a thread in AWS developer forum if you have any questions regarding AWS services. https://forums.aws.amazon.com/index.jspa

Thanks

**Comment by fengsongAWS** [comment]
Please feel free to reopen it when you have more questions.
