### ISSUE TITLE
Cannot connect using echo-example.js

### ISSUE THREAD

**Issue by makeupsomething** [aws/aws-iot-device-sdk-js#124]
When i try to connect using this example it gets stuck attempting to make a new mqtt connection and does not proceed any further. I have no problems running device example.

`attempting new mqtt connection...`

**Comment by fengsongAWS** [comment]
Hi @makeupsomething ,
Did you create a thing and used correct certs for this example? The echo sample is used for monitoring delta status of shadow changes. You can perform changes through either console or another device and see if you can see the messages printed out.

Thanks

**Comment by makeupsomething** [comment]
Hi @fengsongAWS 

Thank you. It seemed it was actually connected but I wasn't clear what I was supposed to do after that. I was able tot learn how to update device shadow from this document http://docs.aws.amazon.com/iot/latest/developerguide/API_UpdateThingShadow.html and could see the correct output on my device. This issue can be closed.
