### ISSUE TITLE
Integration with Angular 4 and SystemJS

### ISSUE THREAD

**Issue by thomasphorton** [aws/aws-iot-device-sdk-js#128]
I'd like to use this package in an Angular 4 application, and it's not going smoothly. I believe it is because of this library's non-standard hierarchy of modules.

For reference, the aws-sdk has the following hierarchy, where each module is in it's own named `.js` file:
```
index.js
|- lib
  |- aws.js
  |- browser.js
```
The IoT library looks like this:
```
index.js
|- device
  |- index.js
|- thing
  |- index.js
```

The SystemJS loader is not intelligent enough to look for a root document in the directory, and 404s. I've checked with SystemJS and they do not plan on implementing this feature.

**Comment by thomasphorton** [comment]
This looks more complicated than initially thought (of course). This SDK assumes many node utilities, where the standard AWS package comes with shims and is more versatile. I'll look into the effort needed to bring it in line with the regular AWS package.

**Comment by fengsongAWS** [comment]
Hi @thomasphorton ,

Thanks for your interest. So far, we have not fully tested and integrated with Angular framework. We will take this as a feature request. Please feel free to provide any feedback and efforts on this and we could include it in the future release.

Thanks

**Comment by c4adarsh** [comment]
Hi @thomasphorton : If you have found any solution for integrating it, please let me know.

**Comment by jmklix** [comment]
This sdk is now being sunsetted. Please take a look at the [v2](https://github.com/aws/aws-iot-device-sdk-js-v2) sdk.
