### ISSUE TITLE
DynamoDB Rule on AWS IoT

### ISSUE THREAD

**Issue by vinhlh** [aws/aws-iot-device-sdk-js#13]
What are parameters in DynamoDB Rule to store states of a thing as time series?
I read the code. You guys used this pattern
```javascript
return '$aws/things/'+thingName+'/shadow/'+operation+'/'+type;
```

So which Topic Filter should I use? And which Hash Key, Range Key, Payload Field?

**Comment by lukin0110** [comment]
I've tried something similar. I stored all messages from a certain topic to a DynamoDB. Is used the following config:

Hash Key Value: ${topic()}
Range Key Value: ${timestamp()}
Payload: left it empty (AWS will stores it by default in 'payload')

Create a DynamoDB table with a hash & range key. 

Can you try to following rule: `SELECT * FROM '$aws/things/#'`.

**Comment by gkwicker** [comment]
Hi Vinh,

We haven't heard any more on this issue, so we're going to go ahead and close it.  For questions on integrating with services like DynamoDB, the [AWS Forums](https://forums.aws.amazon.com) are a great resource.  If you find issues or would like to suggest modifications within this SDK, you can always let us know by creating a GitHub issue or pull request.  Thanks for trying out our SDK and AWS IoT.
