### ISSUE TITLE
thingShadow operations callback

### ISSUE THREAD

**Issue by barryvdh** [aws/aws-iot-device-sdk-js#134]
Wouldn't it be easier if the thingShadow operations would return a callback/promise? 

I'm currently keeping a stack and using [https://caolan.github.io/async/docs.html#queue](async/queue) to keep a stack of the clienttokens and process them in serial, but not sure if that's correct. 

It would be easier of the library would handle the callbacks, eg. return when the status update with that client token comes back, or a timeout from the broker or a client side timeout occurs (after 10 secs?). Do you think this would be possible?

**Comment by fengsongAWS** [comment]
Hi @barryvdh ,
Thanks for your interest in IoT Device SDK.
The thingShadow provides events like timeout, delta, status. Callbacks can be invoked based on those events. You can refer to this sample for some uses cases. https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/thing-example.js

Thing shadow uses MQTT QoS 0 so there is no guarantee of message arrival underneath.

**Comment by fengsongAWS** [comment]
Thanks for your interest in AWS IoT Device SDK. We will close this issue for now and please feel free to open another thread if you have more questions.
