### ISSUE TITLE
tls dependency is missing in package.json

### ISSUE THREAD

**Issue by Kosta-Github** [aws/aws-iot-device-sdk-js#135]
the `tls` dependency (`required` here: https://github.com/aws/aws-iot-device-sdk-js/blob/master/device/lib/tls.js#L17) is missing in `package.json`

**Comment by fengsongAWS** [comment]
Hi @Kosta-Github ,
Similar with event, util and etc, tls here is a default module along with Node. You do not need to explicitly install it through npm.

Thanks,
Fengyi

**Comment by Kosta-Github** [comment]
mh, I am doing a `webpack` of the `device` in combination with the `wss` protocol for a web browser usage, but `webpack` is complaining about the missing `tls` module.
