### ISSUE TITLE
Event Emitters Not Working

### ISSUE THREAD

**Issue by Tin-Man-Dylan** [aws/aws-iot-device-sdk-js#140]
This is from a comment in another issue, where I provided some solution and information as well as a new question. Moving it here so it will be seen. The old question is here https://github.com/aws/aws-iot-device-sdk-js/issues/130 , it gives background to why I am asking this question.

My question is about event emitters, as seen in my post in the [other issue](https://github.com/aws/aws-iot-device-sdk-js/issues/130) the device.on('error', function()) one does work for me, also the 'connect' one and the 'message' one work too. So I assumed the rest of them from MQTTjs would work as well since it is built on it.

However when I try to use ones like 'close' and 'reconnect' and just do a console log they don't seem to always react to the loss of internet. They do seem to show when I have the internet not connected from the beginning, but if I shut it off (ifdown) in the middle of it running the event emitters don't display anything. Is there something I am doing wrong? Because it seems as though they must be working [here](https://github.com/aws/aws-iot-device-sdk-js/blob/master/device/index.js) since it reconnects. Thanks for the help!

**Comment by Tin-Man-Dylan** [comment]
So I tried it again and it doesn't seem to work, though one time right when i reconnected it seemed to do the offline-close-reconnect sequence once. what I am doing for all the events is this:

`
device.on('offline', function() {
        console.log("offline");//not currently working other than if no connection at start
});
device.on('close', function() {
        console.log("closed");//not currently working other than if no connecti$
});
device.on('reconnect', function() {
        console.log("reconnecting");//not currently working other than if no connection at start
});
`
Another thing I have been trying is the functions for detecting connected or reconnecting:

`
isConnecting = device.connected;
isReconnecting = device.reconnecting;
console.log(isConnecting);
console.log(isReconnecting);
`
Except for the console.log here is just producing "undefined" not sure if it has something to do with types. I tried putting Boolean() around it but was always false.

Thanks again for your help, I'm going to be away for 2 weeks so might not get a chance to try out your suggestions for a bit after today.

**Comment by fengsongAWS** [comment]
What sequence did you see? 
When I run the example in this directory https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/device-example.js, it the sequence is what I saw before.

The device does not expose connected and reconnecting attributes so that's why it shows undefined.
