### ISSUE TITLE
Feature-Vote: Websockets with Certificate authentication

### ISSUE THREAD

**Issue by mattmeye** [aws/aws-iot-device-sdk-js#141]
Hello,

i would be glad if you can enable it to authorize with Websockets via certificates and without AccesKey / SecretKey.

**Comment by fengsongAWS** [comment]
Hi @mattmeye ,

Thanks for your interest in aws-iot-device-sdk-js. Can you elaborate more about your use case why do you want to do authorization in websockets via certs?

**Comment by fengsongAWS** [comment]
Thanks for your interest in AWS IoT Device SDK. We will close this issue for now and please feel free to open another thread if you have more questions.

**Comment by mattmeye** [comment]
Hi @fengsongAWS,

In my case,  pc users should be able to connect to the message bus with certificates with their browser. I know, I'm able to create iam users and give them permissions, but I have a specific user management and don't use iam.

It's easier for me to handle a pc user as a normal actor/sensor, manage permissions via certificates. The sdk is currently for nodejs, not for simple browser js.

**Comment by rajatprogrammer** [comment]
Hi @mattmeye  I am also working on the same issue that i have authorized a  specific user for this when you open your account on Amazon as IAM users during adding the iot policy you generate some certificate like public and private certificates. at the same time, you download it and give that certificate to another specific user for whom you want to create and store that certificate on the root of a specific directory and then using aws things shadow your specific user is access it. 
your last sentance is correct that sdk is currently for node js not for simle browse js but if you install mqtt aur any other broker on aws server and link with your system then you can generate your own certificates using ssl command and on the other side you just give that certificate. I am doing same things.

**Comment by mattmeye** [comment]
@rajatprogrammer many thanks, do you use an open js package? or have a code snippet?
