### ISSUE TITLE
Issue in mqtt v2.2.1 'const' keyword

### ISSUE THREAD

**Issue by MohammedSiddiqui10p** [aws/aws-iot-device-sdk-js#142]
This version of mqtt.js had a bug where it used 'const' to declare a variable.
https://github.com/mqttjs/MQTT.js/blob/v2.2.1/lib/connect/index.js#L100

It seems to have been resolved in v2.3.1
https://github.com/mqttjs/MQTT.js/blob/v2.3.1/lib/connect/index.js#L100

The problem came up when I added this package to our project, which uses webpack to bundle and manage the files. Since we exclude node_modules from being parsed by babel, browsers which did not support the const keyword started crying.

Although there are ways where you can include explicit node_modules being parsed e.g:
`{
  test: /\.js$/,
  exclude: /node_modules\/(?!(MY-MODULE|ANOTHER-ONE)\/).*/,
},`

The above solution seems to be working, but I just thought to open this ticket for any other dev which will likely face this problem. Is there any explicit reason this package is depending on a much older version of mqtt ?

**Comment by fengsongAWS** [comment]
Hi @MohammedSiddiqui10p ，
Thanks for your interest in AWS IoT Device SDK. We will update to a newer version of mqtt in the future release.

Thanks

**Comment by MohammedSiddiqui10p** [comment]
Looking forward to it !
