### ISSUE TITLE
react native component contribution

### ISSUE THREAD

**Issue by jamesjara** [aws/aws-iot-device-sdk-js#148]
Hello everybody, I know it has been a long time from the first request of this but it is alive now.
Quite simple, supporting `device` and `thingShadow` for example:
```
<AWSIoTMQTT
    type="shadow"
    ref={(ref) => { this.AWSIoTMQTT = ref; }}
    region={config.AWS_REGION}
    host={config.MQTT_HOST}
    onConnect={() => this.onConnect()}
    onDelta={(thingId, stateObject) => this.onDelta(thingId, stateObject)}
    onStatus={(thingId, statusType, clientToken, stateObject) =>
        this.onStatus(thingId, statusType, clientToken, stateObject)}
    onThingConnected={(thingId) => { this.onThingConnected(thingId); }}
/>
```
Repository: https://github.com/jamesjara/react-native-aws-iot-device-shadows

**Comment by fengsongAWS** [comment]
Hi @jamesjara ,

Thanks for your contribution on this. We will work further on interacting with react native and have it in the future release.

Thanks

**Comment by fengsongAWS** [comment]
Thanks for your interest in AWS IoT Device SDK. We will close this issue for now and please feel free to open another thread if you have more questions.

**Comment by hardcoreprogrammingwarrior** [comment]
but how do u publish?
