### ISSUE TITLE
How can I proxy the IOT endpoint

### ISSUE THREAD

**Issue by radhemad** [aws/aws-iot-device-sdk-js#149]
I am developing an Ionic App and would want to proxy the Endpoint before calling.

**Comment by fengsongAWS** [comment]
Hi @radhemad ,
Can you elaborate your use case?
Are you using websocket connection or cert mutual auth? Are you creating your own proxy server?

**Comment by radhemad** [comment]
So we are using Corporate firewall and would like all the end points go through the corp proxy.
Saw some solutions using AWS-SDK but not AWS-IOT-SDK.

Would need some solution on how to achieve this using IOT.

**Comment by fengsongAWS** [comment]
The aws iot device sdk does not have a sample to work with proxy server. Sometimes it really depends on the proxy setup and behaviors. Typically, to connect with web proxy, you need to create a socket connection between client and proxy server. Then the client should send a HTTP connect and expect a 300 response. Some tls handshake or username/password pair might be required in this process depending on the setup of proxy. The AWS IoT implements tls over handshake using either websocket and X509 mutual auth. The proxy should be able to maintain two socket connection and completely forward packet from one to another. 

Hope this helps.
Thanks

**Comment by fengsongAWS** [comment]
Thanks for your interest in AWS IoT Device SDK. We will close this issue for now and please feel free to open another thread if you have more questions.

**Comment by swapnilGitTest** [comment]
Hi @fengsongAWS 

Do we have any workaround it, to access aws iot from corporate firewall using x.509 auth- Java client
