### ISSUE TITLE
Sigv4  service iotdevicegateway VS iotdata

### ISSUE THREAD

**Issue by jamesjara** [aws/aws-iot-device-sdk-js#150]
Hello,

I was wondering why the current implementation is using `iotdata` and the docs is using `iotdevicegateway` for the sigv4?
Iotdata: 
https://github.com/aws/aws-iot-device-sdk-js/blob/a0def8b9909949f97d107a0dc1b63d069f15d8ae/device/index.js#L146
Documentation: (search for iotdevicegateway)
http://docs.aws.amazon.com/en_en/iot/latest/developerguide/protocols.html#http

**Comment by fengsongAWS** [comment]
Thanks for point this out. They are now both accepted. Since 'iotdevicegateway' is documented, I will switch to iotdevicegateway to avoid confusion.

**Comment by fengsongAWS** [comment]
Issue was resolved in v2.1.0

**Comment by MohammedNoureldin** [comment]
Hi @jamesjara, where is this `iotdevicegateway` coming from? I could not find it anywhere in the docs.
