### ISSUE TITLE
How to access MQTT.Client.connected?

### ISSUE THREAD

**Issue by erichonkanen** [aws/aws-iot-device-sdk-js#152]
Hello,

I would like to be able to check the connection state by looking at `MQTT.Client.connected` 
https://github.com/mqttjs/MQTT.js/blob/master/README.md#connected

However that is not available when using this package...

Any ideas how to access it or why it's not available when using this wrapper lib?

**Comment by fengsongAWS** [comment]
Hi @erichonkanen ,
Thanks for your interest in aws iot device sdk. 
In the SDK, we have a connection state variable to mark the state of the connection as 'inactive', 'stable' so we did not expose connected variable. However, the connectionState variable is for internal use as well. Could you elaborate your usecase of using connected variable?

**Comment by erichonkanen** [comment]
hello @fengsongAWS, we are currently doing an experimental branch switching our project from autobahn.js to aws iot.

The existing autobahn based code uses the connection state to trigger some things in our app. An example is if the connection drops and then comes back up we need to run some code...

**Comment by fengsongAWS** [comment]
The SDK does not expose the connection state unless you customize the source code. Can you do similar things in 'connect' and 'offline' events call back?  e.g. 
```
device.on('connect' function(connack) { do something...})
device.on('offline' function(connack) { do something...})
```

**Comment by erichonkanen** [comment]
@fengsongAWS yeah I can just handle it manually like that.. thanks
