### ISSUE TITLE
Support for Greengrass Discovery

### ISSUE THREAD

**Issue by kennu** [aws/aws-iot-device-sdk-js#154]
The AWS IoT C++ Device SDK has support for Greengrass Core discovery (https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/GreengrassDiscovery.md). It would seem logical to add this support also to the JavaScript SDK. Are there any plans yet?

Technically it's just a certificate-authenticated HTTPS request that returns the local MQTT endpoint and local CA certificate, which will be used instead of the AWS cloud endpoint/CA.

**Comment by fengsongAWS** [comment]
Hi @kennu ,
Thanks for your interest in AWS IoT Node.js SDK. We are looking into this feature request and hopefully we can get this sorted out as soon as possible. Please stay tuned.

**Comment by fengsongAWS** [comment]
Thanks for your interest in AWS IoT Device SDK. We will close this issue for now and please feel free to open another thread if you have more questions.

**Comment by daviian** [comment]
Any update on this?

**Comment by Mayank-Volansys** [comment]
We are planning to use Greengrass, So, I am curious to know when AWS add support for Greengrass Discovery in JavaScript SDK

Please update me ASAP!

Thanks In Advance

**Comment by izaytsev** [comment]
Been looking forward to use this feature as well. Started with the Python SDK and wanted to reproduce a set-up in JS. Almost finished and discovered that device discovery is not part of this SDK. Would be great if you guys could add it.

**Comment by valiknows** [comment]
any updates on this?
