### ISSUE TITLE
Can't connect with Cognito credentials

### ISSUE THREAD

**Issue by edodso2** [aws/aws-iot-device-sdk-js#155]
I was able to use the SDK to connect my thing via node.js and X.509 cert. Then I connected in the browser using Congito and an unauthenticated user. However, when I tried to use an authenticated user I get stuck in a "closed/reconnecting" loop.

- My policy for the identity pool is the same for authenticated and unauthenticated users.
- I had no issue connecting to dynamodb via AWS SDK with my authenticated user.

Here is the code I am using (modified the mqtt-explorer-example):

`cognitoUser.authenticateUser(authenticationDetails, {
  onSuccess: function (result) {
  
    var params = {
      IdentityPoolId: AWSConfiguration.poolId,
      Logins: {
        'cognito-idp.us-east-1.amazonaws.com/us-east-1_TbVAQ9aj5': result.idToken.jwtToken
      }
    };

    AWS.config.credentials = new AWS.CognitoIdentityCredentials(params);

    AWS.config.credentials.get(function(err, data) {
      if (!err) {
          
        mqttClient.updateWebSocketCredentials(
          AWS.config.credentials.accessKeyId,
          AWS.config.credentials.secretAccessKey,
          AWS.config.credentials.sessionToken
        );
            
       } else {
          console.log('error retrieving identity:' + err);
          alert('error retrieving identity: ' + err);
       }
    });
  },

  onFailure: function(err) {
    alert(err);
  }
});`

Note: there are some other methods to get the credentials besides the 'get' function. I have tried various different methods all with the same result.

If anyone has got this working and can share some knowledge that would be a big help!

**Comment by fengsongAWS** [comment]
Hi @edodso2 ,
Thanks for your interest and question in IoT Node.js SDK. 
 
You’ll need to attach your IoT policy to your authenticated Cognito identities also. The pool gets attached to an IAM policy and authenticated Cognito identities also need the IoT policy to access AWS IoT data plane actions like iot:Connect/Publish/Subscribe/Receive.
 
You can do this for one-off identities with the iot:AttachPrincipalPolicy API http://docs.aws.amazon.com/iot/latest/apireference/API_AttachPrincipalPolicy.html

Please let us know if this solves your problem.

**Comment by edodso2** [comment]
Thanks for the quick response @fengsongAWS . After some trial and error I was able to get the connection established. 

The connection does drop from time to time (did this about 4 times while I was writing this post) but reconnects immediately and is able to receive messages. Is this normal?

For anyone else experiencing this issue here are the steps I am following:
1. Authenticate with Cognito
2. Configure AWS credentials like below ( I did this inside the authenticate callback):
```javascript
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId: '<enter_id_here>',
        Logins: {
          'cognito-idp.<enter_region_here>.amazonaws.com/<enter_userpoolid_here>': result.getIdToken().getJwtToken()
        }
      });
```

3. Refresh credentials. To get the keys & token you will need to access iot
`AWS.config.credentials.refresh`

4. Attach principal policy to the cognitoID (since there are many different id's in cognito i had a lot of issues here I ended up with the below code):
```javascript
var iotparams = {
      policyName: <enter_policy_name_from_iot_console>
      principal: AWS.config.credentials.identityId
};
```

Note: policy name is from iot console (under security) not IAM.

5. After above steps I was able to connect using the keys & token in AWS.config.credentials

I know this post isn't detailed, but for anyone having trouble I would suggest to first get the mqtt-explorer example in this repo working then reference the [Cognito SDK Docs](http://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-javascript-examples.html) and the above steps to get everything working much quicker than I did!

**Comment by fengsongAWS** [comment]
Hi @edodso2 ,
Thanks for your detailed elaboration. We will work on providing more instructions on cognito setup in the future. 
The connection drop is not normal. You probably should double check your environment settings or logs to see the reason that drops the connection.
