### ISSUE TITLE
Configure attempted reconnection interval

### ISSUE THREAD

**Issue by mlfarrell** [aws/aws-iot-device-sdk-js#157]
Is this possible?  If the device can't connect, I'd like it to use up less cpu and logging space trying to reconnect immediately in a loop.  I'd like to dial it down to maybe every minute or so.

**Comment by fengsongAWS** [comment]
You can config `baseReconnectTimeMs` and `maximumReconnectTimeMs` to meet your requirement.

Thanks

**Comment by mlfarrell** [comment]
Thanks.  Sorry for creating an issue for something you clearly documented.
