### ISSUE TITLE
Keep Receiving Messages after the messages are consumed by the client

### ISSUE THREAD

**Issue by RameshRM** [aws/aws-iot-device-sdk-js#158]
My setup is I publish a message from `iot` and have a rule setup to trigger a Lambda, Lambda publishes a message on the topic subscribed by `iot`, I am experiencing messages are bufferred and keep receiving messages constantly

Any pointers on why this would happen ?

**Comment by fengsongAWS** [comment]
Hi @RameshRM ,
Can you elaborate your case? What topics did your iot device subscribe to and which topic did your lambda publish to? And which topic did you receive messages from?

**Comment by RameshRM** [comment]
@fengsongAWS 

1. I have device publishing a message `verify`  
2. `Verify` message is setup @ the Rule engine to Trigger a Lambda
3. If Lambda `verified` successfully, sends a message back 'verify` with `status`
4. Device subscribes to the message `verify`

My issue is after `device.on(message)` is consumed , I keep receiving messages , that means `device.on(message)` is getting invoked.

Lambda is not going to get triggered every time, How is the message getting replayed , Device is not publishing the message either.

**Comment by fengsongAWS** [comment]
I do not quite understand here. Is `**verify**` and `**status**` the name of your topic? What do you mean by saying device subscribe to the message `verify`?

`device.on(message)` should only be triggered when there is incoming message. You can subscribe to life cycle events to see the message flowing by log into IoT Console subscribing to $aws/events/# to see who published the messages.

**Comment by RameshRM** [comment]
Ah, I should have explained better, Device & Lambda send back and forth `Verify` topic with value status.

Btw: `$aws/events/# ` I can subscribe to this topic with my registered `thing` ?

**Comment by fengsongAWS** [comment]
Hi @RameshRM ,
You can use AWS IoT console to subscribe to life cycle topics.

**Comment by fengsongAWS** [comment]
Hi @RameshRM ,
Please reopen another thread if you still have questions
