### ISSUE TITLE
Is there an option to disable `Reconnect`

### ISSUE THREAD

**Issue by RameshRM** [aws/aws-iot-device-sdk-js#159]
Is there an option to support disabling `auto reconnect` of `iot` , I do see the embedded C have an option to do this

http://aws-iot-device-sdk-embedded-c-docs.s3-website-us-east-1.amazonaws.com/aws__iot__mqtt__client_8h.html#aead415c5217c53ce127747a9019e6b0d

**Comment by fengsongAWS** [comment]
There is no option field to disable `autoreconnect`. The reconnect logic is handled by mqtt.js.
However, you can call `device.end()` to force ending the reconnection. 

Thanks

**Comment by RameshRM** [comment]
Ok Thanks, `device.end` will work.
