### ISSUE TITLE
Device config values differ from Console

### ISSUE THREAD

**Issue by typemismatch** [aws/aws-iot-device-sdk-js#16]
The console gives a config object with your certificate names etc, host + port and so on however they don't match what Device and more specifically, tls-reader.js is expecting. caPath, certPath and keyPath and being called caCert, clientCert, privateKey - also, the config object is missing the region, which is fine if you're in us-east-1 but otherwise it also throws an exception.

**Comment by gkwicker** [comment]
Hi Craig,

Thanks for trying out the AWS IoT Device SDK and for bringing this issue to our attention.  Currently, only the example applications are designed to work with the JSON document that the AWS console generates.  This is done using the '-F' command line option as shown [here.](https://github.com/aws/aws-iot-device-sdk-js#use-a-configuration-file)  However, we agree that it might also be nice to use this same JSON document as an input to the Device and Thing Shadow classes.  In addition, if the hostname is specified (as in the JSON document from the AWS Console), this should override the region.  For changes like these, we will first implement them in our internal development and testing pipeline prior to releasing them on github and npm.  In the meantime, we'll leave this issue open, so feel free to comment further on this topic.  Thanks again for your help.
