### ISSUE TITLE
'secretKey' device initialization option vs 'secretAccessKey' from AWS credentials

### ISSUE THREAD

**Issue by Nosajool** [aws/aws-iot-device-sdk-js#166]
One thing that tripped me up when initializing the device client was that the constructor options `accessKeyId` and `sessionToken` map perfectly to the `AWS.config.credentials` keys however `secretKey` differs from `secretAccessKey`.

This prevents me from using shorthand ES6 object initialization syntax when the key and variable name are the same. (I had assumed that they mapped perfectly and was wondering why I was seeing `wss://no-credentials-available` until I used `#updateWebSocketCredentials` which uses positional arguments rather than keys)

```js
import DeviceSdk from 'aws-iot-device-sdk';

...

const { accessKeyId, secretAccessKey, sessionToken } = AWS.config.credentials;
const client = DeviceSdk.device({
  accessKeyId,
  secretKey: secretAccessKey, // <-----HERE
  sessionToken,
});
```

This is not really a bug but a gotcha that might be worth mentioning in the README.

**Comment by fengsongAWS** [comment]
Hi @Nosajool ,
Thanks for pointing this out. We will look into this but to avoid major version changes, I would prefer stay with the current options.

**Comment by Nosajool** [comment]
Sounds good :sunglasses:
