### ISSUE TITLE
How to handle errors?

### ISSUE THREAD

**Issue by raRaRa** [aws/aws-iot-device-sdk-js#167]
When my PC loses connection to AWS IoT I get bunch of expected errors such as:

> WebSocket connection to 'wss://***' failed: Error during WebSocket handshake: Unexpected response code: 403

> Uncaught Error: Uncaught, unspecified "error" event. ([object Event])
    at f.r.emit

The reconnect event is triggered which is enough for me to handle the error, but I would like to catch this particular error just to make the console look better.

Is there anything that I can do to catch those errors? 

Thanks!

**Comment by liuszeng** [comment]
Hi @raRaRa ,

Thank you very much for using AWS IoT Node.js SDK.

Unfortunately, I am not able to reproduce your issue. I assume the errors are coming from the underneath Mqtt.js code. Can you confirm? Can you provide more context/logs when this issue happens?

Thanks,
Liusu

**Comment by 0xc0d3r** [comment]
I'm also getting the same error. 


`WebSocket connection to 'wss://no-credentials-available/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED`

events.js:62 Uncaught Error: Uncaught, unspecified "error" event. ([object Event])
    at DeviceClient.EventEmitter.emit (events.js:62)
    at MqttClient.<anonymous> (index.js:772)
    at MqttClient.EventEmitter.emit (events.js:96)
    at Duplexify.f (once.js:25)
    at Duplexify.EventEmitter.emit (events.js:96)
    at Duplexify._destroy (index.js:184)
    at index.js:175
    at Item.352.Item.run (browser.js:153)
    at drainQueue (browser.js:123)

**Comment by raRaRa** [comment]
I ended up listening to `error`, I just wasn't aware that it was possible.

```
mqttClient.on('error', (error) => {
    console.log(error)
})
```

That seems to do the trick, but there's no way to tell what kind of error was thrown, e.g. if it was a connection issue, etc.

**Comment by fengsongAWS** [comment]
MQTT is a long live connection and it does not contain any message error code. If any unexpected behavior, the connection was just killed.

**Comment by fengsongAWS** [comment]
Please open another thread if you still have questions.
