### ISSUE TITLE
Example code just reconnects does not issue a usable error message

### ISSUE THREAD

**Issue by paul-cipherlex** [aws/aws-iot-device-sdk-js#168]
When running the example code, I'm getting errors but the client just reconnects and doesn't issue any useful error messages.

For example:

    node node_modules/aws-iot-device-sdk/examples/device-example.js -t 1  -f certs -d 4000 -D -T paul-pi3 -H a1vfc41l04drxa.iot.us-east-1.amazonaws.com

Just fails with

```
attempting new mqtt connection...
offline
connection lost - will attempt reconnection in 4 seconds...
close
reconnect
connection lost - will attempt reconnection in 8 seconds...
close

```

When I hook up CloudWatch, I get a semi-usable error message:

    2017-12-09 06:32:12.657 TRACEID:636c2ee2-3f87-58c6-f18c-4248f3190037 PRINCIPALID:4d1552d14416ab4198353b308538604794bcc3a0aa03c79050dd61d3afc20ee9 [ERROR] EVENT:MQTT Client Connect MESSAGE:Connect Status: AUTHORIZATION_ERROR

The client should be fixed to issue usable error messages.  It takes more undocumented steps to hook up cloud watch, making "Hello World" scenarios much more difficult to get going.

It would be helpful if the error messages also suggested remediation steps.   I have keys issued according to the IOT wizard, so I don't know what to do next...

**Comment by liuszeng** [comment]
Hi @paul-cipherlex ,

Thank you very much for using AWS IoT Node.js SDK.

I am assuming that you are using the following SDK sample:
https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/device-example.js

>Just fails with
>    attempting new mqtt connection...
>    offline
>    connection lost - will attempt reconnection in 4 seconds...
>    close
>    reconnect
>    connection lost - will attempt reconnection in 8 seconds...
>    close

The SDK will emit corresponding events based on the message arrival and client status change. In the sample, it just prints out a simple statement saying the client is offline and reconnecting in `offline` and `reconnect` event. You should always be able to change the way you handle these events by implementing your own handlers.

>The client should be fixed to issue usable error messages.

As for detailed error reporting, unlike HTTP, MQTT features a long live connection and strictly enforced protocol RFC that does not allow error messages being communicated back to the client. There is nothing much you can do on the client side.

> It takes more undocumented steps to hook up cloud watch, making "Hello World" scenarios much more difficult to get going.

AWS IoT emits some server side log to customer cloud watch logs. Documentation can be found here:
http://docs.aws.amazon.com/iot/latest/developerguide/cloud-watch-logs.html

From the cloudwatch log you provide I can see that you are having some authorization issue using X.509 cert based mutual auth. I would recommend you to take a look at the documentation about IoT policy configuration:
http://docs.aws.amazon.com/iot/latest/developerguide/pub-sub-policy.html

Thanks,
Liusu

**Comment by paul-cipherlex** [comment]
Hello:

I followed the example at:  http://docs.aws.amazon.com/iot/latest/developerguide/iot-device-sdk-node.html

And it says nothing about adding a policy to a certificate.

Are there step by step instructions for raspberry pi3 that actually work?  Having trouble finding one.

**Comment by paul-cipherlex** [comment]
After adding this policy, of which I could not find as an example in the documentation, the above example works:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Connect",
        "iot:Receive",
        "iot:Subscribe",
        "iot:GetThingShadow",
        "iot:DeleteThingShadow",
        "iot:UpdateThingShadow"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```

**Comment by paul-cipherlex** [comment]
I'm writing a how-to for my fellow devs, that will have step by step instructions that if followed will result in success.

Would you care for a copy when I'm done?

**Comment by liuszeng** [comment]
Hi @paul-cipherlex ,

>I followed the example at: http://docs.aws.amazon.com/iot/latest/developerguide/iot-device-sdk-node.html
>And it says nothing about adding a policy to a certificate.

Sorry that you are not able to find the documentation. It's in the first section in "AWS IoT SDK tutorials":
http://docs.aws.amazon.com/iot/latest/developerguide/iot-sdk-setup.html

Glad to know that the example is working for you.

Thanks,
Liusu

**Comment by paul-cipherlex** [comment]
Would you please add the [link to the SDK setup doc](http://docs.aws.amazon.com/iot/latest/developerguide/iot-sdk-setup.html ) to the README.md in the examples section?

That will help the next person who attempts to use the SDK.

I also note the link includes instructions for loading the wrong version of nodejs.  I gave feedback via the suggestions link in that doc.

**Comment by liuszeng** [comment]
Hi @paul-cipherlex ,

I have created an internal tracker for this documentation update request. It will be included in the future releases. Thank you again for your input.

Thanks,
Liusu
