### ISSUE TITLE
custom authorizer headers

### ISSUE THREAD

**Issue by Zacharis278** [aws/aws-iot-device-sdk-js#169]
I'm attempting to use a custom authorizer for browser clients and haven't had much luck getting it to work.  Turns out on further inspection I'm not seeing any of the custom authorization headers getting sent when attempting to connect.

Am I missing something?

client setup:
```
this.client = awsIoT.device({
      debug: true,
      protocol: 'wss-custom-auth',
      host: 'xxxxxxxxxxx.iot.us-west-2.amazonaws.com',
      customAuthHeaders: {
        'X-Amz-CustomAuthorizer-Name': 'test-authorizer',
        'X-Amz-CustomAuthorizer-Signature': 'xxxxxxxxxxxxxxxxx',
        'TestAuthorizerToken': 'xxxxxxxxxxx'
      }
    });
```

**Comment by liuszeng** [comment]
Hi @Zacharis278 ,

Thank you very much for using AWS IoT Device SDK for Node.js.

I have forwarded this issue to the corresponding internal team for better support/investigation. In the meantime, can you also share the logs when you were experiencing the issue?

Thanks,
Liusu

**Comment by Zacharis278** [comment]
As is tradition it takes opening an issue before I find the underlying problem  😉 .  I had not realized the browser implantation of websockets do not support adding additional headers to the request.

Is there any way to use a custom authorizer with browser clients?

**Comment by liuszeng** [comment]
Hi @Zacharis278 ,

Thank you very much for providing the information. Please bear with me while I am going through the code.

I was looking at the package.json file for the browser sample and found this line suspicious:
https://github.com/aws/aws-iot-device-sdk-js/blob/master/browser/package.json#L12

Are you using this browser sample in the SDK? Can you update the version of the device SDK and try again?

Thanks,
Liusu

**Comment by Zacharis278** [comment]
Yeah on further investigation my problem may be a wider one than something that can be addressed in this SDK alone.   The websocket implantation in the web browser itself does not support adding headers.  Yet, the custom authorizer setup needs to send that 'X-Amz-CustomAuthorizer-Name' header in order to identify what authorizer to use.

So, my broader question.  Is it in any way possible to use a custom authorizer if your client device is a browser?

**Comment by liuszeng** [comment]
Hi @Zacharis278 ,

I was able to duplicate your issue in Firefox on my side using browserify and the latest version of SDK with custom authorizer support. It seems that the required headers for custom authorization in the outgoing request are still missing event if it is configured in the SDK client:
![image](https://user-images.githubusercontent.com/14796906/33916128-2b85eb16-df5c-11e7-97c2-0c2fc527b782.png)

Unfortunately, using custom authorizer with AWS IoT requires extra headers to be in the handshake request, including authorizer name, token and signature. Unless there is a way have the browser include these headers in the outbound request, missing them would make this request an unauthorized one, resulting in a 403 HTTP response.

I have added an internal tracker for further investigation of this issue. Sorry for the inconvenience it has caused.

Thanks,
Liusu

**Comment by danilotorrisi** [comment]
Hi everybody,
the problem seems to be related to the WebSocket browser implementation. From what I understand, the WebSocket browser implementation does not accept custom HTTP headers via the option parameters.

**Comment by mlfarrell** [comment]
I just stumbled onto this today.  Does that mean you can't do custom iot auth in the browser at all??  That is what I've been working towards for a day now.  Are we forced to use cognito?

**Comment by fengsongAWS** [comment]
Hi @mlfarrell ,
As mentioned by @liuszeng , unless there is a way to include those headers, the custom auth will not work in browser envrionment. Yes, for now, the SDK does not wrap web headers into the handshake request. And as usual, cognito is the recommended way to communicate with iot service cloud.

**Comment by mlfarrell** [comment]
Put me on the list of people who definitely need custom auth in a browser and are requesting it.  I've heard (albeit I'm not a websockets expert) that there is a way to embed the info in the URL itself. Once it is possible, please add some kind of custom auth support to the SDK in the browser.

**Comment by vit21ik** [comment]
This code is correct but it doesn't work in browser because browser websocket client doesn't support custom headers.
This client works on nodejs.

**Comment by waynerobinson** [comment]
This is definitely something that we also require and I've just lost multiple days to this issue.

If you don't plan on supporting `wss-custom-auth` in this library, you might want to at least mention that this authentication mode doesn't work for browser in the README somewhere.

**Comment by AWSSteveHa** [comment]
Hi @waynerobinson,
I apologize for your difficulties with this. We are investigating how to overcome this limitation so we can enable custom auth support in the browser. You also raise a good point that there should be mention of this issue in the README. I'll make sure we address that.
Thank you.

**Comment by webmaxru** [comment]
Hi! If anybody uses Node-RED: I added a Custom Authorizer to the AWS IoT node: https://www.npmjs.com/package/node-red-contrib-aws-iot-custom-auth

**Comment by mlfarrell** [comment]
Gonna add in my two cents and unsub.  I solved this for myself by returning a STS temporary credential (a role that has IOT access) back to the client through a token-protected web API (I implemented the API via api gateway + lambda + custom authorizers).  I then used the temporary STS creds to initialize iot with no problems.  This should hold anyone over until the above is resolved.

**Comment by mlfarrell** [comment]
lol I just read mooyoul's comment

**Comment by ultrafez** [comment]
I'm going to join this issue by chiming in that I'm experiencing the same problem - I've been investigating custom auth and found that this limitation isn't described in the docs. Is there an update on this issue? It's been open for over 6 months now.

**Comment by rrrhys** [comment]
To send the headers in the connect request, please try
npm install --save git+https://github.com/rrrhys/websocket-stream.git

I've modified websocket-stream to pass through headers when supplied in the options (for a React Native project).

**Comment by ultrafez** [comment]
@rrrhys, the problem described in this GitHub issue is related to using this npm package in the browser - the root cause is that the WebSocket API implemented by browsers doesn't support adding custom headers, even thought the websocket protocol itself _does_ support custom headers.

The fix required from the AWS team is a way of indicating that the developer wants to use a custom authorizer via parameters in the URL, rather than by adding custom headers, as the URL is the only way of adding extra information to the websocket connection request.

An effective workaround has been described in [mooyoul's comment](https://github.com/aws/aws-iot-device-sdk-js/issues/169#issuecomment-387447701) and [mlfarrell's comment](https://github.com/aws/aws-iot-device-sdk-js/issues/169#issuecomment-388215712) which I too am using. This has also meant that I was able to use the smaller [mqtt.js](https://github.com/mqttjs/MQTT.js/) for my application rather than the heavier aws-iot-device-sdk since I offloaded generation of the presigned URL to a lambda rather than calculating the MQTT connection URL in the browser.

@AWSSteveHa, there still isn't any mention of this limitation in the README - can this be updated to avoid other people wasting time on this issue until it's addressed?

**Comment by rrrhys** [comment]
@ultrafez I completely understand. The fix I proposed makes this npm
package work in React Native with a custom authorizer. I realise my comment
could have been clearer.

**Comment by AWSSteveHa** [comment]
@ultrafez thank you for the reminder of mention of this limitation in the README. My apologies to anyone who spent time unnecessarily on this. The README is now updated.

**Comment by aniket91** [comment]
It's sad to see this does not work in browser environments. There is no support in Java SDK as well. Is there a way we can get this to work in React Native environment? Has anyone tried it? Thanks.

**Comment by eagene** [comment]
@ultrafez Can you explain what you're doing? I'm using cognito in the browser already for authentication and so can get temporary credentials, but I thought I needed to then generate a signed url in the browser in any case to connect to iot. Is that not the case? Or do you generate the presigned url in a lambda, return it to the browser, and then use the mqtt library?

BTW: I've managed to get this to work using my permanent login credentials (as a test), but am still getting auth errors using the temporary credentials -- although I've followed the documentation for adding permissions.

Thanks.

**Comment by jules-ofs** [comment]
For those who suggest using temporary sts credentials ( @mooyoul , @mlfarrell  ), one of the possible benefits of the custom authorizer is that it gives you a place to generate custom IOT Core policy to attach to identities.  I'm struggling to work out where / how are you attaching the IOT Core policy to your temporary credentials?  Are you attaching the policy in a lambda that is called manually?  If so, what happens when something goes badly wrong and a whole heap of requests come in at once - blowing the 15 transactions per second quota on AttachPolicy?

**Comment by stijndepestel** [comment]
Hi,

I've been running into the same issues with custom authentication headers and websockets in browsers, however I have noticed, the custom authentication is also supported using the querystring of the connection URI. 

If I change line [L137 of device/index.js](https://github.com/aws/aws-iot-device-sdk-js/blob/master/device/index.js#L175) which creates the connection UR to read the following: 
`return 'wss://' + hostName + path + "?x-amz-customauthorizer-name=authorizer-name&token=allow";`
my authentication lambda gets triggered.

Obviously, this should be passed on using the options. Can I create a PR for this fix or is this solution not optimal?

**Comment by bretambrose** [comment]
Support for custom auth via query params has been added via https://github.com/aws/aws-iot-device-sdk-js/pull/383.
