### ISSUE TITLE
Documentation for iOT SDK

### ISSUE THREAD

**Issue by livesankp** [aws/aws-iot-device-sdk-js#17]
Hello,

For each device how to create individual connections which can be maintained. For example.
I have one Hub which can communicate to Server and there are 3 Mobile devices who wants to control one Hub. As i have already developed similar thing but using signalr of asp.net. If i want to replace signalr with aws iot what should i do ? as my mobile app is already working calling asp.net web api.
So when web api receives event i want to publish that event to iot subscriber which is only one Hub.
Can you provide any good documentation for creating and maintaining connections. I am already maintaining connections in database so all i need is when iot connections starts from node.js i want to store in the same database that particular connection and when mobile app sends event i want to pass that event on that connection then my node.js program can handle it.

**Comment by gkwicker** [comment]
Hi livesankp,

Thanks for your question.  The AWS IoT platform allows devices and other clients such as mobile apps to communicate using a simple publish/subscribe model.  You won't need to implement your own database to connect clients with devices, as the AWS IoT platform handles that for you.  As long as both sides agree on which topics to use and the data format used for communication, they'll be able to talk to one another.  The [temperature-control example application](https://github.com/aws/aws-iot-device-sdk-js/tree/master/examples/temperature-control) in this SDK illustrates a very similar use case to the one you mention here; you can start one process in device simulation mode and then one or more in the simulated mobile application mode to interact with it.  Each process can run on a different host and the AWS IoT platform will connect them all.  The [README.md](https://github.com/aws/aws-iot-device-sdk-js/blob/master/README.md#programs) file contains documentation on running the example programs.  If you have further questions on using the AWS IoT platform, the [AWS Forums](https://forums.aws.amazon.com/index.jspa) are a great resource.
