### ISSUE TITLE
is there a way to access the underlying mqtt device?

### ISSUE THREAD

**Issue by jacksonloper** [aws/aws-iot-device-sdk-js#174]
It looks to me like the underlying `new mqtt.MqttClient(_wrapper, options)` is a private variable.  That makes some things hard to debug.  For example, at the moment AFAIK there is no way to check if the device is actually connected (e.g. using `mqtt.Client#connected`).  More generally it is kind of hard to debug because everything of importance is private.  

Possibly related: in your documentation, you say

```
//
// Device is an instance returned by mqtt.Client(), see mqtt.js for full
// documentation.
//
```

but this does not appear to be true.  Rather, Device is an instance of the `DeviceClient` class...

What is the big picture thinking about all this?

**Comment by bxpan** [comment]
Hi Jacksonloper,

Currently, you can tell whether it is connected by the "connect" callback function. For example: https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/device-example.js#L80  If you this callback function is not triggered, then it is not connected. However, we'll consider and evaluate the use case and necessity of adding an API to check the current connection status in the future.

**Comment by fengsongAWS** [comment]
Please open another thread if you still have questions.
