### ISSUE TITLE
Published messages are lost

### ISSUE THREAD

**Issue by RameshRM** [aws/aws-iot-device-sdk-js#181]
Hi , 

I use [iot-data](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IotData.html) from my Lambda to publish messages to all the clients. The messages are never received by the devices, they do work when the connections are warm. 

Can you help me on trouble shooting this

JUST a FYI.. All the clients connect w/single Device CERT

**Comment by fengsongAWS** [comment]
There are a few things you can verify.
1. Subscribe to the same topic using IoT console to see if you are able to receive messages. If not, there must be some problems when lambda publishing messages.
2. If you can receive message using console but not able to receive messages from device, double check your IoT Policy that you attached to certificate. Make sure you have correct policy or * on both your actions and resources.

**Comment by RameshRM** [comment]
@fengsongAWS Thanks for ur reply, I should have been more clear w/my question ,

It is not like i never able to subscribe to message, I am able to subscribe when the server started up and for a while after that I am not able to subscribe the messages and the Console subscription is good.

Thanks

Ramesh

**Comment by fengsongAWS** [comment]
Could you elaborate the use case? What server you are using to subscribe? What do you mean by saying you are able to subscribe for a while?

**Comment by RameshRM** [comment]
The server is a `nodejs` server using the `aws-device-sdk` and the publisher is a `nodejs lambda` 

The subscription is good when the server is started and able to see the messages are comming throu, after a while (I havent timed it)  I dont see any incomming messages.

**Comment by fengsongAWS** [comment]
Since you were able to subscribe and receive messages initially, that means you setup the rules engine, cert, policy correctly and the device SDK works fine. Also you mentioned that you try subscribing topics using console at the same time and the console could also receive messages. This probably is not related to SDK and I would recommend you look into your node.js server setup and running.

**Comment by RameshRM** [comment]
Ok, Thanks, One another quick question, which port the SDK Runs to subscribe message runs ?

**Comment by fengsongAWS** [comment]
MQTT over TLS with mutual certificate authentication using port 8883
MQTT over WebSocket/TLS with SigV4 authentication using port 443

**Comment by orber3** [comment]
Did you fixed it ? Same problem here
