### ISSUE TITLE
send message to iot device

### ISSUE THREAD

**Issue by mattman73** [aws/aws-iot-device-sdk-js#182]
Sorry to ask but I have been trying to work out how to send to my iot device, I have the device-example.js running and I can send test messages from 'Configure and test your device' page on AWS but I would like to now send messages from my 'Lambda' echo skill Node.js code.
I have tried to follow the SDK and reading on the web but as yet I have not managed to get it connected.
Please can anyone give me some pointers this would be great.
Many Thanks
Matt

**Comment by fengsongAWS** [comment]
If you are trying to do publish from lambda function, you should use aws sdk java script. Link is here: https://github.com/aws/aws-sdk-js  As for how to get start with Lambda function, you fould follow the lambda page here https://aws.amazon.com/lambda/ and developer guide here https://docs.aws.amazon.com/lambda/latest/dg/welcome.html.

This repo is mostly for AWS IoT Device SDK. If you have more questions on device SDK side, please feel free to open an issue on it. 

Thanks
