### ISSUE TITLE
Issue with windows-browserize.bat: 'C:\Program' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by pflugs30** [aws/aws-iot-device-sdk-js#183]
I was attempting to run the windows-browserize.bat file on the Lifecycle browser example on my Windows 7 x64 desktop.  When I executed the command `.\scripts\windows-browserize.bat examples/browser/lifecycle/index.js` in the **aws-iot-device-sdk-js** root directory, I received the error "`C:\Program' is not recognized as an internal or external command, operable program or batch file`".

I first ensured I had the latest npm and node versions available.  I then started adding `echo` statements to the batch file, looking for the command that caused the issue.  I found that lines 45 and 65 (which invoke the command `call %BROWSERIFY`.

I believe the root cause is the path on my machine for the Browserify package contains a space for `C:\Program Files\...`, and the space is not escaped with double-quotes.  My solution was to go to line 13 and add double quotes around the `%%a` variable.  Then, I was able to re-run the `windows-browserize.bat` script without errors and run the lifecycle example as expected.

Can anyone else confirm this issue?  Shall I create a pull-request?

**Comment by fengsongAWS** [comment]
Hi @pflugs30 ,
Thanks for your input for AWS IoT Node.js SDK. Please feel free to describe the issue and create a pull request on this. We will verify this and include it in the future release if it turns out to be a general issue. This will also be a good reference to other people who have similar issues.
