### ISSUE TITLE
Authorizing Direct Calls to AWS Services - Any working examples

### ISSUE THREAD

**Issue by muthumani-prabhu** [aws/aws-iot-device-sdk-js#184]
Any working examples which can explain the working of authorizing direct calls to AWS services (https://docs.aws.amazon.com/iot/latest/developerguide/authorizing-direct-aws.html). I tried all the possibilities to get it working, but no success so far. Would any of you please lend helping hand on this topic?

When I try accessing this link (https://<your-aws-account-id>.credentials.iot.region.amazonaws.com:443/role-aliases/<your-role-alias>/credentials
) to get temporary credentials, I am always seeing the response as "Not Found"

**Comment by fengsongAWS** [comment]
Hi @muthumani-prabhu ,
We do not have plans to add this to device sdk. You may refer to https://github.com/aws/aws-sdk-js aws javascript sdk which provide remote credential provider. I hope this thread might provide more background information to you .https://github.com/aws/aws-iot-device-sdk-cpp/issues/59

**Comment by muthumani-prabhu** [comment]
Anyone with this issue, please follow this forum link https://forums.aws.amazon.com/thread.jspa?messageID=817558&tstart=0. You can definitely make it work :-).
