### ISSUE TITLE
Where's the callback for failed auth

### ISSUE THREAD

**Issue by mlfarrell** [aws/aws-iot-device-sdk-js#185]
Whats the sanctioned proper way to handle expiration of temporary IAM credentials using this SDK so I can detect the need to re authorize?

**Comment by mlfarrell** [comment]
Does offline have event data so that I can know the reason is failed auth vs just a timeout?

**Comment by fengsongAWS** [comment]
No. The MQTT disconnect packet does not have payload or data. You will not know the error code.

**Comment by aravind08** [comment]
@fengsongAWS I'm starting to face this issue since last week after updating the ionic 3.5 -> 3.20. 

Here's my `ionic info`:

cli packages: (/Users/xxx/.nvm/versions/node/v9.8.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.1.0 browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.1.2 
    Node              : v9.8.0
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.3 Build version 9E145 

Environment Variables:

    ANDROID_HOME : /Users/xxx/Library/Android/sdk

Misc:

    backend : pro
