### ISSUE TITLE
RootCACertificate - Where and how?

### ISSUE THREAD

**Issue by gruberb** [aws/aws-iot-device-sdk-js#192]
When I register my device with the sdk, I need to provide:

- caPath
- certPath
- keyPath

I can download the  caCert and privateKey from the AWS IoT console. But what is the `YourRootCACertificate` and where do I get this from? I can download three files:

- xxx.certificate.pem.crt
- xxx.public.key
- xxx.private.key

This definetly needs clarification. Do I have to generate the `RootCACertificate` on my console? If yes, how and why?

**Comment by rajatprogrammer** [comment]
No, you don't generate your YourRootCACertificate because it is by default created by Amazon server you just download this file when you click on create certificate button the software 3 pem files one is public key and another one is  private Key and the Last one is rootCa file

**Comment by stt** [comment]
I don't think that's correct, if xxx.certificate.pem.crt is rootCa then what's your client cert?

When you create a cert in iot core it provides a link to this page:
https://docs.aws.amazon.com/iot/latest/developerguide/server-authentication.html#server-authentication-certs from there the one CA cert that appears to work with the example code is 
VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem (then it hits more errors but at least gets past "local issuer" verification)

Although if I try to verify it with `openssl verify` it still fails, probably it's missing some intermediary.
```
openssl verify -verbose -CAfile VeriSign-C3-CA-G5.pem certificate.pem.crt 
CN = AWS IoT Certificate
error 20 at 0 depth lookup: unable to get local issuer certificate
error /Users/stt/a749842d38-certificate.pem.crt: verification failed
```

This basic connection stuff is really poorly documented, I bet there's combined years of wasted human effort globally in people trying to get aws iot to do the simplest thing.

**Comment by stt** [comment]
I don't think that's correct, if xxx.certificate.pem.crt is rootCa then what's your client cert?

When you create a cert in iot core it provides a link to this page:
https://docs.aws.amazon.com/iot/latest/developerguide/server-authentication.html#server-authentication-certs from there the one CA cert that appears to work with the example code is 
VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem (then it hits more errors but at least gets past "local issuer" verification)

Although if I try to verify it with `openssl verify` it still fails, probably it's missing some intermediary.
```
openssl verify -verbose -CAfile VeriSign-C3-CA-G5.pem certificate.pem.crt 
CN = AWS IoT Certificate
error 20 at 0 depth lookup: unable to get local issuer certificate
error /Users/s/certificate.pem.crt: verification failed
```

This basic connection stuff IS poorly documented, I bet there's combined years of wasted human effort globally in people trying to get aws iot to do the simplest thing.

**Comment by graebm** [comment]
![Screen Shot 2020-04-20 at 3 50 30 PM](https://user-images.githubusercontent.com/24399397/79807358-806be180-831f-11ea-9716-6e0885bca35a.png)
