### ISSUE TITLE
How to implement the promise 

### ISSUE THREAD

**Issue by francophongvu** [aws/aws-iot-device-sdk-js#193]
Hi,

As I know, AWS SDK supported Promise, 
For example: 
```
var s3 = new AWS.S3({apiVersion: '2006-03-01', region: 'us-west-2'});
var params = {
  Bucket: 'bucket',
  Key: 'example2.txt',
  Body: 'Uploaded text using the promise-based method!'
};
var putObjectPromise = s3.putObject(params).promise();
putObjectPromise.then(function(data) {
  console.log('Success');
}).catch(function(err) {
  console.log(err);
});
```
however, for this IoT SDK, I don't know how to implement like that. Could anyone give me example?

**Comment by fengsongAWS** [comment]
Right now, IoT SDK does not implement promise API. This would be something we are interested and consider to implement in the future. So far, you may need to override and implement yourself if you do have this use case. Thanks for your interest in AWS IoT SDK.
