### ISSUE TITLE
Unable to establish connection with MQTT

### ISSUE THREAD

**Issue by RameshRM** [aws/aws-iot-device-sdk-js#196]
TypeError: nextTick is not a function

Stack Trace :

mqtt/lib/client.js:37:2
mqtt/lib/client.js:286:3
mqtt/lib/client.js:227

FYI, This is used along with aws iot **aws-iot-device-sdk/device/index.js:639**

Suddenly hit with this issue right b4 launch preparation, can someone look @ this earliest

Thx

**Comment by RameshRM** [comment]
Hi, can anyof you take a look at this at the earliest ? i am totally blocked for next release preparations

**Comment by fengsongAWS** [comment]
This error is thrown from mqtt.js. 

Did you run into this issue each time you start up your program? What environment are you using? Do you use SDK in browser or node ?
Are you able to run the sample code with basic setup or configuration?

**Comment by RameshRM** [comment]
This started throwing up from yesterday and it is running on `node` `mqtt` folks think this may be `aws sdk` problem https://github.com/mqttjs/MQTT.js/issues/774

**Comment by fengsongAWS** [comment]
How often did you see this error? Are you able to running samples successfully?

**Comment by RameshRM** [comment]
I am not able to connect even once, this was successfully working and the messages were working fine until yday . I see this error as and when .i try to establish a connection

**Comment by fengsongAWS** [comment]
The sdk is passing options to mqtt client at the first place. Are you able to run the sample code? Or is this something related to the way to invoke the client? Can you provide sample code to duplicate this?

**Comment by RameshRM** [comment]
```
//confit.deviceConfig contains the Cert, & Other Config options for the construcgtor 
var Device = awsIot.device(confit.deviceConfig);
```

**Comment by fengsongAWS** [comment]
Sorry, I am not able to duplicate your problem. This would probably due to environment config. I would suggest you try using sample code and see if it works or not. And if necessary, start plainly with mqtt.js and see if you still encounter the issue. This will help you identify where the problem occurs.

**Comment by fengsongAWS** [comment]
Close this thread for now. Please open another thread if you have more questions.

**Comment by oprince** [comment]
The error occurred for me after I have upgrade few node modules which seems as MQTT dependencies.  It was solved by re-installing MQTT module.
