### ISSUE TITLE
Support for Greengrass Discovery

### ISSUE THREAD

**Issue by Mayank-Volansys** [aws/aws-iot-device-sdk-js#198]
We are planning to use Greengrass, So, I am curious to know when AWS add support for Greengrass Discovery in JavaScript SDK

Please update me ASAP!

Thanks In Advance

**Comment by fengsongAWS** [comment]
Hi @Mayank-Volansys ,

Thanks for your interest in AWS IoT Device SDK. We are working on Greengrass Discovery feature. However we cannot tell a specific release date at this point. I will get back to you as soon as we have that out. Please watch/fork the repo for a future release.

**Comment by Mayank-Volansys** [comment]
Hi @fengsongAWS  ,

Thanks for letting us know about this update

**Comment by brugnara** [comment]
In the meanwhile I have pushed a simple wrapper to the RestAPI in order to get this feature. 

Hope this helps: https://www.npmjs.com/package/aws-iot-greengrass-discovery

**Comment by jmklix** [comment]
Please check out the [v2](https://github.com/aws/aws-iot-device-sdk-js-v2) sdk for Greengrass Discovery support.
