### ISSUE TITLE
aws-iot-device-sdk-js cannt work

### ISSUE THREAD

**Issue by Pillar1989** [aws/aws-iot-device-sdk-js#20]
Hello
   I have installed the sdk on my beaglebone.
  root@beaglebone:~# node
> var awsIot = require('aws-iot-device-sdk')
undefined
> 
and request the certificate file from https://us-west-2.console.aws.amazon.com/iot/home?region=us-west-2#/dashboard.  Change the file name.

root@beaglebone:~# ls awsCerts/ 
certificate.pem.crt  private.pem.key  root-CA.crt
root@beaglebone:~# 
root@beaglebone:~# cat test.js 
var awsIot = require('aws-iot-device-sdk');

var device = awsIot.device({
   keyPath: '/root/awsCerts/private.pem.key',
  certPath: '/root/awsCerts/certificate.pem.crt',
    caPath: '/root/awsCerts/root-CA.crt',
  clientId: 'myAwsClientId',
    region: 'us-east-1'
});

//
// Device is an instance returned by mqtt.Client(), see mqtt.js for full
// documentation.
//
device
  .on('connect', function() {
    console.log('connect');
    device.subscribe('topic_1');
    device.publish('topic_2', JSON.stringify({ test_data: 1}));
    });

device
  .on('message', function(topic, payload) {
    console.log('message', topic, payload.toString());
  });
Run the example. But it print nothing. so What's wrong?

**Comment by Pillar1989** [comment]
the root-CA.crt  download from https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem

**Comment by nhira** [comment]
Try running the echo-example as described here.  If it works, you should be able to see changes you push from the AWS IoT console on the screen ...
https://github.com/aws/aws-iot-device-sdk-js#echo-examplejs

You can add ``debug: true`` when constructing the Thing Shadow to see connection logs.

Hope this helps!

-h

**Comment by gkwicker** [comment]
Hi,

It looks like you may have created your certificates in the us-west-2 region but are trying to connect to the us-east-1 region.  You'll need to connect to the region that you created your certificate in, as mentioned in nhira's response above.

**Comment by Pillar1989** [comment]
Haha, I have a stupid mistakes. But It's still not work.
root@beaglebone:~/aws-iot-device-sdk-js/examples# node echo-example.js --aws-region=us-west-2 --certificate-dir=/root/awsCerts/ --thing-name=led --debug=true
connected to things instance, registering thing name
offline
close
reconnect
connected to things instance, registering thing name

and I run the example test:
var awsIot = require('aws-iot-device-sdk');

var device = awsIot.device({
   keyPath: '/root/awsCerts/private.pem.key',
  certPath: '/root/awsCerts/certificate.pem.crt',
    caPath: '/root/awsCerts/root-CA.crt',
  clientId: 'myAwsClientId',
    region: 'us-west-2'
});

//
// Device is an instance returned by mqtt.Client(), see mqtt.js for full
// documentation.
//
device
  .on('connect', function() {
    console.log('connect');
    device.subscribe('topic_1');
    device.publish('topic_2', JSON.stringify({ test_data: 1}));
    });

device
  .on('message', function(topic, payload) {
    console.log('message', topic, payload.toString());
  });
root@beaglebone:~# node test.js 
connect

it should print topic and payload.

**Comment by Pillar1989** [comment]
Any update?

**Comment by gkwicker** [comment]
Hi,

The echo example (echo-example.js) is for use when testing with the AWS console.  Have you tried running device-example.js as specified in the [README.md](https://github.com/aws/aws-iot-device-sdk-js#programs)?  This example program is probably the simplest way for you to verify that you are able to connect to the AWS IoT platform.  Can you try running device-example.js as specified in the instructions in the README and let us know if that is working?

**Comment by Pillar1989** [comment]
root@beaglebone:~/aws-iot-device-sdk-js/examples# node device-example.js --aws-region=us-west-2 --certificate-dir=/root/awsCerts/ --thing-name=led 
connect

Just response connect message, mqtt still dont response

**Comment by gkwicker** [comment]
Hi,

You need to run two copies of all the example programs (except for echo-example.js, which works with the AWS console).  So, in one shell you'd do:

```
node device-example.js -aws-region=us-west-2 --certificate-dir=/root/awsCerts --test-mode=1
```
And in another shell, you'd do:

```
node device-example.js -aws-region=us-west-2 --certificate-dir=/root/awsCerts --test-mode=2
```

If you only have one console to work with, you can run the programs in the background like this:

```
node device-example.js -aws-region=us-west-2 --certificate-dir=/root/awsCerts --test-mode=1 &

node device-example.js -aws-region=us-west-2 --certificate-dir=/root/awsCerts --test-mode=2 &
```
Note that each program has to be given a different value for '--test-mode'; one program runs with test-mode=1 and another runs with test-mode=2.  Also note that the '--thing-name' option does not do anything for this example program.

**Comment by Pillar1989** [comment]
root@beaglebone:~/aws-iot-device-sdk-js/examples# node device-example.js --aws-region=us-west-2 --certificate-dir=/root/awsCerts --test-mode=2
offline
close
reconnect
connect
message topic_2 {"mode1Process":1}
message topic_2 {"mode1Process":2}
message topic_2 {"mode1Process":3}

Haha, it works, thank you very much.

**Comment by lamiastella** [comment]
When I am trying to run the following node.js example from AWS IoT I get this error:

pi@raspberrypi:~/aws-iot-device-sdk-js/examples $ node device-example.js -g

private.pem.key doesn't exist (--help for usage)
However I have the private.pem.key in ~/certs folder as requested by the tutorial.

pi@raspberrypi:~/aws-iot-device-sdk-js/examples $ vi device-example.js 
pi@raspberrypi:~/aws-iot-device-sdk-js/examples $ ls ~/certs/private.pem.key 
/home/pi/certs/private.pem.key

Please have a look at the question in Stackoverflow as well. Thanks!

**Comment by lamiastella** [comment]
Solved the problem by giving the paths like the following: pi@raspberrypi:~/aws-iot-device-sdk-js/examples $ node device-example.js --aws-region=us-west-2 --certificate-dir=/home/pi/certs --test-mode=2
