### ISSUE TITLE
Question: Sending events to a device during unit testing.

### ISSUE THREAD

**Issue by lucasowens** [aws/aws-iot-device-sdk-js#202]
Is there a way for me to simulate the various device events in a unit test? I would like to send events like 'connect' to a device manually in a unit testing env. Is this possible?

**Comment by fengsongAWS** [comment]
> I would like to send events like 'connect' to a device manually in a unit testing env

By unit testing, what do you mean sending events? Normally this should happen in the same environment where you mock the device or MQTT client. If you are talking about sending mock mqtt server, e.g. sending connack when some devices making a connect call, then you would probably build up a local message broker and do authentication.

**Comment by lucasowens** [comment]
I was thinking about what I was testing incorrectly, Thank you for the quick response! I will close this.
