### ISSUE TITLE
Implementing Request/Reply in AWS Lambda

### ISSUE THREAD

**Issue by ghost** [aws/aws-iot-device-sdk-js#205]
Currently I am working on a Lambda function used by API Gateway to implement a Request/Reply for communication with a device. The below code is working fine when it is executed the first time:

```
var awsIot = require('aws-iot-device-sdk');

  var device = awsIot.device({
  keyPath:    'certs/someid-private.pem.key',
  certPath:   'certs/someid-certificate.pem.crt',
  caPath:     'certs/VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem',
  clientId:   'nodejs-client123',
  host:     'blabla.iot.eu-central-1.amazonaws.com'
  });

exports.handler = (event, context, callback) => {

  console.log('Start');
  device
    .on('connect', function() {
      console.log('connect');
    });
  device.subscribe('test/reply', null, (err, granted) => {
    console.log(err);
    console.log(granted);
  });
  console.log("subscribed");
  device.publish('test', JSON.stringify({ test_data: 1 }), { qos: 1 });
  device
    .on('message', function(topic, payload) {
      console.log('message', topic, payload.toString());
      device.unsubscribe('test/reply', () => {
        device.end(false, function() {
          console.log("Disconnect...");
          callback(null, payload.toString());
        });
      });


    });
  console.log('End');
};
```

The first time, the log is:

> START RequestId: c6646eba-3260-11e8-a34a-e7b15eb6afc2 Version: $LATEST
> 2018-03-28T08:19:46.656Z	c6646eba-3260-11e8-a34a-e7b15eb6afc2	Start
> 2018-03-28T08:19:46.657Z	c6646eba-3260-11e8-a34a-e7b15eb6afc2	subscribed
> 2018-03-28T08:19:46.676Z	c6646eba-3260-11e8-a34a-e7b15eb6afc2	End
> 2018-03-28T08:19:46.798Z	c6646eba-3260-11e8-a34a-e7b15eb6afc2	connect
> 2018-03-28T08:19:47.078Z	c6646eba-3260-11e8-a34a-e7b15eb6afc2	null
> 2018-03-28T08:19:47.116Z	c6646eba-3260-11e8-a34a-e7b15eb6afc2	[ { topic: 'test/reply',
>     qos: 0 } ]
> 2018-03-28T08:19:47.444Z	c6646eba-3260-11e8-a34a-e7b15eb6afc2	message test/reply Got your message:{"test_data":1}
> 2018-03-28T08:19:47.483Z	c6646eba-3260-11e8-a34a-e7b15eb6afc2	Disconnect...
> END RequestId: c6646eba-3260-11e8-a34a-e7b15eb6afc2
> REPORT RequestId: c6646eba-3260-11e8-a34a-e7b15eb6afc2	Duration: 880.75 ms	Billed Duration: 900 ms 	Memory Size: 128 MB	Max Memory Used: 38 MB	

All other executions do not execute the publish of the message:

> START RequestId: 68bd4c3d-3262-11e8-9ebd-1339f0382184 Version: $LATEST
> 2018-03-28T08:31:28.096Z	68bd4c3d-3262-11e8-9ebd-1339f0382184	Start
> 2018-03-28T08:31:28.096Z	68bd4c3d-3262-11e8-9ebd-1339f0382184	subscribed
> 2018-03-28T08:31:28.096Z	68bd4c3d-3262-11e8-9ebd-1339f0382184	End
> END RequestId: 68bd4c3d-3262-11e8-9ebd-1339f0382184
> REPORT RequestId: 68bd4c3d-3262-11e8-9ebd-1339f0382184	Duration: 15.10 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 39 MB	

When I put the instantiation of the device into the handler, then it works for all executions, but is very slow. So my assumption is, that the device object still exists in the node runtime after the first execution. So my question is, can I still use this object and what do I have to do, that I can use it in all other executions?

**Comment by fengsongAWS** [comment]
Hi,
MQTT is long live connection. So it is against this behavior when you apply aws iot device sdk which is mqtt based connection in AWS Lambda function since the latter will be killed once the execution finished. I would recommend AWS SDK in node.js for your purpose to do one time publish in HTTP request. 
Please take reference from here: https://github.com/aws/aws-sdk-js

**Comment by kirnberger** [comment]
Hi fengsong,

indeed, my first attempt was using the aws sdk, but I realized, that the sdk only supports publishing messages to a mqtt topic:

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IotData.html

 But my challenge is to use mqtt in a synchronous way. I want to send a message to a topic and listening on a reply topic for the response in the same lambda function:

- subscribe to the reply topic, e.g. /replies/<id>
- publish a message with <id> to a dedicated client topic
- wait for the response on the subscription
- lambda times out, when

So, what is the common solution to achieve this? 

Kind Regards,
Marcell

**Comment by fengsongAWS** [comment]
Back to your initial questions, after the first execution, the device object does not exist in lambda container if the lambda container finished. And you have to put instantiation in handler because that is the entry point of lambda invocation.  The reason that execution is slow is probably related to lambda cold start. That is my initial guessing. If you want to learn more about lambda and questions, feel free to open a thread in aws lambda forum https://forums.aws.amazon.com/forum.jspa?forumID=186. 

So, having lambda function stays in connection and listen for something incoming is somehow against the behavior of lambda function. There is no way to guarantee that your lambda container will always stay live and waiting for incoming messages.

**Comment by xiongyu0523** [comment]
I have the same questions.

aws-sdk uses http, which only allow publish data to Device Gateway, is there any method to get sync response on MQTT subscription in Lambda? 

I have see many topics asking the same question but nobody gives clear answer
https://forums.aws.amazon.com/thread.jspa?messageID=741493&#741493

**Comment by mkozjak** [comment]
Interesting topic. I have a use-case where I'd like to reuse the IoT Device websocket connection.
One way to implement request/reply is to get the transport instance (websocket) from this library and feed it into a library such as [rpc-websockets](https://github.com/elpheria/rpc-websockets) if it provided a support to feed the socket to it. That's one way to achieve synchronous communication between devices.

**Comment by FanchenBao** [comment]
Consider using thing shadow to enable communication between iot thing and lambda. Lambda can publish message to an iot topic. Instead of having iot thing respond on another topic, it can update its thing shadow. Then lambda can get the iot thing's response from the updated thing shadow.
