### ISSUE TITLE
Trouble using with Require.js

### ISSUE THREAD

**Issue by devinbostIL** [aws/aws-iot-device-sdk-js#207]
Hi,

We're having issues getting this code imported into a client application that uses require.js. We're getting an error that the module is not defined, like this: https://stackoverflow.com/questions/29652716/module-exports-module-is-not-defined

We tried using the instructions here: http://requirejs.org/docs/commonjs.html#autoconversion
to convert it to the asynchronous module definition (AMD) module structure, but we get no output returned... We also tried running it by omitting "node" from the command like as mentioned near the bottom of this page: https://github.com/requirejs/r.js
but we still got no output. The codebase is using Grunt, Bower, and requirejs... so it's an older codebase that we're stuck with at the current moment. But we need to find a way to get this SDK working before we will be able to get additional time to clean up the code, so we're trying to figure out how to get it implemented. Any ideas?

**Comment by fengsongAWS** [comment]
Hi @devinbostIL ,
Thanks for your interest in IoT Device SDK. This seems more likely related to the specific platform setup and compatibility. We did not test the SDK with require.js module and unfortunately, I am not able to duplicate the issue here.
