### ISSUE TITLE
running echo-example.js not working

### ISSUE THREAD

**Issue by MichaelStephan** [aws/aws-iot-device-sdk-js#21]
Hello,

I would like to run the echo-example.js example with "node examples/echo-example.js -F config.json -f . --thing-name testThing1". Unfortunately it seems that the client certificate is rejected by aws.

error [Error: 140735187984384:error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1275:SSL alert number 46
]

I'm using all the assets which were created during the "connect a device" workflow. Maybe you have hints what it wrong.

Thanks

**Comment by MichaelStephan** [comment]
solved by switching the region with -g eu-west-1

**Comment by lamiastella** [comment]
Hi Michael, 
Where did you find the config.json file? I can't find any tutorial for it

**Comment by MichaelStephan** [comment]
hello, unfortunately I dont know anymore where I got the information. Just use the following example:

{
  "host": "A3PMH9QV6IOHKE.iot.eu-west-1.amazonaws.com",
  "port": 8883,
  "clientId": "XXX",
  "thingName": "YYY",
  "caCert": "root-CA.crt",
  "clientCert": "XXX-certificate.pem.crt",
  "privateKey": "YYY-private.pem.key"
}

When creating a new thing, all the clientCert, privateKey, ... can be downloaded. Hopefully it helps.

**Comment by johnrotach** [comment]
It's important to call out that the host in this config is account-specific.  A new prefix is generated for each AWS IoT user's account.  You can determine your prefix using the AWS CLI or by clicking on any Thing in the AWS IoT Console.  Example AWS CLI command usage:

```
$aws iot describe-endpoint
```
which will respond:
```
{
   "endpointAddress": "<YOUR SPECIFIC PREFIX>.iot.<YOUR REGION>.amazonaws.com"
}
```

**Comment by piya23300** [comment]
Thank you @MichaelStephan for the solution.

@monajalal can config at `/examples/lib/cmdline.js` file. you will see `region` to change it that you want.

```
default: {
         region: 'ap-southeast-1',
```
