### ISSUE TITLE
Callback problem when trying to register already registered thing

### ISSUE THREAD

**Issue by nodejs-apps** [aws/aws-iot-device-sdk-js#210]
_register_ function in **/thing/index.js** doesn't call callback function if the thing already registered and process hangs on. Managing registered things in the app state and don't trying to register them again may be a solution but adding  `callback()` in line 618 would be a better solution.

**Comment by fengsongAWS** [comment]
Hi @nodejs-apps ,
Thanks for your interest in Node.js SDK. Please feel free to submit a PR if you think about a better solution. We will take it through our internal pipeline and consider to release it in the future.

Thanks,
Fengyi

**Comment by liuszeng** [comment]
Closing as it is captured in the following PR:
https://github.com/aws/aws-iot-device-sdk-js/pull/211
