### ISSUE TITLE
Require http proxy support

### ISSUE THREAD

**Issue by deejvince** [aws/aws-iot-device-sdk-js#212]
We have IOT devices which we require to use the wss protocol to connect to AWS-IOT. (JOBS api).

These devices are sometimes in corporate networks that requires to use an explicit proxy.

The SDK doesn’t have support for a Proxy - but we think it’s mandatory to support these use cases.

Would like to see proxy support in the JavaScript device-sdk.

**Comment by fengsongAWS** [comment]
Hi @deejvince ,
Thanks for the feature request. We will take this into account and take appropriate plans on it. At the same time, please feel free to submit a pull request if you have some thoughts on it as well.

**Comment by deejvince** [comment]
Hi,

We have submitted a pull request for supporting an http proxy for websockets

**Comment by xuaoran** [comment]
Hi @deejvince ,

Thank you for the pull request. We have seen a pull request and want to make sure that it is from yours: (the requester name is not yours)

https://github.com/aws/aws-iot-device-sdk-js/pull/214

**Comment by deejvince** [comment]
Yes, that is the correct pull request.

**Comment by fengsongAWS** [comment]
Tracking in this https://github.com/aws/aws-iot-device-sdk-js/pull/214 . Close this thread for now.
