### ISSUE TITLE
Using Lambda Function to Connect to AWS IoT and set it as Actions of IFTTT

### ISSUE THREAD

**Issue by Oxbowl** [aws/aws-iot-device-sdk-js#213]
Hi there everyone, I was trying to develop a lambda function which will connect to the AWS thing and publish an MQTT message, I want to receive these published messages on a Raspberry Pi which is connected to my room lights as well.

I managed to create the simple mobile app to control my room lights and Air-conditions. But the problem now that I wanted to configure the Lambda function and AWS IoT to do more smart way such as home automation. 

I would like to use the 3rd party app like weather channel as the Trigger in IFTTT to control my air-conditions automatically once the outdoor temperature in my location reaches 30 and above. Since I am testing this lambda function now, I am not using the event to trigger the connection and message publishing to IFTTT, I am not sure how to configure the IFTTT service channel too. I did downloaded quite a number of example at IFTTT channel, but it didn't help me at all. 

After then this, I alr got my Raspberry Pi with connected to the IR blaster and it works fine with the Simple Andriod that design by me. So right now I want to have the home automation system by using the IFTTT, the only thing that I confused is how to Using Lambda Function to Connect to AWS IoT and set it as Actions of IFTTT. Any one can help?

**Comment by fengsongAWS** [comment]
AWS IoT Device SDK is based on MQTT protocol which is long live connection. That's where you also get concept of `subscribe`. In this case, this SDK is not designed for use in Lambda function. If you only care about doing publish once and do not care about long live functionality e.g. subscribe. You are recommended to use AWS SDK in lambda function. For example https://github.com/aws/aws-sdk-js . By using AWS SDK, you are open to all the resources that AWS provides.

**Comment by Oxbowl** [comment]
Thanks, Will try to figure out first

**Comment by fengsongAWS** [comment]
Please open another thread if you still have questions.
