### ISSUE TITLE
Getting connection status

### ISSUE THREAD

**Issue by dushyantbangal** [aws/aws-iot-device-sdk-js#216]
How do I check if the client is connected or not?

From the Device class example, I understand that the Device is an instance returned by mqtt.Client()
mqtt.js has a `connected` flag https://github.com/mqttjs/MQTT.js#connected

However, `device.connected` gives me `undefined`

**Comment by xuaoran** [comment]
Hi @dushyantbangal 

Can you provide more details how you use `device.connected`?

Thanks,
Aoran

**Comment by fengsongAWS** [comment]
Hi @dushyantbangal ,
The connected variable is not exposed at this time. We will consider use cases like this in the future. For now, the connect call back will be triggered once the client is connected. You can also maintain a variable like this. This is also how mqtt.js maintain `connected` variable

**Comment by dushyantbangal** [comment]
@xuaoran my idea was to check `if(device.connected)` before I call publish.
@fengsongAWS is there any way to put timeout on a publish call? I noticed the callback is never called when there is loss in connectivity.

**Comment by fengsongAWS** [comment]
why do you want to put timeout in a publish call? Are you using qos 1? Which callback is never triggered? Connect callback or publish callback?
