### ISSUE TITLE
Question: do clients automatically disconnect after detaching authorization policies?

### ISSUE THREAD

**Issue by rclai** [aws/aws-iot-device-sdk-js#217]
Not sure where the right place is to ask this.

I am testing a setup where I'm using Cognito identities to interact with the IOT platform. I tested with full `iot:*` access.

I managed to connect to the broker via `getOpenIdTokenForDeveloperIdentity` then `getCredentialsForIdentity` to pass the credential data to `updateWebSocketCredentials`. Then I wanted to see what happens if I detach the `iot:*` policy from the identity and I noticed that the client's session was still connected until I refreshed the page.

Is this expected behavior? I was hoping that it would automatically disconnect.

**Comment by rclai** [comment]
I had set the shadow instance to ping every 5 seconds, but it kept ping ponging just fine after I had detached the policy. Only when I refreshed the page did it not let me in anymore.

**Comment by fengsongAWS** [comment]
This is more about control plane API and not quite related to SDK. Please go to  [IoT Forum](https://forums.aws.amazon.com/forum.jspa?forumID=210) and create a thread there. Someone will help you from there. 
Thanks.

**Comment by gkwicker** [comment]
Hi @rclai, it can take a few minutes for policy changes to take effect on existing connections, but for new connections you should notice the change immediately.  See [this AWS Forum Post](https://forums.aws.amazon.com/thread.jspa?messageID=703662) for more information.  Let us know if this information is helpful, and thanks for using AWS IoT.
