### ISSUE TITLE
Forward the publish message to mqtt.js even when offlineQueueing is false

### ISSUE THREAD

**Issue by dushyantbangal** [aws/aws-iot-device-sdk-js#219]
MQTT.js has its own queuing mechanism and store to persist the packets if the device is offline.
It handles the condition way better than `aws-iot-device-sdk`.

Refer to the issue:
https://github.com/mqttjs/MQTT.js/issues/818

When the connection is not made, and `publish` is called, `aws-iot-device-sdk` maintains its own offline queue. However, if the device is restarted, the data is lost. MQTT.js supports persistent storage, but this SDK does not forward the calls to MQTT.js

Atleast forward the calls when `offlineQueueing` is set to `false`

Everything works fine when I removed the `if` condition at
https://github.com/aws/aws-iot-device-sdk-js/blob/234d170c865586f4e49e4b0946100d93f367ee8f/device/index.js#L839

**Comment by fengsongAWS** [comment]
You are right that iot-device-sdk does not support persistent storage. It handles the offline logic for the reason of better handling throttling, AWS IoT limit and etc. For example, AWS IoT could only support subscription of 8 topics at once and mqtt.js would dump everything in the topic array to IoT which will cause failures. We will be working on improvement of this SDK and at the same time, please feel free to submit any pull request that you think could better support the functionality.

**Comment by dushyantbangal** [comment]
@fengsongAWS, actually, it does support persistent storage in a way.
When the connection goes offline, the SDK takes a while to detect the event and `_filling()` still returns false. Hence, the queuing used here is the one build in MQTT.js
If you use a store there, the packets are stored in that store.

I thought of sending a PR by removing the `if` at 
https://github.com/aws/aws-iot-device-sdk-js/blob/234d170c865586f4e49e4b0946100d93f367ee8f/device/index.js#L839

This `if` seems to be only to block the publishing when the device is offline. However, removing that will mean the publishes will be sent to MQTT.js, which will use its own queuing.
This will break `offlineQueueing:false` as the data will still be queued.

The other way would be to add another field to options. Something that will just turn off the SDK's queuing. But I think that will just confuse users.

**Comment by fengsongAWS** [comment]
What if you turn off offlineQueueing and does that give you a way of using MQTT.js queue?

**Comment by dushyantbangal** [comment]
No, like I mentioned, it doesn't forward data to MQTT.js when `offlineQueuing:false` and the connection is down.
It doesn't fire the publish call when.

**Comment by lavaxun** [comment]
@dushyantbangal which solution do you used to enable the offline handling with mqtt.js?

**Comment by dushyantbangal** [comment]
@lavaxun, I was using `mqtt-nedb-store`. But just switch to `mqtt-level-store` yesterday.

In the aws sdk settings, I am setting `offlineQueuing:false` so that it doesn't use its own memory queuing. You supply the mqtt store in the same settings object.

Also, I'm commenting out the `if` condition mentioned in my [previous comment](https://github.com/aws/aws-iot-device-sdk-js/issues/219#issuecomment-387721705).

With this setting, aws sdk will forward all the publishes to `mqtt.js`, no matter what the connection status it. The store implementation of `mqtt.js` will take care of queuing.

**Comment by lavaxun** [comment]
@dushyantbangal brilliant! I'm also thinking to use the level-db as the queue persistent storage.
Thanks for sharing the solution.

**Comment by dushyantbangal** [comment]
@lavaxun you're welcome. `nedb` has lots of issue, and an important one is 256 MB limit. Once the filesize exceeds that, it cannot compact it my removing the uploaded records. So dont go there, go with `mqtt-level-store`

**Comment by lavaxun** [comment]
@dushyantbangal can you share sample code of how your settings object and .publish() looks like? 
It seems like if I use `qos: 0` then it will publish the message to IoT Core directly but not saving to the level-db. 
if I use `qos: 2` it will only go into level-db but not the IoT Core. (regardless if the device is online or offline)

**Comment by lavaxun** [comment]
Managed to have the offline queue working. 
It looks like I have to use `qos: 1`.

MQTT stream is closed right after the connection is established. 
Not sure why.

**Comment by dushyantbangal** [comment]
@lavaxun AWS IoT core rejects `qos: 2`, thats why.
They've mentioned that in the [limits document](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot)

**Comment by dushyantbangal** [comment]
@ColdenCullen We found a way to to make changes in `aws-iot-device-sdk-js` to make this work, but as long as those changes are not available in `aws-iot-device-sdk-js`, shouldn't this issue remain open?

**Comment by ColdenCullen** [comment]
I'm sorry, I saw the last comment about QoS and thought that was the resolution, but I can see now that that's not the case. Reopening.
