### ISSUE TITLE
Unsure about the end of the shadow update lifecycle

### ISSUE THREAD

**Issue by rclai** [aws/aws-iot-device-sdk-js#220]
I'm trying to build the following flow where I have:

1. A mobile app
2. A thing (a light bulb in this example)

I understand that if I want the app to turn on the light I would update the shadow by setting `state.desired.on` to `true`. This would then give me a status of `accepted` (or `rejected`/`timeout`), then a `delta` would also be published (which the app apparently also receives), which will be consumed by the subscribed light bulb, turn itself on, and update the shadow with `state.reported.on` as `true`. Now that `desired` and `reported` match, how will the mobile app know that the update was successful?

Is the mobile app supposed to listen to the `foreignStateChange` event to know that the light turned on (to know of the new reported `on` state)?  This is not clear because the documentation says it's "different _clients_". Is a thing considered a client? I am unsure because I've been testing using the AWS IoT console's shadow document editor, and don't know if the events emitted from updating the document there are different from events emitted when a real (hardware) thing sends updates.

**Comment by fengsongAWS** [comment]
The accepted status event will tell you that your operation is accepted. By receiving accepted event, your mobile app should assume that the update was successful. 

The `foreignStageChange` event is triggered by third `controller` (you can think of a third switch) which tries to turn on the light bulb in your case. So, your first switch should be always in sync with the status of lights and should know who did that operation. In this case, the mobile app(switch) knows that some other switches which is not me tries to update the light bulb.

**Comment by rclai** [comment]
Thanks for the info on `foreignStageChange`.

How can I possibly use the update/accepted status as my way of knowing that the light actually turned on if it only indicates that the shadow was updated? I need proof from the light (device) that it turned itself on. Isn't that why the device is supposed to update the shadow with its newly `reported` state? I'd like to know how the mobile app knows when the device has updated the reported state to match the desired state, otherwise I can't just show the user on the UI that the light has turned on because the "turning the light on" operation is still pending.

**Comment by rclai** [comment]
If I'm not mistaken, looks like I can listen to `foreignStageChange` to know that the light turned on.

**Comment by rinatio** [comment]
@fengsongAWS Since it's somewhat related, I'd ask here instead of creating another issue. Why don't use use `foreignStateChange` event in the `temperature-monitor` example and set an interval polling the IoT every 3 seconds? What's the benefit over using `foreignStateChange`?
