### ISSUE TITLE
Integration with Angular 6

### ISSUE THREAD

**Issue by czechk** [aws/aws-iot-device-sdk-js#223]
Hi
We are having build breaks after migrating to Angular 6.
This could possible to ( https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814 )

ERROR in ./node_modules/aws-iot-device-sdk/common/lib/tls-reader.js
Module not found: Error: Can't resolve 'fs' in '/../node_modules/aws-iot-device-sdk/common/lib'
ERROR in ./node_modules/aws-iot-device-sdk/device/index.js
Module not found: Error: Can't resolve 'fs' in '/../node_modules/aws-iot-device-sdk/device'
ERROR in ./node_modules/aws-iot-device-sdk/device/index.js
Module not found: Error: Can't resolve 'path' in '/../node_modules/aws-iot-device-sdk/device'
ERROR in ./node_modules/aws-iot-device-sdk/device/lib/tls.js
Module not found: Error: Can't resolve 'tls' in '/../node_modules/aws-iot-device-sdk/device/lib'

**Comment by fengsongAWS** [comment]
Hi @czechk ,
It seems that you need to disable fs in angular environment. This was always the problem different in node and web. We do not test this sdk in angular environment yet and we will see what we can do in the future to better support web environment. At the same time, please feel free to submit pr if you have some thoughts on it.

**Comment by stonecourier** [comment]
We are facing the same issues with our Angular project.

**Comment by mordka** [comment]
Angular 6 doesn't support `fs` and because we can't eject webpack configuration from Angular any more then we can't tell webpack to ignore this module.

**Comment by hblanken** [comment]
@fengsongAWS  - any chance to update the SDK to support modern angular6 apps?

**Comment by dornaveh** [comment]
anyone found a solution?

**Comment by killbox-code** [comment]
@hobojoe thanks so much for posting that link - not something I would consider permanent but it does the job in a simple way for the foreseeable future.

**Comment by fengsongAWS** [comment]
This is an environment specific use case. We will consider this support in the future. At this point, feel free to submit any patch or pr to the repo. Thanks for your interest in AWS IoT  Device SDK.

**Comment by eranation** [comment]
@hobojoe thanks for the patch, but this didn't work for me, I now get a "Error: No browser version for node.js core module fs available" where there any other steps you had to do?

**Comment by killbox-code** [comment]
@eranation - The file below is saved in my project and executed on the npm 'postinstall' hook:

### tools/postinstall/patch-ngcli-webpack.ts
```ts
#!/usr/bin/env ts-node

import * as fs from 'fs-extra'

// tslint:disable-next-line:max-line-length
const configFile = `./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js`
const newConfig = `node:
  {
    fs: 'empty',
    global: true,
    crypto: 'empty',
    tls: 'empty',
    net: 'empty',
    process: true,
    module: false,
    clearImmediate: false,
    setImmediate: false
  }`

fs
  .readFile(configFile)
  .then((b: Buffer) => b.toString())
  .then((contents: string) => contents.replace(/node: false/g, newConfig))
  .then((config: string) => fs.writeFile(configFile, config).catch(console.log))
```

### package.json
```json
  "scripts": {
    "postinstall": "ts-node ./tools/postinstall/patch-ngcli-webpack.ts"
  }
```

I'm not really sure that it's the ***best*** implementation but it has done its job and thus far I have not encountered any negative side-affects

**Comment by eranation** [comment]
@killbox-code thanks for sharing, this works like a charm. (my issue was that I had `fs: true` and `tls: true` I should have read their webpack example)

**Comment by mdivani** [comment]
I have same issue but on React not angular, although I am working with TS :(
