### ISSUE TITLE
Not reciving messages after a while

### ISSUE THREAD

**Issue by matiasdecarli** [aws/aws-iot-device-sdk-js#226]
Hello, I'm experiencing some issue with this library

I have a `node.js` app running on a Raspberry Pi. The connection is done successfully and I can send / receive messages, but after a while (sometimes 20 minutes, sometimes 4 hours), I stop receiving messages.

I'm running this application in several machines and not all of them experience the same issue. Also, when I stop receiving messages, after a restart, the app communicates successfully again (which indicates that it's not a network related issue)

Can you point me on how can I debug this? Thanks in advance

`"aws-iot-device-sdk": "2.2.0"`
`node --version: 8.10.0`

**Comment by fengsongAWS** [comment]
Can you check your cloudwatch log to see what are the reasons that you have been disconnected?

**Comment by fengsongAWS** [comment]
The log should tell you the reason why you disconnected or why is it unable to deliver the messages.

**Comment by fengsongAWS** [comment]
Also, you can do some search or narrow down the timeline when you met the error from cloudwatch. Just to make sure you are in the stream of iot logs e.g. AWSIotLogs

**Comment by matiasdecarli** [comment]
Ok, so... i did this test. I have the app subscribed (and also publishing) messages to certain topics. At the same time, every 1 minute, I made a curl via `request` to a website to check connectivity via `https`

After a while, I stopped receiving messages via the subscribed topic but I was still able to send pings, this means that the one who lost connectivity is `iot`

I'm looking at changing from MQTT overt TLS  using port 8883 to MQTT over websockets using port 443. Do you think this could be a solution for the issue that I'm having?

PS: I can't seem to find anything on the logs, bessides from the messages being published (the ones that I should recibe on the app)

**Comment by matiasdecarli** [comment]
Also, I'm starting to see this error

```
{ Error: read EHOSTUNREACH
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:628:25)
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'read',
  type: 'error',
  target:
   WebSocket {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     readyState: 3,
     bytesReceived: 2206,
     extensions: null,
     protocol: 'mqttv3.1',
     _binaryType: 'arraybuffer',
     _finalize: { [Function: bound finalize] __ultron: 0 },
     _closeFrameReceived: false,
     _closeFrameSent: false,
     _closeMessage: '',
     _closeTimer: null,
     _finalized: true,
     _closeCode: 1006,
     _receiver: null,
     _sender: null,
     _socket: null,
     _ultron: null,
     protocolVersion: 13,
     _isServer: false,
     url: 'wss://[edited].amazonaws.com/mqtt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[edited]&X-Amz-Date=[edited]&X-Amz-SignedHeaders=host&X-Amz-Signature=[edited]',
     _req: null } }
Error: read EHOSTUNREACH
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:628:25)
[debug][closeDeviceConn] going down...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Exit status 1
npm ERR!
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-17T23_10_50_944Z-debug.log
```

**Comment by fengsongAWS** [comment]
This means the host is not able to reach could be potentially your local network routing problem e.g. IP rotation. Can you log into AWS IoT Cloudwatch and select AWSIoTLogs  to see the server side log?

**Comment by matiasdecarli** [comment]
Ok, so my problem is that sometimes I lost connectivity and I don't realize quick enough to force a reconnect. I started to catch the `EHOSTUNREACH ` thanks to the `device.on('error')` event, so now the app doesn't crash. A good starting point

But I'm still failing to realize that some `publish` are not successful. Is there any way to force reconnection after X messages not delivered or set a timeout? I've tryied `keepAlive, connectTimeout, reconnectPeriod`, but none of those seems to fix my problem

Thanks in advance

**Comment by fengsongAWS** [comment]
Do you know the reason of unsuccessful publish? It could either be connection problem or network problem e.g. packet lost. You could enable QoS 1 instead of QoS 0 to guarantee at least 1 packet has been arrived.

**Comment by matiasdecarli** [comment]
I am already using the `qos:1`, yes. 

Regarding the lost connection, I can see locally that after the app starts & connect, if I turn off the wifi, the `iot` doesn't realize that the messages are not being sent. Is there any way to detect this sooner? After I turn off the connection, all the publish messages stop reaching the callback

```
device.publish('<Topic>', JSON.stringify(payload), {
      qos: 1
    }, function (err, resp) {
      // never reach this part
    })
```

**Comment by matiasdecarli** [comment]
Ok finally found the issue & solution for this

The issue that I was having was: the messages not been posted on AWS IoT due to networking issues. Since the messages didn't have a timeout set, I was realizing after a long time that the messages were failing. To solve this, I just set `keepalive: 10`. After 10 seconds if the messages didn't have the `PUBACK`, an error is trigged, and the reconnection is attempted

(I'm also using `qos: 1`)

After doing this, the library works as a charm. Thanks for the help @fengsongAWS
