### ISSUE TITLE
About the feedback

### ISSUE THREAD

**Issue by Oxbowl** [aws/aws-iot-device-sdk-js#232]
Hi, I used the raspberry to create my topic and build my android app.
So far I need to understand that how to receive the feedback from AWS IoT, example as below:

I clicked the ON/OFF button for my light. And the glow after few seconds.
which it means the IoT connected to my Raspberry Pi and proceed with my command.
It is fine for it, but yet what if I want to have two devices. Once the lights on, both devices will receive the notification from the App. I will confuse on how to use the callback function.

**Comment by liuszeng** [comment]
Hi @Oxbowl ,

Can you elaborate more on your use case and the logic flow? Which Node.js SDK API are you working with?

Thanks,
Liusu

**Comment by Oxbowl** [comment]
Hi liuszeng,

Thank you for the fast response. I was using AWS lambda API and IFTTT. So I can trigger my home device with IFTTT through the AWS. However I wanna create the notification for my device with everything it triggered by IFTTT. 
I created a simple android app also, it can trigger my home device also. but yet it cannot notify me for everytime triggering. The main target I want which it is how to receive the response from AWS IoT/Lambda?? when it is triggered so that my phone will give me a notification.

**Comment by liuszeng** [comment]
Hi @Oxbowl ,

The API you need is MQTT subscribe, which allows you to receive publishes/notifications from server with a long live MQTT connection. You may want to take a look at the AWS Android SDK for IoT MQTT:
https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L996
https://github.com/awslabs/aws-sdk-android-samples/blob/master/AndroidPubSub/src/com/amazonaws/demo/androidpubsub/PubSubActivity.java

In case of any issues you have in using the AWS Android SDK APIs, you can open an issue on the repository:
https://github.com/aws/aws-sdk-android/issues

Hope the above helps.

Thank,
Liusu
