### ISSUE TITLE
Getting error 403 after the socket closes and it tries to reconnect

### ISSUE THREAD

**Issue by MichaelPriebe** [aws/aws-iot-device-sdk-js#233]
Seems to be an endless loop until I restart.

**Comment by deftomat** [comment]
@MichaelPriebe The same for us. Did you solve it?

**Comment by MichaelPriebe** [comment]
Not exactly. I just started ending the socket if it errors, and reconnecting after.

**Comment by RavirajKakadeGit** [comment]
Any update on issue, still I'm facing same issue.
Any help will appreciated.

**Comment by jmklix** [comment]
Sorry, but we are no longer considering any feature requests for this sdk as it is being sunsetted. The [V2](https://github.com/aws/aws-iot-device-sdk-js-v2) sdk is accepting feature requests.
