### ISSUE TITLE
Add `enableMetrics` in `DeviceOptions` (Typescript)

### ISSUE THREAD

**Issue by PhilLavoie** [aws/aws-iot-device-sdk-js#237]
Let me know if this should be in the other project :)

Package: `@types/aws-iot-device-sdk`
Version: `2.1.1`
Link: https://www.npmjs.com/package/@types/aws-iot-device-sdk

This interface: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-iot-device-sdk/index.d.ts#L12 seems to be missing the `enableMetrics` field, as documentated here: https://www.npmjs.com/package/aws-iot-device-sdk#awsiotdeviceoptions

**Comment by ColdenCullen** [comment]
Good catch, that is indeed missing. However, as far as I'm aware we do not maintain those bindings, so I think you'd be better served opening an issue or PR against DT.
