### ISSUE TITLE
AMQJS0008I Socket closed.

### ISSUE THREAD

**Issue by sahilkanani** [aws/aws-iot-device-sdk-js#238]
**After following the steps given in the documentation, I am still experiencing the issue of "AMQJS0008I Socket closed."**

I was trying to use IOT Module to create AWS IOT Chat for my serverless application (I followed the steps given in the documentation), but it didn't worked and gave 'Socket Already Closed' error.

I have followed below steps:

1.  I have give "iot:*" rights to my cognito pool.

2. I have created one policy and attached my cognito user identity to that policy.

3. Then i tried connecting it using sdk and it was successfully connected, but then when i tried to publish/subscribe to topic, it thrown the same error.

Is there anything I missed here?

**Comment by jmklix** [comment]
Sorry for the late reply. Have you been able to successfully run the device-example with the policy that you get with the AWS IoT console onboarding?

**Comment by sahilkanani** [comment]
@jmklix Frankly speaking this post is too old to remember for me. But i guess i somehow managed to solved that issue. Hence closing it.
