### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by Buzda** [aws/aws-iot-device-sdk-js#240]
I am creating a HelloWorld example in subscribing/publishing to a topic in the AWSIoT following an online tutorial for creating a Thing, certificate and a policy and used the following script:

***********************************************
var awsIot = require('aws-iot-device-sdk');

var device = awsIot.device({
   keyPath: '13351509b3-private.pem.key',
  certPath: '13351509b3-certificate.pem.crt',
    caPath: 'rootCA.pem',
  clientId: 'Switch',
      host: 'aulc5zc5uh1aj.iot.us-east-2.amazonaws.com',
});

 device.on('connect', function() {
    console.log('connect');
    device.publish('SwitchPolicy', JSON.stringify({ test_data: 1}));
  });

device
  .on('message', function(topic, payload) {
    console.log('message', topic, payload.toString());
  });
***********************************************

I encountered the error (unable to get local issuer certificate).

**Comment by Buzda** [comment]
It turned out that there was a problem with the certificate I downloaded. I used one of the Amazon Trust Services Endpoints (the all don't work). I then used the VeriSign Endpoints (Legacy) and it worked. But I'm still wondering why the ATSs don't work although they are the recommended ones and they live longer.

**Comment by agaskell** [comment]
Heads up for anyone else running into this issue. I was using the correct url (with the -ats) but Certificate Amazon Root CA 2 wasn't working for me with the [device-example](https://github.com/aws/aws-iot-device-sdk-js#device-examplejs) (UNABLE_TO_GET_ISSUER_CERT_LOCALLY). After switching to Amazon Root CA 1 I was able to connect.

I also tried certificates 3 and 4. Those didn't work either.

**Comment by ColdenCullen** [comment]
That is correct, IoT uses RSA 2048 bit, so AmazonRootCA1 is the only one that will work.

**Comment by thisisbrians** [comment]
This solved the issue for me as well. For any exasperated devs arriving here from a Google search: I lifted the cert off of this page: https://good.sca1a.amazontrust.com/
