### ISSUE TITLE
How does one handle expired credentials?

### ISSUE THREAD

**Issue by nirsharony** [aws/aws-iot-device-sdk-js#241]
The accessKeyId, secretKey and sessionToken are sent to AWSIoTData.device and the objecgt is initialized properly. I then successfully send and receive messages.

However, these tokens will expire after a while.
How can the exipration be detected and what can be done to refresh them?

Thanks

**Comment by ColdenCullen** [comment]
Unfortunately cert rotation is outside the scope of this SDK. You'll need to build out some way to deploy new certs as part of you application. If you have any questions on how to implement that, we can probably point you in the right direction.

**Comment by nirsharony** [comment]
Thanks for the reply.

I understand,but if I am to implement my credentials rotation, I need some way of knowing that my current credentials have expired. When they expire, will the error callback get invoked and if so, what error message should I expect to get?

**Comment by ColdenCullen** [comment]
It looks like there is an error, and I think it's emitted [here](https://github.com/aws/aws-iot-device-sdk-js/blob/master/device/lib/tls.js#L35). Unfortunately if that is where it is raised, then clearly it's not very specific. Although, I think if you are having your connections consistently succeed and then all of a sudden start failing, then it's probably time for new certs 😃

If this isn't specific enough, it looks like it should be pretty easy to query `connection.authorizationError`. Let me know how you'd like to proceed.

**Comment by nirsharony** [comment]
Thanks for this info.

I just tested something else: 
Connected to a topic and then delibaretely turned off my Internet connectivity.
This is the order of the events that got emited: 

1) **offline** event was emited
2) **close** event was emitted
3) **reconnect** event was emitted
4) **error** event was emitted. The error was:  {"isTrusted":true} 

I was expecting the error to say something about a network problem.
How else would I know the cause of the error?

**Comment by ColdenCullen** [comment]
That is definitely a strange order of events, but I would think 1-3 would let you know the cause of the error 😃

**Comment by paparent** [comment]
Hi ! 

I'm wondering how to implement this too. MQTT.js supports it (I think) via : https://github.com/mqttjs/MQTT.js/blob/master/README.md#signed-websocket-urls

Might be a nice idea ? Otherwise how can I disable the auto-reconnect stuff so I can handle it by myself ?

**Comment by maciejdzikowicki** [comment]
When you receive your AWS temporary credentials, you also get `expiration` timestamp. Few minutes before that you can refresh credentials (this needs your own implementations) and use  `updateWebSocketCredentials` method.
