### ISSUE TITLE
Does not work with Typescript and Angular 6

### ISSUE THREAD

**Issue by tadas-subonis** [aws/aws-iot-device-sdk-js#248]
```
  private clientObservable: Subject<Client> = new Subject();
  private messageObservable: Subject<Message> = new Subject();
....

    const endpoint = '';
    const clientId = guid();
    const region = '';

    AWS.config.update({
      region: region
    });

    const credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: ''
    }, {
      region: region,
      httpOptions: {
        connectTimeout: 5,
      }
    });

    Observable.create((observer: Observer<Client>) => {

      const cognitoIdentity = new AWS.CognitoIdentity();
      credentials.get((err) => {
        if (err) {
          observer.error(err);
          console.error('error retrieving identity:', err);
          return;
        }

        console.log('retrieved identity: ' + credentials.identityId);
        var params = {
          IdentityId: credentials.identityId
        };
        cognitoIdentity.getCredentialsForIdentity(params, function (err, data) {
          if (err) {
            console.log('error retrieving credentials: ' + err);
            observer.error(err);
            return;
          }

          console.log("Received credentials", data.Credentials);

          const mqttClient: Client = awsIot.device({
            region: region,
            protocol: 'wss',
            clientId: clientId,
            host: endpoint,
            accessKeyId: data.Credentials.AccessKeyId,
            secretKey: data.Credentials.SecretKey,
            sessionToken: data.Credentials.SessionToken
          });
          mqttClient.on('error', error1 => {
            console.warn("Error in MQTT", error1);
          });


          // @ts-ignorec
          mqttClient.updateWebSocketCredentials(data.Credentials.AccessKeyId,
            data.Credentials.SecretKey,
            data.Credentials.SessionToken
          );

          console.log("MQTT Client ready", mqttClient);

          observer.next(mqttClient);
          observer.complete();
        });
      });

    })
      .subscribe(this.clientObservable);

    const messageObservable: Observable<Message> = this.clientObservable
      .pipe(
        flatMap(client => {
          return <Observable<Message>>Observable.create((observer: Observer<Message>) => {
            const handler = (topic, payload) => {
              const payloadJ = JSON.parse(payload.toString());

              observer.next(new Message(
                topic,
                payloadJ.type,
                payloadJ,
              ))

            };

            client.on('message', handler);
          });
        }),
      );

    messageObservable.subscribe(this.messageObservable);
```

The code above doesn't give me a working MQTT client - I've tried sending and getting messages back (there are no messages on the dashboard as well).

I've had to apply this had as well: https://github.com/aws/aws-iot-device-sdk-js/issues/223#issuecomment-397669600

The regular instructions for webpack do not work on typescript-integrated webpack, because after bunlding, you get errors like here https://github.com/aws/aws-iot-device-sdk-js/issues/115

**Comment by tadas-subonis** [comment]
Alright, apparently it was a policy configuration issue. After some time (not immediately), the system started reporting 403 errors that hinted me towards that direction (kinda like here https://github.com/aws-samples/aws-iot-examples/issues/1 )

**Comment by kahnchen1028** [comment]
Excuse me, do have fixed this problem? or finding the other way to replace that? 
I am Integrating about aws iot device sdk to Angular 7, and I face some problem..orz
first problem is I need use" mqttClient = new awsIot.device(deviceOption)"
second problem is I got error on chrome console...
The error as this...
===================================================================
ERROR TypeError: process.nextTick is not a function
    at Duplexify.push../node_modules/duplexify/index.js.Duplexify.destroy (index.js:181)
    at WebSocket.onclose [as __zone_symbol__ON_PROPERTYclose] (stream.js:139)
    at WebSocket.wrapFn (zone.js:1332)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17290)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:498)
    at invokeTask (zone.js:1744)
    at WebSocket.globalZoneAwareCallback (zone.js:1770)
====================================================================
If you have any suggestion, please tell me QQ.. thanks
