### ISSUE TITLE
How to explicitly disconnect from AWSIoTData.device?

### ISSUE THREAD

**Issue by nirsharony** [aws/aws-iot-device-sdk-js#249]
Hi.

I am basing my work on this code:
https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/browser/mqtt-explorer/index.js

I am successfully connecting and getting the following callbacks invoked: 
- connect
- reconnect
- message
- error
- offline
- close

However, in some scenarios, I need to completely disconnect from the topic.
What i do is use: mqttClient.unsubscribe
Note that even after I disconnect, I sometimes still get the **connect** callback invoked. I don't want to connect automatically after unsubscribing from the topic.
Is there to force such disconnection?

Thanks

**Comment by graebm** [comment]
There is an `end(force, callback)`function on the mqttClient. `force` is whether to close immediately, or wait for in-flight messages to be sent. `callback` will be called when the connection finishes closing.
