### ISSUE TITLE
Error in installing aws-iot-device-sdk.js on ubuntu

### ISSUE THREAD

**Issue by Hussnain1** [aws/aws-iot-device-sdk-js#25]
I am trying to install sdk using nom command but to no success.
Please look into it and guide me further.\

![main](https://cloud.githubusercontent.com/assets/8127852/11769171/d29b4084-a202-11e5-831e-d22c8eca3b38.png)

**Comment by gkwicker** [comment]
It looks like this is a known issue in Debian.  [This post on stackoverflow](http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu) covers what appears to be the same issue and recommends a fix (sudo apt-get install nodejs-legacy).  Let us know if that fixes the problem.

**Comment by gkwicker** [comment]
Hi,

We haven't heard back from you on this issue, so we're going to go ahead and close it.  Feel free to re-open it if you have further questions on this topic.
