### ISSUE TITLE
MQTT Version 5 Support

### ISSUE THREAD

**Issue by deen13** [aws/aws-iot-device-sdk-js#250]
Hello AWS Contributors, 

first i have to thank you for the great work. I just have read about the features in the new MQTT Version 5. Is there anything on the roadmap related to upgrade the AWS IoT Broker Version? 💯

**Comment by kanumuru** [comment]
Hi Team,
Any updates on this thread? We are looking forward to implementing MQTT 5.1 in our project. Some timeline or plan details would be appreciated.

**Comment by bretambrose** [comment]
SDK features are driven by the requirements of the service team, so I've opened a question with them regarding MQTT 5+ support.  That being said, this (version 1) SDK has been moved to maintenance mode and all future development (beyond critical security fixes) will likely be restricted to the v2 SDKs (https://github.com/aws/aws-iot-device-sdk-js-v2 for example)

**Comment by bretambrose** [comment]
Here's the response I received from the IoT service team:

"We are currently evaluating MQTT 5 but we do not have a definitive timeline for support.  Are there particular features of MQTT 5 that you are interested in?"

I can relay answers to the features question directly to the team.

**Comment by kanumuru** [comment]
Since AWS IOT supports MQTT 3.1 with QoS 0 and QoS 1.
We want to implement MQTT QoS 2 in our project.
Will, there be any upgrade of Message Broker?
Any information related to this is helpful and appreciated!
Thank you in advance.

**Comment by jmklix** [comment]
As stated above there is now a [v2 sdk](https://github.com/aws/aws-iot-device-sdk-js-v2) and any feature requests should be directed to that sdk.
