### ISSUE TITLE
Support for non-ssl (ws://)

### ISSUE THREAD

**Issue by lagnat** [aws/aws-iot-device-sdk-js#252]
In our development environment with serverless-offline, IoT connections are being rejected by the browser for invalid certificate authority.  This makes sense as we're using self-signed certs and there doesn't appear to be any way to disable checks for self-signed certs when running on a browser and native WebSocket.  Side note.. I've seen `rejectUnauthorized: false` and I'm fairly sure it used to work but I can no longer make it work in a browser.

Is there something I'm missing here?

I've since made several small code changes to aws-iot-device-sdk-js to support ws:// URLs, though I can't say for sure it covers all of the use-cases.  Would that be a welcome PR?

**Comment by ColdenCullen** [comment]
Hey @lagnat,

Thanks for your interest! Since we only support connecting to the AWS IoT endpoints (which REQUIRE SSL), I don't really think this is something we want to support or encourage.

Cheers!
Colden
