### ISSUE TITLE
Websocket connection failed

### ISSUE THREAD

**Issue by rossrossp** [aws/aws-iot-device-sdk-js#259]
Hello team,

The below setup of IoT for handling chat alerts had been working perfectly for me for a while now, but has recently stopped working, although nothing has changed.
I am using the SDK on the client side, and connecting to my AWS IoT endpoint via the wss protocol, using Cognito as the identity provider.

First, I fetch the credentials:
```
    AWS.config.region = Globals.region;
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId: Globals.iotIdentityPoolId,
        IdentityId: Globals.iotIdentityId
    });

    AWS.config.credentials.get(function(err) {
        if(err) return console.log(err);
        IoT.connect('XXXXXX',
            Globals.iotEndpoint, 
            AWS.config.region,
            AWS.config.credentials.accessKeyId,
            AWS.config.credentials.secretAccessKey,
            AWS.config.credentials.sessionToken);
    });
```

Then I attempt to connect:
```
        var params = {
          region: region,
          protocol: 'wss',
          port: 443,
          host: iotEndpoint,
          accessKeyId: accessKeyId,
          secretKey: secretAccessKey,
          sessionToken: sessionToken
        };
        client = awsIot.device(params);
```

The error is not so clear, but here's what I've got:
WebSocket connection to 'wss://XXXXXXXXX.iot.eu-west-1.amazonaws.com/mqtt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXX%2Feu-west-1%2Fiotdevicegateway%2Faws4_request&X-Amz-Date=20190224T185745Z&X-Amz-SignedHeaders=host&X-Amz-Signature=XXXX&X-Amz-Security-Token=XXXXX' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID

error { target: WebSocket, isTrusted: true, srcElement: WebSocket, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, composed: false, timeStamp: 4246, cancelBubble: false, … } 

Does anybody know why this could have suddenly stopped working? I've updated the SDK and dependencies, but still see the same errors.

Thanks,
Ross.

**Comment by rossrossp** [comment]
I have just read that we need to switch to the ats endpoint. I have done this and it now seems to be working! I will test a bit and then close the issue.

**Comment by eercanayar** [comment]
Check #268
