### ISSUE TITLE
AWS Device in browser does not connect at all

### ISSUE THREAD

**Issue by castellanprime** [aws/aws-iot-device-sdk-js#265]
Hi, 
 
I am reading the docs and trying to setup iot for a friend but to no avail. I am using cognito for authentication. This is the setup on the IAM side.

```javascript
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "iot:Receive",
            "Resource": "arn:aws:iot:XXXX:XXXXX:topic/${cognito-identity.amazonaws.com:sub}"
        },
        {
            "Effect": "Allow",
            "Action": "iot:Connect",
            "Resource": "arn:aws:iot:::client/${cognito-identity.amazonaws.com:sub}"
        },
        {
            "Effect": "Allow",
            "Action": "iot:Subscribe",
            "Resource": "arn:aws:iot:XXXXXX:XXXXXXX:topicfilter/${cognito-identity.amazonaws.com:sub}/"
        },
        {
            "Effect": "Allow",
            "Action": "iot:DescribeEndpoint",
            "Resource": "*"
        }
    ]
}
```

I also attach the same policy as above to the user using a lambda(server side) on login using the attachPolicy in the AWS IOT SDK. The endpoint address is hardcoded after getting it from the iot core console.. The client configuration in the browser is this:

```javascript
this.client = AWSIot.device({
  accessKeyId: XXXXX,
  secretKey: XXXXXX,
  sessionToken: XXXXXX,
  clientId: `a cognito Id ` + some number
  host: XXXXXXX.iot.amazonaws.com,
  region: XXXXXX,
  protocol: 'wss',
  debug: true,
  port: 443,
  clean: false
});
```

The client detects it is offline and tries to reconnect. This pattern is repeated until after 128 seconds, i get the error message below: 

`WebSocket connection to 'wss://endpoint/mqtt?X-Amz-Algorithm=000&X-Amz-Credential=0000&X-Amz-Date=0000&X-Amz-SignedHeaders=host&X-Amz-Signature=0000&X-Amz-Security-Token=0000 failed: Error during WebSocket handshake: Unexpected response code: 403`

What can I change so that I can actually connect to the Aws Iot Broker? Thanks.

**Comment by graebm** [comment]
Thanks for sharing so much data up front

It appears that the clientId coming from code does not match the pattern in the IAM policy. Your policy allows:
```
"Effect": "Allow",
"Action": "iot:Connect",
"Resource": "arn:aws:iot:::client/${cognito-identity.amazonaws.com:sub}"
```

But your code is setting: `clientId: "a cognito Id " + some number`

To get these things aligning, either put a wildcard at the end of the policy resource path like so:
```
"Resource": "arn:aws:iot:::client/${cognito-identity.amazonaws.com:sub}*"
```
or remove the `+ some number` from the clientId used to connect

**Comment by castellanprime** [comment]
@graebm  Thanks for your help. Apart from your solution, I also made a mistake in the policy for connect:

```
"Effect": "Allow",
"Action": "iot:Connect",
"Resource": "arn:aws:iot:XXXXXX:XXXXXXX:client/${cognito-identity.amazonaws.com:sub}"
```
After I added your solution and the above correction, I was able to connect.

**Comment by graebm** [comment]
🎉
