### ISSUE TITLE
[Error] 'wss://no-credentials-available/' problem

### ISSUE THREAD

**Issue by DongwonLee87** [aws/aws-iot-device-sdk-js#266]
I tried to test got some error code as follows.
How can I fix the problem ?
Can I know what is releated with ?

[source code]
    if (typeof target === 'object') {
      socket = target
    // otherwise make a new one
    } else {
      // special constructor treatment for native websockets in browsers, see
      // https://github.com/maxogden/websocket-stream/issues/82
      logToHTML('New WebSocket, with arguments:', target, protocols, options);
      if (isNative && isBrowser) {
        socket = new WS(target, protocols) // At this point, the error happen
      } else {
        socket = new WS(target, protocols, options)
      }

[error console]
connection to 'wss://no-credentials-available/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

**Comment by bretambrose** [comment]
How are you importing credentials?

https://github.com/aws/aws-iot-device-sdk-js#websocket-configuration
