### ISSUE TITLE
Certificate X.509

### ISSUE THREAD

**Issue by srirammoorthyziffity** [aws/aws-iot-device-sdk-js#27]
Do I have to call AWS command to create cert.pem?

aws iot --endpoint-url https://i.us-east-1.pb.iot.amazonaws.com describe-certificate --certificate-id --output text --query certificateDescription.certificatePem > cert.pem

or is there any OpenSSL command available? My use case is to create cert.pem without relying on AWS.  Because i created initial certificates with OpenSSL commands,

$ openssl genrsa -out privateKey.pem 2048
$ openssl req -new -key privateKey.pem -out cert.csr

I would like to understand what the above aws command does.

**Comment by johnrotach** [comment]
Hello,

The describe-certificate API does not create a certificate but rather describes a client certificate which has already been signed by AWS IoT and is available for use.  When creating certificates for use with AWS IoT you have two choices:

First, you can generate your private and public keys locally (using OpenSSL) and then create a CSR containing your public key.  This CSR is then submitted to AWS IoT and signed and you are returned a client certificate which can be used in conjunction with your private key to access the service.

Second, you can choose to have the service generate the keys and return the public key, private key and client certificate using the create-keys-and-certificate API call.

After completing either option above you can see your newly created certificate by listing your certificates.  Describing this certificate will merely return the certificate already returned when in one of the steps above.

The act of signing the client certificate has to be done by the service and cannot be done locally with OpenSSL.  Doing this locally would create what is called a self-signed certificate.

I hope this helps clear this up.

John
AWS IoT

**Comment by johnrotach** [comment]
Apologies - I accidentally commented and closed rather than just commenting.  Feel free to comment further or close if your question was answered.

**Comment by srirammoorthyziffity** [comment]
@johnrotach Thanks John :+1: . Now i am clear and understood the process.
