### ISSUE TITLE
browserize exit status 1 code ELIFECYCLE errno 1

### ISSUE THREAD

**Issue by borch84** [aws/aws-iot-device-sdk-js#271]
Hi, I am running the Temperature Monitor Browser Example Application from here: https://github.com/aws/aws-iot-device-sdk-js#temperature-monitor-browser-example-application

Step 4 is giving me this error:
```
borch@g4560:~/Documents/JavaScript-Apps/aws-iot-device-sdk-js$ npm run-script browserize examples/browser/temperature-monitor/index.js

> aws-iot-device-sdk@2.2.1 browserize /home/borch/Documents/JavaScript-Apps/aws-iot-device-sdk-js
> ./scripts/browserize.sh "examples/browser/temperature-monitor/index.js"

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-iot-device-sdk@2.2.1 browserize: `./scripts/browserize.sh "examples/browser/temperature-monitor/index.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aws-iot-device-sdk@2.2.1 browserize script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/borch/.npm/_logs/2019-05-03T04_58_40_648Z-debug.log
```

The output of debug.log is attached here:

[2019-05-03T04_58_40_648Z-debug.log](https://github.com/aws/aws-iot-device-sdk-js/files/3140698/2019-05-03T04_58_40_648Z-debug.log)

I am using SDK version: v2.2.1-3-g4814456
node -v v10.15.3
npm -v 6.9.0

Already executed npm install in the root folder of aws-iot-device-sdk-js

Appreciate any help here, cheers.

**Comment by graebm** [comment]
I tried to reproduce this but couldn't.

I tried by pulling the latest from Github and doing `npm install` from the project directory and running the browserize script. I also tried by pulling the latest `aws-iot-device-sdk` from npm, cd'ing into the `node_modules/aws-iot-device-sdk` dir and running the browserize script from there. It succeeded both ways

The versions on my machine are:
aws-iot-device-sdk: v2.2.1
npm: 6.9.0
node: v11.9.0
OS: Mac 10.13.6

What did you mean when you said your aws-iot-device-sdk was "v2.2.1-3-g4814456"?
Where did the "-3-g4814456" part come from?

**Comment by borch84** [comment]
Hi @graebm, thanks for replaying back. I just git cloned aws-iot-device-sdk into a new directory. 
```
$ git clone https://github.com/aws/aws-iot-device-sdk-js.git
$ cd aws-iot-device-sdk-js
$ npm install
$ npm run-script browserize examples/browser/temperature-monitor/index.js

> aws-iot-device-sdk@2.2.1 browserize /home/borch/Documents/JavaScript-Apps/another-aws-iot-device-sdk/aws-iot-device-sdk-js
> ./scripts/browserize.sh "examples/browser/temperature-monitor/index.js"

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-iot-device-sdk@2.2.1 browserize: `./scripts/browserize.sh "examples/browser/temperature-monitor/index.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aws-iot-device-sdk@2.2.1 browserize script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/borch/.npm/_logs/2019-05-04T02_56_27_816Z-debug.log

```
v2.2.1-3-g4814456 comes from the git describe command. Also added the output of git rev-parse HEAD to confirm and I am using the latest commit version:

```
$ git describe
v2.2.1-3-g4814456
$ git rev-parse HEAD
481445639ff6bb92586c63d3c9ee85dd37728453
```
I am using latest LTS version of node, however you are using node version 11.9 though.

Using Linux.

```
$ node -v
v10.15.3
$ npm -v
6.9.0
$ uname -a
Linux g4560 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
$ 
```
