### ISSUE TITLE
Premature closed issue

### ISSUE THREAD

**Issue by imayur7** [aws/aws-iot-device-sdk-js#272]
Hello, using Aws-iot-device-sdk package I got this error :

Error: premature close
    at TLSSocket.onclose (/home/pi/Server/node_modules/end-of-stream/index.js:47:67)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at _handle.close (net.js:561:12)
    at TCP.done [as _onclose] (_tls_wrap.js:360:7)

This was happening when the Internet connection is closed while the running server, 
Please help me I'm stuck here because however, I need to also manage when an application in offline mode.

Device: Raspberry pi
Node: v8.16.0
NPM : 6.4.1

**Comment by JonathanHenson** [comment]
I'm a bit confused by the question. This is the correct behaviour when you lose a connection.

Are you asking how to handle offline queuing?

**Comment by imayur7** [comment]
Hello, @JonathanHenson Sorry for confusion actually I need to handle this error because whenever my device gets in offline mode, I get This error after some time. And for Offline Queue I already set it to false.
 I'm sharing my DEBUB logs may be it will help. I also Included socket.io in my code.
also, you said this is correct behavior then could you please guide me to resolve this issue?
[logs.txt](https://github.com/aws/aws-iot-device-sdk-js/files/3176040/logs.txt)

**Comment by imayur7** [comment]
Thank you for the reply. issue solved after using mqtt.Client#end when Server goes offline.

**Comment by mkl96** [comment]
can you please answer in detail, I'm facing this error in ec2 instance

> Thank you for the reply. issue solved after using mqtt.Client#end when Server goes offline.

**Comment by ionSurf** [comment]
Also, check for the clientID that you're using for both connecting as the ShadowThing and the ShadowMonitor, THEY CANNOT BE THE SAME. This will result in connection drops on both sides.

**Comment by SuneethaYamani** [comment]
> Also, check for the clientID that you're using for both connecting as the ShadowThing and the ShadowMonitor, THEY CANNOT BE THE SAME. This will result in connection drops on both sides.

for shadow monitor which clientid we should use?

**Comment by bretambrose** [comment]
Clientid is an arbitrary string.  You can use whatever you'd like.  That being said, your permission policies may be scoped all the way down to specific clientid values, and if that's the case for you, they'll need to match.
