### ISSUE TITLE
How to handle error when calling awsIot.thingShadow#register()

### ISSUE THREAD

**Issue by michaelwittig** [aws/aws-iot-device-sdk-js#274]
Hi,

I wonder how I have to handle an error during `awsIot.thingShadow#register()`.

```
const thingShadow = awsIot.thingShadow({
  keyPath: '...',
  certPath: '...',
  caPath: '...',
  clientId: 'clientid',
  host: 'host'
});
thingShadow.register('thingname', {}, function(err) {
  if (err) {
    // what should I do?
  } else {
    // ok, great
  }
});
```

It looks like, calling register again is not a good idea (no callback ever called https://github.com/aws/aws-iot-device-sdk-js/blob/master/thing/index.js#L616)

As far as I understand, even if I get an error during `register()`, the subscriptions will be made as soon as the connection is alive? 

The documentation mentions "Applications should wait until shadow registration is complete before performing update/get/delete operations.".  How can I know that the registration is complete if I get an error?

**Comment by ShunKeJiang** [comment]
@michaelwittig It seems like you can use get to detect if the opClientToken is null

**Comment by jmklix** [comment]
@michaelwittig where you able to find a way to handle the error? If so was it by checking if opClientToken is null?
