### ISSUE TITLE
React Native Integration

### ISSUE THREAD

**Issue by vishalavalani** [aws/aws-iot-device-sdk-js#277]
I tried all possible ways of integrating it with React Native especially https://github.com/aws/aws-iot-device-sdk-js/issues/86. None of them are working properly.

- https://github.com/aws/aws-iot-device-sdk-js/issues/86#issuecomment-371159865 - **Error**: https://i.stack.imgur.com/LcBOc.png

- https://aws-amplify.github.io/docs/js/pubsub - **Error**: AMQJS0007E Socket error:undefined

Need help in integration or guide best way forward.

**Comment by JonathanHenson** [comment]
This looks like an issue for amplify-js, I've filed and issue and referenced this one.

**Comment by desarrollomovil480** [comment]
Hi!
Do we have any news on this issue? We're facing the same problem when trying to integrate the library into a ReactNative project.
