### ISSUE TITLE
"Error: This socket has been ended by the other party" (EPIPE)

### ISSUE THREAD

**Issue by Craigson** [aws/aws-iot-device-sdk-js#278]
Hello!

I've been using IoT Core to handle pub/sub messaging between my fleet of Raspberry Pi devices.  They're all running NodeJS v10.x inside of a docker container, managed using the Balena Cloud framework.  I'm experiencing issues that I can't seem to debug, see the following stack trace:

{code}
30.07.19 12:29:39 (-0400)  server  ERROR { Error: This socket has been ended by the other party
30.07.19 12:29:39 (-0400)  server      at TLSSocket.writeAfterFIN [as write] (net.js:395:12)
30.07.19 12:29:39 (-0400)  server      at emptyPacket (/app/node_modules/mqtt-packet/writeToStream.js:477:17)
30.07.19 12:29:39 (-0400)  server      at Object.generate [as writeToStream] (/app/node_modules/mqtt-packet/writeToStream.js:49:14)
30.07.19 12:29:39 (-0400)  server      at sendPacket (/app/node_modules/mqtt/lib/client.js:37:27)
30.07.19 12:29:39 (-0400)  server      at MqttClient._sendPacket (/app/node_modules/mqtt/lib/client.js:776:5)
30.07.19 12:29:39 (-0400)  server      at MqttClient._checkPing (/app/node_modules/mqtt/lib/client.js:832:10)
30.07.19 12:29:39 (-0400)  server      at Timeout.<anonymous> (/app/node_modules/mqtt/lib/client.js:809:12)
30.07.19 12:29:39 (-0400)  server      at ontimeout (timers.js:438:13)
30.07.19 12:29:39 (-0400)  server      at tryOnTimeout (timers.js:300:5)
30.07.19 12:29:39 (-0400)  server      at listOnTimeout (timers.js:263:5) code: 'EPIPE' }
{code}

This error happens frequently / sporadically and is preventing me from using my devices for the purposes for which they're intended.

I currently only have 2 devices setup and for the most part they're sitting idle, so it's impossible that I'm exceeding any sort of service limits.

How can I prevent and/or handle this error to ensure the connection remains stable?

Thanks

**Comment by justinboswell** [comment]
When the service forcibly hangs up on a client abruptly, the usual suspects are:
1) Error in last message sent
2) Service limit violation
3) Keepalive timeout

What was the last message sent to the service before the hangup? The above log is after the possible offending message. The service does not always send back a helpful error response before hanging up, but we might be able to guess what went wrong if we know what was sent to the service last.

**Comment by 792x** [comment]
This seems to happen for us when someone with the same client ID connects, then it takes some time (no more than 5 minutes) for AWS to end the old connection. This isn't a problem in itself but it crashes the entire process, how are we supposed to catch this error?

**Comment by graebm** [comment]
Yes, when a 2nd device connects with the same ClientID, the 1st device will get kicked off. This behavior defined in the MQTT spec.

You can catch connection errors, and prevent them from [crashing the program](https://nodejs.org/api/events.html#events_error_events), by registering a handler for the `error` event. Ex:
```
device.on('error', function(error) {
    console.log('error', error);
});
```

That code snippet is from the [examples/device-example.js](https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/device-example.js) sample that ships with the SDK. I tested by running that sample on 2 terminals at the same time, each using the same ClientID. They took turns connecting and kicking the other one off. They never crashed, the logs just showed an infinite loop of:
```
...
connect
offline
error { Error: This socket has been ended by the other party ... }
close
reconnect
connect
offline
error { Error: This socket has been ended by the other party ... }
close
reconnect
connect
...
```
