### ISSUE TITLE
MQTT QoS level upgrade?

### ISSUE THREAD

**Issue by heidilind** [aws/aws-iot-device-sdk-js#279]
We're using the job update functions failed and succeeded and noticed few times a job hasn't been updated in iot but stayed in a progress state. That happens very rarely though. From the source code we found out that the qos parameter is not set:

In /jobs/index ln 108:
```
device.publish(buildJobTopic(thingName, job.id, 'update'), 
    JSON.stringify({ status: status, statusDetails: statusDetails}), null, function(err){})
```
options being 'null' instead for example {qos:1}, which would verify that iot receives the message at least once. Is there any plans in future to maybe set it to 1?

**Comment by graebm** [comment]
This SDK is in maintenance mode while we develop a [V2 SDK])https://github.com/awslabs/aws-iot-device-sdk-js-v2). In the V2 SDK, users can specify the desired QoS.
