### ISSUE TITLE
Connection lost every 2-3 Minutes by some users

### ISSUE THREAD

**Issue by klotzma** [aws/aws-iot-device-sdk-js#280]
Hello,

I want to reminisce with this Issue again to the now long time existing problem, hoping to find help, because I can use the Iot service very limited.

I have to partially re-order my google home several times to run it, whether via IFTTT or the direct connection to GHome, I quote "The service Iobroker is currently unavailable".

`2019-08-11 22:16:54.958 - �[31merror�[39m: iot.0 Error by device connection: "read ECONNRESET" 
2019-08-11 22:16:54.958 - �[32minfo�[39m: iot.0 Connection changed: disconnect 
2019-08-11 22:16:54.958 - �[32minfo�[39m: iot.0 Connection lost 
2019-08-11 22:17:00.268 - �[32minfo�[39m: iot.0 Connection changed: connect 
2019-08-11 22:22:00.541 - �[31merror�[39m: iot.0 Error by device connection: "read ECONNRESET"
`

Same problem as in this closed issue:
[Aws Iot Issue #251](https://github.com/aws/aws-iot-device-sdk-js/issues/251)

**Comment by bretambrose** [comment]
At this point, assuming you've checked all of the suggestions in the referenced thread, I think the best chance for progress is to provide a wire shark log from the initial connection to the first disconnect.

**Comment by klotzma** [comment]
I'll let the Wireshark run and post the protocol here

**Comment by klotzma** [comment]
Can someone help me with how I record this with Wireshark?

**Comment by justinboswell** [comment]
Just open wireshark, and capture with a filter of ```host <your endpoint>-ats.iot.<region>.amazonaws.com```, then run your program. That'll capture only packets going to your IoT endpoint, which is what you want.

**Comment by klotzma** [comment]
What do you mean with "My Endpoint" ? Where can i find it?

**Comment by justinboswell** [comment]
The endpoint you were assigned for your Thing in the AWS Console. It should look something like ```a16523t7iy5uyg-ats.iot.us-east-1.amazonaws.com```.

**Comment by klotzma** [comment]
I recorded the traffic, but it has to be filtered.
My Cloud IP = a18wym7vjdl22g.iot.eu-west-1.amazonaws.com
Towards the end of the connection abort should be seen.
Here is the zip:
[protocol.zip](https://github.com/aws/aws-iot-device-sdk-js/files/3580899/protocol.zip)

![iot](https://user-images.githubusercontent.com/45261052/64374672-9fce2c80-d024-11e9-9fee-8163de0fb76a.jpg)

![iot2](https://user-images.githubusercontent.com/45261052/64374695-a8befe00-d024-11e9-927a-a5cfa839024f.jpg)

**Comment by justinboswell** [comment]
That looks like a normal 5 minute timeout hangup from the service, because no packets were sent from the client to the service. If you look at the timestamps, it's exactly 300 seconds.

**Comment by klotzma** [comment]
But where do the problems come from?  Others do not and the service works.  I always get errors.

**Comment by klotzma** [comment]
Are you talking about the pictures now?  or did you look at the log?  Because there is not much to see in the pictures

**Comment by klotzma** [comment]
I do not believe the pictures say anything.  I just did it to show that it recorded.  Because I do not understand anything that is in the record

**Comment by klotzma** [comment]
Here I once again recorded the Trafic, this time longer.  Again, unfiltered, must be filtered out.  I can not do that.
[vm100neu2.pcap.zip](https://github.com/aws/aws-iot-device-sdk-js/files/3583356/vm100neu2.pcap.zip)

**Comment by justinboswell** [comment]
I filtered the log you posted down (```tcp.port == 8883``` works). Have you tried setting ```keepalive``` in the options structure you pass to the ```Device``` constructor to something like 60 seconds? Do you have logs from the session? Set ```debug = true``` on the options passed to the ```Device``` constructor, and you should get some logs.

**Comment by klotzma** [comment]
I detected it via TCPDUMP because I have this system running in a virtual machine under Proxmox.
Can I also set something under tcpdump?

**Comment by justinboswell** [comment]
No, because all of the packets are encrypted with TLS, so we can only guess at their contents by size. Furthermore, we want to see how the SDK is reacting to incoming/outgoing messages.

**Comment by klotzma** [comment]
And wireshark decodes this when capturing it?

**Comment by klotzma** [comment]
The iot service runs on my server under a VM and the server is connected via LAN to my router.  Wireshark I have on a Windows laptop, how can I record the traffic now in the LAN?

**Comment by klotzma** [comment]
I have used the "capturing" feature of my router and here is the protocol:
[!!iad-if-lan_06.09.19_2127.zip](https://github.com/aws/aws-iot-device-sdk-js/files/3585542/iad-if-lan_06.09.19_2127.zip)
Can you find more here?

**Comment by justinboswell** [comment]
None of what we're asking for is wireshark related. I need the logs from your application, so I can see what the SDK thinks is happening.

**Comment by klotzma** [comment]
I ran the loglevel on silly and debug and uploaded it here.
[log.zip](https://github.com/aws/aws-iot-device-sdk-js/files/3585764/log.zip)
[iobroker.2019-09-06debug.zip](https://github.com/aws/aws-iot-device-sdk-js/files/3585823/iobroker.2019-09-06debug.zip)
Or do you mean something else?
If so, can you help me with what you need, I am not a professional?

**Comment by klotzma** [comment]
I have now let my router capture the traffic and set the log of the application to debug in parallel.
- 1:56 pm start log debug and start capture
- 2:06 pm log debug and capture ended
Have all this packaged in this ZIP:
[log(Debug)+capture.zip](https://github.com/aws/aws-iot-device-sdk-js/files/3586600/log.Debug.%2Bcapture.zip)
         
I would have liked to record longer, but you can only upload files here with 10 mb

**Comment by graebm** [comment]
The wireshark logs from the router are not very helpful, since the data is all encrypted. You do not need to keep including those.

Have you tried setting a shorteer `keepalive` value? Like:

```
var awsIot = require('aws-iot-device-sdk');

var device = awsIot.device({
     debug: true,
   keepalive: 60,
   keyPath: <YourPrivateKeyPath>,
  certPath: <YourCertificatePath>,
    caPath: <YourRootCACertificatePath>,
  clientId: <YourUniqueClientIdentifier>,
      host: <YourCustomEndpoint>,
       ...
});

**Comment by klotzma** [comment]
OK sorry.

Where do I have to change that "keepalive" ?
In the application where the iot service is running?

**Comment by klotzma** [comment]
> The wireshark logs from the router are not very helpful, since the data is all encrypted. You do not need to keep including those.
> 

If you can tell me how to record it unencrypted, I would make it new.
Unfortunately, I am only a user and not a developer.

**Comment by GermanBluefox** [comment]
> OK sorry.
> 
> Where do I have to change that "keepalive" ?
> In the application where the iot service is running?

This is a place that could be edited:
https://github.com/ioBroker/ioBroker.iot/blob/master/main.js#L767

```
device = new DeviceModule({
                privateKey: new Buffer(certs.private),
                clientCert: new Buffer(certs.certificate),
                caCert:     fs.readFileSync(__dirname + '/keys/root-CA.crt'),
                clientId,
                username:   'ioBroker',
                host:       adapter.config.cloudUrl,
                debug:      !!adapter.config.debug,
                baseReconnectTimeMs: 5000,
                keepalive: 60, // ADD THIS LINE
            });
````

the file could be found in /opt/iobroker/node_modules/iobroker.iot/main.js

**Comment by Apollon77** [comment]
Would be interesting if it helps

**Comment by klotzma** [comment]
`2019-09-10 17:51:07.137  - [31merror[39m: Caught by controller[0]: /opt/iobroker/node_modules/iobroker.iot/main.js:777
2019-09-10 17:51:07.138  - [31merror[39m: Caught by controller[0]: 		keepalive: 60,
2019-09-10 17:51:07.138  - [31merror[39m: Caught by controller[0]: 		^^^^^^^^^
2019-09-10 17:51:07.138  - [31merror[39m: Caught by controller[0]: SyntaxError: Unexpected identifier
2019-09-10 17:51:07.138  - [31merror[39m: Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:723:23)
2019-09-10 17:51:07.138  - [31merror[39m: Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-09-10 17:51:07.138  - [31merror[39m: Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:653:32)
2019-09-10 17:51:07.138  - [31merror[39m: Caught by controller[0]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-09-10 17:51:07.138  - [31merror[39m: Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2019-09-10 17:51:07.138  - [31merror[39m: Caught by controller[0]:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2019-09-10 17:51:07.138  - [31merror[39m: Caught by controller[0]:     at startup (internal/bootstrap/node.js:283:19)
2019-09-10 17:51:07.139  - [31merror[39m: Caught by controller[0]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
2019-09-10 17:51:07.139  - [31merror[39m: host.iobroker instance system.adapter.iot.0 terminated with code 1 ()
2019-09-10 17:51:07.139  - [32minfo[39m: host.iobroker Restart adapter system.adapter.iot.0 because enabled
2019-09-10 17:51:37.153  - [32minfo[39m: host.iobroker instance system.adapter.iot.0 started with pid 18328`

This error comes and the adapter stops working

**Comment by Apollon77** [comment]
did you forgot to add a "," at the end of the line before?

**Comment by klotzma** [comment]
Yes, I forgot a comma. The iot adapter has not been disconnected for 1.5 hours

**Comment by GermanBluefox** [comment]
> Yes, I forgot a comma. The iot adapter has not been disconnected for 1.5 hours

Very interesting....

**Comment by GermanBluefox** [comment]
@graebm What is the suggested value for keepalive?

**Comment by Apollon77** [comment]
@graebm just for my understanding: What is the default when not set? Or is then no "keep alive" is done at all?

**Comment by klotzma** [comment]
What changed the "keepalive"?  So for stupid people, like me.  I'm not so familiar with Javascript.

**Comment by klotzma** [comment]
Since I added the line "keepalive", there was no disconnect or "econnreset" error in the log anymore.

**Comment by Apollon77** [comment]
Coooool ...Then we will prepare a new release with this change soon. In theory it would be intersting which other values would also work, so that maybe the default or the "best practice" could be adoped to prevent such problems also for other users

**Comment by pedro-brito-automa** [comment]
I dont understand well how the keepalive affect the connection, I was having the same problem here, and it was solved setting the keepalive to 60. 
is it related to time that server need to maintain the connection alive ? 
can 300s be more than the server need to work well?
