### ISSUE TITLE
Handle credentials update manually

### ISSUE THREAD

**Issue by jsisdrug** [aws/aws-iot-device-sdk-js#281]
Hi, I'm currently using an API to get credentials(expires in an hour) and successfully created a websocket connection. 

My Approach:
I created a timeout based on credentials expiry to fetch the latest credentials which seem to work fine until I disconnect and reconnect to internet.

I also tried applying this logic in reconnect but it actually tries to call the API when there is no internet connection.

I tried to end and create new connection based on page change but I'm unable to end the connection as the credentials are expired.

Where should I handle the logic to get latest credentials?

**Comment by jmklix** [comment]
What api are you using to get the credentials?

**Comment by oneEyedSunday** [comment]
> Hi, I'm currently using an API to get credentials(expires in an hour) and successfully created a websocket connection.

Hello @jsisdrug how are you adding a custom expiry to your function / API that signs the Wss url?
