### ISSUE TITLE
Unit tests do not pass if `AWS_PROFILE` environment variable is set

### ISSUE THREAD

**Issue by dhillis-miovision** [aws/aws-iot-device-sdk-js#283]
To reproduce:

`AWS_PROFILE=foo npm test`

This causes 2 tests to fail:
```
  144 passing (2s)
  2 failing

  1) device class unit tests device not throw an exception if using websocket protocol with filename specified in options does not throws exception:
     AssertionError [ERR_ASSERTION]: Got unwanted exception.
Actual message: "Invalid connect options supplied."
      at Context.<anonymous> (test/device-unit-tests.js:407:17)

  2) thing shadow class unit tests Verify that MQTT operations use the correct shadow qos values "after all" hook:
     Uncaught 1 test failed.
```

The issue seems to come from device/index.js:485 which reads:
`var user_profile = options.profile || process.env.AWS_PROFILE || 'default';`
The unit tests don't do anything with this environment variable and it ends up setting `user_profile` to `foo` (in my example above), but then it can't find the correct profile from the list.

**Comment by dhillis-miovision** [comment]
@fengsongAWS I think the bot is correct here as well. I don't see this particular error on master (although I see a different error):

```
1) device class unit tests device not throw an exception if using websocket protocol with filename specified in options does not throws exception:
     AssertionError [ERR_ASSERTION]: Got unwanted exception.
Actual message: "Invalid connect options supplied."
      at Context.<anonymous> (test/device-unit-tests.js:407:17)
```

**Comment by Mo33n** [comment]
This message is because /test/data/credentials file doesn't contain credentials for your AWS_PROFILE.
Here is the PR to print a message in that case. [344](https://github.com/aws/aws-iot-device-sdk-js/pull/344)

**Comment by graebm** [comment]
The issue is user environment variables that the tests didn't expect to be set. A real fix for these test failures would be to add the following:
```
delete process.env.AWS_PROFILE
delete process.env.AWS_SESSION_TOKEN
```

to any test that's currently deleting or setting `process.env.AWS_ACCESS_KEY_ID`

**Comment by bretambrose** [comment]
This has been addressed via https://github.com/aws/aws-iot-device-sdk-js/pull/380
