### ISSUE TITLE
Cannot call `update` from within `on('timeout')` callback

### ISSUE THREAD

**Issue by dhillis-miovision** [aws/aws-iot-device-sdk-js#284]
There's an issue with `ThingShadowsClient` such that you can't call `update` from within the callback of `on('timeout')`.

Because the `on`'s callback can be executed synchronously, the callback runs in a strange context where the `thingShadows[thingName].pending` is `false`, however, the old `thingShadows[thingName].timeout` and `thingShadows[thingName].clientToken` are still set.

This causes the message handler to consider subsequent accepted messages as a `foreignStateChange` and will end up discarding the message, triggering a timeout on the second request.

**Comment by bretambrose** [comment]
Thanks for digging into this.  We'll have someone take a look at the PR.
