### ISSUE TITLE
premature close...only on Android 5.0 and up??

### ISSUE THREAD

**Issue by tronious** [aws/aws-iot-device-sdk-js#286]
So I'm really at a loss here.  We have a Cordova application that runs on multiple versions of Android.

When sending data to AWS-IOT on Android 4.(pick your flavor) it works.  Anything above that...no dice.

In the 'error' callback I keep seeing premature close.

While it seems tremendously strange that it would have anything to do with specific versions of Android...this is the only commonality I can see.

Using latest versions of aws-iot-device-sdk and aws-sdk

I'm sure I'm not providing enough information here...so please let me know what other information I can supply and I will.  Thanks for any help anyone can provide

**Comment by veslav3** [comment]
I have a premature close issue when using the jobs-example.js

**Comment by mwinnogy** [comment]
Can you tell if the messages reach their destination and do you see any errors on the could side?

You can find errors in the log in CloudWatch=> Logs => Insights
(sometimes it takes a moment to refresh the log data)
https://console.aws.amazon.com/cloudwatch

Usually I get premature close errors when I have not set the correct permissions.

Maybe that does not solve your Android specific question but in general for jobs you need to subscribe these topicfilters (and allow to receive the topics):
- $aws/things/MyThing/jobs/notify (or $aws/things/MyThing/jobs/notify-next)
- $aws/things/MyThing/jobs/get/accepted
- $aws/things/MyThing/jobs/get/rejected
- $aws/things/MyThing/jobs/jobId/get/accepted
- $aws/things/MyThing/jobs/jobId/get/rejected

for updating jobs you at least need publishing permissions for the topic
- $aws/things/MyThing/jobs/jobId/update

(Keep in mind that you always need to add the prefix, e. g. ``"arn:aws:iot:<region>:<account>:topicfilter/`$aws/things...``
That may sound obvious but took me some time when starting with jobs)

More information here:
https://docs.aws.amazon.com/iot/latest/developerguide/jobs-devices.html
https://docs.aws.amazon.com/iot/latest/developerguide/topics.html

These information should be added as a comment to the code for subscribing, updating jobs.

**Comment by ionSurf** [comment]
Also, check for the clientID that you're using for both connecting as the ShadowThing and the ShadowMonitor, THEY CANNOT BE THE SAME. This will result in connection drops on both sides.

**Comment by jmklix** [comment]
@tronious are you still having problems on Android 5.0 and up?
