### ISSUE TITLE
Using persistent sessions (with cleanSession = 0)

### ISSUE THREAD

**Issue by franciscofrr** [aws/aws-iot-device-sdk-js#288]
Hi there! [On this link](https://docs.aws.amazon.com/iot/latest/developerguide/mqtt-persistent-sessions.html), the documentation says that AWS IoT now supports persistent sessions with MQTT by setting the cleanSession parameter to 0 and reading the sessionPresent attribute from the CONNACK. However, I can't seem to find anything related to it on this repository. Has this functionality only been implemented in other languages (e.g. Java)?

**Comment by justinboswell** [comment]
That is correct. We have implemented it in all of the v2 SDKs which are coming soon.

https://github.com/awslabs/aws-iot-device-sdk-js-v2 is the JS one.

**Comment by amdixit** [comment]
When is this becoming available as npm? Also, is there a documentation on the library spec?

**Comment by graebm** [comment]
https://www.npmjs.com/package/aws-iot-device-sdk-v2
