### ISSUE TITLE
'.' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ewendel88** [aws/aws-iot-device-sdk-js#290]
I have installed Browserify. When I run npm run-script browserize I get the error. it looks like it is failing on "./scripts/browserize.sh" see error log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\elliott.wendel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'browserize' ]
2 info using npm@6.12.0
3 info using node@v8.9.1
4 verbose run-script [ 'prebrowserize', 'browserize', 'postbrowserize' ]
5 info lifecycle aws-iot-device-sdk@2.2.2~prebrowserize: aws-iot-device-sdk@2.2.2
6 info lifecycle aws-iot-device-sdk@2.2.2~browserize: aws-iot-device-sdk@2.2.2
7 verbose lifecycle aws-iot-device-sdk@2.2.2~browserize: unsafe-perm in lifecycle true
8 verbose lifecycle aws-iot-device-sdk@2.2.2~browserize: PATH: blahblahblah
9 verbose lifecycle aws-iot-device-sdk@2.2.2~browserize: CWD: C:\Users\elliott.wendel\Downloads\aws-iot-device-sdk-js
10 silly lifecycle aws-iot-device-sdk@2.2.2~browserize: Args: [ '/d /s /c', './scripts/browserize.sh' ]
11 silly lifecycle aws-iot-device-sdk@2.2.2~browserize: Returned: code: 1  signal: null
12 info lifecycle aws-iot-device-sdk@2.2.2~browserize: Failed to exec browserize script
13 verbose stack Error: aws-iot-device-sdk@2.2.2 browserize: `./scripts/browserize.sh`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\elliott.wendel\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\elliott.wendel\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid aws-iot-device-sdk@2.2.2
15 verbose cwd C:\Users\elliott.wendel\Downloads\aws-iot-device-sdk-js
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\elliott.wendel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "browserize"
18 verbose node v8.9.1
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error aws-iot-device-sdk@2.2.2 browserize: `./scripts/browserize.sh`
22 error Exit status 1
23 error Failed at the aws-iot-device-sdk@2.2.2 browserize script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ShunKeJiang** [comment]
@ewendel88 Modify "browserize": "./scripts/browserize. Sh "in package.json to "browserize": ".\ scripts\ browserize. Sh ",

**Comment by ShunKeJiang** [comment]
@ewendel88 Modify "browserize": "./scripts/browserize. Sh "in package.json to "browserize": ".\\scripts\\ browserize. Sh ", Because in windos/is treated as a string

**Comment by ShunKeJiang** [comment]
@ewendel88 This is '\\' I don't know why github gave me '\'

**Comment by KaibaLopez** [comment]
Hi , thanks @ShunKeJiang.
And @ewendel88 , did his suggestion fix your issue?
