### ISSUE TITLE
Vue Js Integration

### ISSUE THREAD

**Issue by ayse-ozer** [aws/aws-iot-device-sdk-js#296]
I want to add “aws-iot-device-sdk” to my project, but I couldn’t find such a plugin for vue js. Have you used it before.

**Comment by bretambrose** [comment]
Hello,

I don't think anyone on the team has used vue js before but I'm not sure why a specific plugin is needed.  The two libraries have very specific concerns that don't seem to overlap.  You should be able to consume the iot device sdk the same way you would with any other package.

**Comment by dalumiller** [comment]
Hi @ayse-ozer, I work with Vue and all you need to do is require the aws-sdk, and then create a new instance of AWS.IoT. You'll need npm install aws-sdk, and configure your credentials as well.

**Comment by ayse-ozer** [comment]
Hi @dalumiller , I have included the "aws-iot-device-sdk" and "aws-sdk" plugins in my project and created a js file like in the https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/browser/mqtt-explorer/index.js link.
After doing this, I started to import the data, but no dynamic structure occurred. Can I do what I want to do with Vue Mqtt?

**Comment by dalumiller** [comment]
@ayse-ozer I'm not sure what Vuq Mqtt is offering you that the iot instance wouldn't. It looks like Vue Mqtt provides methods to pub/sub, which the iot instance offers. Is using Express or a Lambda triggered by your front end to use the iot sdk to pub/sub not an option? I may me misunderstanding your use of Vue Mqtt, if so can you explain the scenario?
