### ISSUE TITLE
Create job code signing formats not working with aws-iot-device-sdk-js?

### ISSUE THREAD

**Issue by ydvsailendar** [aws/aws-iot-device-sdk-js#298]
_I have created a job with job-document as follow:_

```
{
  "operation": "install",
  "packageName": "copy-server.js",
  "workingDirectory": "./examples",
  "files": [
    {
      "fileName": "server.js",
      "fileVersion": "1.0.0",
      "fileSource": {
        "url": "${aws:iot:code-sign-signature:s3://us-east-1.<bucket_name>/server.js@version_id}"
      }
    }
  ]
}
```
_I am using a profile created using platformId of "AWSIoTDeviceManagement-SHA256-ECDSA" for code signing. the output is the below job document recieved by the job agent:_

```
{
  "operation": "install",
  "packageName": "copy-job.js",
  "workingDirectory": "./examples/",
  "files": [
    {
      "fileName": "server.js",
      "fileVersion": "1.0.0",
      "fileSource": {
        "url": {
          "rawPayloadSize": 137,
          "signature": "xxxxxxxxXXXXXXxxxxxxxx==",
          "signatureAlgorithm": "SHA256withECDSA",
          "payloadLocation": {
            "s3": {
              "bucketName": "bucket_name",
              "key": "server.js",
              "version": "version_id"
            }
          }
        }
      }
    }
  ]
```
_Now as per the aws-iot-device-sdk-js document example for install the format shown there is:_

```
{
  "operation": "install",
  "packageName": "uniquePackageName",
  "workingDirectory": "../jobs-example-directory",
  "launchCommand": "node jobs-example.js -f ~/certs -H <PREFIX>.iot.<REGION>.amazonaws.com -T thingName",
  "autoStart": "true",
  "files": [
    {
      "fileName": "jobs-example.js",
      "fileVersion": "1.0.2.10",
      "fileSource": {
        "url": "https://some-bucket.s3.amazonaws.com/jobs-example.js"
      },
      "checksum": {
        "inline": {
          "value": "9569257356cfc5c7b2b849e5f58b5d287f183e08627743498d9bd52801a2fbe4"
        },
        "hashAlgorithm": "SHA256"
      }
    },
    {
      "fileName": "config.json",
      "fileSource": {
        "url": "https://some-bucket.s3.amazonaws.com/config.json"
      }
    }
  ]
}
```

1. So my question here is am I doing something wrong to generate different outputs?
2. Or the example in the SDK and the generated document by AWS coding signing are handled in two different ways?
3. I am stuck here so I am looking for any suggestions on how to tackle it and what's being done wrong from my side?

**Comment by graebm** [comment]
It seems that  job documents that reference code-signed URLs will have a different format when sent to the job agent, compared to documents whose references do not use code-signing. The job sample included in the SDK does not expect the document to use code-signing. If you want to use code-signing, and use the sample as a starting point, you'll need to dig in and modify the code

**Comment by jmklix** [comment]
@ydvsailendar where you able to get the signing formats working?
