### ISSUE TITLE
Add clock offset support

### ISSUE THREAD

**Issue by maciejdzikowicki** [aws/aws-iot-device-sdk-js#299]
Currently it is not possible to connect to MQTT if user has incorrect time settings on his machine. 

Please add handling for `systemClockOffset` like is implemented in https://github.com/kndt84/aws-api-gateway-client/blob/master/src/lib/apiGatewayCore/sigV4Client.js#L201

**Comment by KaibaLopez** [comment]
Hi @maciejdzikowicki , thanks for bringing this up, I'll look into it, but on the mean time, have you tried the v2 sdk?

**Comment by maciejdzikowicki** [comment]
Correct me if I'm wrong, but https://github.com/aws/aws-iot-device-sdk-js-v2 doesn't look like production ready project. I'm not using shadows in my project and I don't see similar stuff like `DeviceClient` in v1.

**Comment by graebm** [comment]
Across all AWS client software, we have varied support for "clock skew". We are currently debating whether this feature is desirable. It can actually be very dangerous in distributed systems if clock skew exists on any machine in "the middle".

**Comment by maciejdzikowicki** [comment]
@graebm I agree and in my case it is user issue (not correct time on user machine). In my project I'm using API Gateway and IoT. For API Gateway I'm able to fix clock offset, but for IoT it is not possible without overriding AWS libs. I don't want to ask clients to change their local clock.

**Comment by jmklix** [comment]
Sorry, but we are no longer considering any feature requests for this sdk as it is being sunsetted. The [V2](https://github.com/aws/aws-iot-device-sdk-js-v2) sdk is accepting feature requests.
