### ISSUE TITLE
node vs. javascript

### ISSUE THREAD

**Issue by AdamGlass** [aws/aws-iot-device-sdk-js#30]
it seems like this SDK only works in Node and isn't pure javascript.  Is it possible to adapt it for browsers so that it could be used in something like Cordova?

Actually i noticed in the AWS IoT documentation that this was referred to as an SDK for NodeJS.  Maybe just retitle the github README.

**Comment by gkwicker** [comment]
Hi Adam,

Thanks for pointing this out, and we'll update the title in the README.md to clarify that this SDK is only for use with Node.js in the next release.  If you need to access AWS services from the browser, you might have a look at the [AWS SDK for JavaScript](https://github.com/aws/aws-sdk-js).  Let us know if that answers your question, and thanks for using AWS IoT.

**Comment by gkwicker** [comment]
Fixed in [Version 1.0.10](https://github.com/aws/aws-iot-device-sdk-js/releases/tag/v1.0.10)

**Comment by Krieke** [comment]
The AWS SDK for JavaScript doesn't support mqtt protocol?

**Comment by rongsaws** [comment]
That's correct. The regular AWS SDK for JavaScript only supports Restful APIs, however it does include AWS IoT support with APIs listed in

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Iot.html
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IotData.html

If you plan to use MQTT (via TLS or Websocket), you need to use AWS IoT Device SDK for NodeJS.

**Comment by Krieke** [comment]
Hello @rongsaws : this is what I am currently trying to do... see issue : "Uncaught TypeError: filesys.existsSync is not a function".  I am currently stuck on the sdk bundle

**Comment by juppdes** [comment]
@Krieke you have solved the question ?
