### ISSUE TITLE
AWS IOT + iONIC4 + Angular + MQTT

### ISSUE THREAD

**Issue by puneetjindal1000** [aws/aws-iot-device-sdk-js#300]
I am unable to use your SDK in my Ionic 4 application. AWS amplify is working fine and I am able to use it to successfully log in using AWS Cognito. How to include your module in my hybrid app? Can you provide me a simple example to include the module in my app and initialize MQTT client. I tried NPM install it is giving "process.version is undefined"

`import * as AWS from "aws-sdk";
AWS.config.region = 'us-east-2';
AWS.config.credentials = new AWS.CognitoIdentityCredentials({IdentityPoolId: 'region:xxxxxxxxxxxxxxxxxxxxxxxxxx'});

this.client = new AWSMqttClient(
{
			region: AWS.config.region,
			credentials: AWS.config.credentials,
			endpoint: 'xxxxxxx.iot.region.amazonaws.com',
			expires: 40, // Sign url with expiration of 600 seconds
			clientId: 'mqtt-client-' + (Math.floor((Math.random() * 100000) + 1)),
			will: 
			{
				topic: 'WillMsg',
				payload: 'Connection Closed abnormally..!',
				qos: 0,
				retain: false
			} 
		});
		   
		this.client.on('connect', () => 
		{
			this.client.subscribe('/myTopic')
		});

		this.client.on('message', (topic, message) => 
		{
			console.log(topic, message)
		});

		this.client.on('close', () => 
		{
			console.log('Closed');
		});
		this.client.on('offline', () => 
		{
			console.log('Offline');
		});`

Thank you

**Comment by rccarper** [comment]
Hello,

Based on your code sample, I think you may be currently using a 3rd party library for MQTT (https://github.com/kmamykin/aws-mqtt).  Is that accurate?  Also, if you're interested in switching to the IoT SDK in this repo, we do have some examples that should help you get started, including a handful for working inside of a web browser: https://github.com/aws/aws-iot-device-sdk-js/tree/master/examples.

Thanks,
Ryan
