### ISSUE TITLE
Node v12 'close' event is not emitted when publish message to unauthorised topic (using mqtt 3.0 solves this)

### ISSUE THREAD

**Issue by dyrobin** [aws/aws-iot-device-sdk-js#301]
When publishing a message to unauthorised topic using aws iot, AWS logs error and disconnect event  in AWS CloudWatch.  Previously 'close' event was emitted in aws iot sdk run by node v8. But in Node v12 the 'close' event is not emitted any more. 

With Node v12 I tried to use mqtt.js 3.0.0 and the 'close' event is emitted again. Should aws-iot-sdk update its dependency of mqtt.js to version 3.0.0?

**Comment by justinboswell** [comment]
This SDK is being sunsetted, and is unlikely to see updates unless there are security issues. See [aws/aws-iot-device-sdk-js-v2](https://github.com/aws/aws-iot-device-sdk-js-v2) for an up to date JS implementation.
