### ISSUE TITLE
Unable to connect to IOT core via wss (unexpected server response (403)) 

### ISSUE THREAD

**Issue by toughdeveloper** [aws/aws-iot-device-sdk-js#305]
Hi,

I'm trying to connect to IOT core using the websocket protocol following the examples:

```
node examples/device-example.js --protocol=wss --host-name=a2rwtpm8dpfd2a-ats.iot.eu-west-1.amazonaws.com --port=443
```

I've checked I have valid aws credentials and ensured the IAM policy has full IOT Core access.

As per the docs, I've added my valid `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to my environment:

```
export AWS_ACCESS_KEY_ID=[a valid AWS access key ID]
export AWS_SECRET_ACCESS_KEY=[a valid AWS secret access key]
```

But the script fails to connect, returning:

```
offline
error Error: unexpected server response (403)
    at ClientRequest.<anonymous> (/Users/matthewpawley/Documents/dev.nosync/aws-iot-device-sdk-js/node_modules/ws/lib/WebSocket.js:653:21)
    at ClientRequest.emit (events.js:223:5)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
    at TLSSocket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:181:23) 
```

Any advice would be appreciated.

**Comment by KaibaLopez** [comment]
Could you add `-d` to get more debug information?

**Comment by toughdeveloper** [comment]
Managed to resolve the issue.

When not using the example we included the `sessionToken` and it worked:

```
const device = awsIot.device({
    clientId: 'test',
    host: host,
    protocol: 'wss',
    accessKeyId: credentials.AccessKeyId,
    secretKey: credentials.SecretAccessKey,
    sessionToken: credentials.Token
});
```

**Comment by RavirajKakadeGit** [comment]
@toughdeveloper i had tried with above config its works but you haven't added port number, Please add `port: '443'` in your config then its giving 403 error 😢

**Comment by Koyana-t** [comment]
I believe wss using port:443 normally. 
plz check device index.js line 173. and also dev guide protocols  section said, wws using port:443.

   // Include the port number in the hostname if it's not 
   // the standard wss port (443).
   //
   if (!isUndefined(options.port) && options.port !== 443) {
      hostName = options.host + ':' + options.port;
   }

**Comment by RavirajKakadeGit** [comment]
Yeah..i'm also conclude the same. Thanks @Koyana-t
