### ISSUE TITLE
Retrieve clientToken on delta

### ISSUE THREAD

**Issue by ctobolski** [aws/aws-iot-device-sdk-js#306]
We are trying to access the clientToken on the delta to track the status of state update requests to our IoT devices, and are listening to the update/accepted topic for one that we supply when interacting with the device shadow service over REST. 

We notice that if we subscribe through the test section of IoTCore, we can see the clientToken, and after a little searching, we found that the clientToken is being explicitly removed in the handleMessages function in the Thing module. 

Can we get that clientToken exposed? I noticed the comment mentioned that the clientToken was internal to the class, but this handicaps our ability to track longer lived clientTokens.

**Comment by KaibaLopez** [comment]
Hi @ctobolski,
A few things that I'd like to note here...
I'm a bit confused on what the problem is, could you provide sample code on what you're trying to do and what is the expected result? I get that you're trying to access clientToken, but I'm not sure on when or where you're trying to access it (device.on( 'message') maybe? )
 
Also, exposing clientToken may be a customization that you could do for your code, I'm not convinced that it is a "feature" needed on the sdk, so for now I'll mark this as guidance...

Finally, you may also want to check out [V2](https://github.com/aws/aws-iot-device-sdk-js-v2/) of this sdk, it may be easier to use even if it has less documentation at the moment.

**Comment by ctobolski** [comment]
Hello @KaibaLopez, I'd be happy to explain this a bit more thoroughly.

We are trying to track the status of asynchronous requests. So if we take the IoT lightbulb example, I can send a new color to a lightbulb by updating the thingShadow using the device shadow service. When providing this functionality to my users, I want them to know definitively that the color change propogated to the light bulb. The way we are attempting to track the status of a state change is by passing our own clientToken to the device shadow service when we publish a desired state change. We would then store that clientToken in a repository with a status indicating the request is in progress.

That token goes to the device on the delta topic. We were thinking to use the same clientToken when we report from the device that the state change was accepted. That way we can have an IoT rule that will listen for update/accepted messages, pulling off the clientToken and updating our record to set the status of the operation associated with that token to completed.

Our intention is to expose an asynchonous REST api that will allow people to request a state change on the device, and receive a clientToken back which they can then use to poll a clientToken status endpoint to track the progress of the request.

Here's the relevant code:

Our service: 
```
const updateThingShadowDesiredState = async (
  deviceId: string,
  payload: Partial<DeviceState>,
  clientToken = uuid(),
): Promise<UpdateThingShadowResponse | AWSError> => {
  const desiredStateUpdate = {
    state: {
      desired: {
        ...payload,
      },
    },
    clientToken,
  };
  try {
    const response = await iotData
      .updateThingShadow({
        thingName: deviceId,
        payload: JSON.stringify(desiredStateUpdate),
      })
      .promise();
    return response;
  } catch (error) {
    handleError(error);
  }
};
``` 

On the device we're expecting to receive the clientToken as part of the delta event.

```
device.on('delta', function(thingName, stateObject) { 
  device.update(DEVICE_NAME, {
    state: {
      reported: stateObject.state,
      clientToken // we would like to retrieve the client token from the delta to pass it along here
    },
  });
});
```
Based on some of the reading I have done, I don't believe that the clientToken is necessarily internal to the sdk. [This whitepaper](https://d1.awsstatic.com/whitepapers/Designing_MQTT_Topics_for_AWS_IoT_Core.pdf) detailing best practices for mqtt has a section on tracking state updates that seems to be intentionally removed from the sdk.

Specifically, if you look at pages 16/17 in the Command Processing on Wind Turbine section, you can see that the stateObject contains the clientToken and that the reported update from the IoT device contains the same clientToken. This is what we are trying to achieve with the sdk.

**Comment by KaibaLopez** [comment]
Hi @ctobolski , just a quick update, I've been playing around the example, and I've only managed to send the client token as part of the state, which is probably not exactly what you want, but to do more you'd need to do some more deep changes in the device class, and I've not been able to make it work.

Right now I'm trying to get it to work the sdk's V2, which you might want to try too btw, but it'd writing the sample from scratch so It'll take a bit longer. I'll update again when I manage to make it work.

**Comment by ctobolski** [comment]
Thanks! We would love the sdk to support this or some guidance on why it isn't supported. Did we misunderstand the white paper? Is the pattern we're considering incorrect?

**Comment by pequnio3** [comment]
I'm also interested in accessing the ClientToken.  I find it strange that the clientToken is referenced so much in the documentation (https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-document.html) for what is available, but it is not present as accessible to the user.  This token can be very useful for me to understand what device is making what request and performing logic on that.

**Comment by jmklix** [comment]
Are you looking for an example of it being used like in the ['thing-example'](https://github.com/aws/aws-iot-device-sdk-js/blob/abc9fa4137b0d93455ed996a77e1d684a16dcdd0/examples/thing-example.js#L75):

`var clientToken = thingShadows[operation](thingName, state);`
