### ISSUE TITLE
SDK doesn't seem to work with a role inside of an AWS profile

### ISSUE THREAD

**Issue by zomgbre** [aws/aws-iot-device-sdk-js#307]
It seems that if you have a profile in your .aws/credentials with a role instead of straight up access keys this SDK cannot work with it. This is really not awesome for local development.

This works:
```
[some_profile]
aws_access_key_id = xxxxxxxxxx
aws_secret_access_key = xxxxxxxxxxxxx
```

This does not:
```
[some_profile]
aws_access_key_id = xxxxxxxxxx
aws_secret_access_key = xxxxxxxxxxxxx

[some_profile_with_role]
role_arn = arn:aws:iam::XXXXXXXXXXX:role/some-cross-account-role
source_profile = some_profile
```

Looking at the source code, it appears to not take this into account...

**Comment by KaibaLopez** [comment]
Hi @zomgbre ,
This feature was implemented on the [sdk's V2](https://github.com/aws/aws-iot-device-sdk-js-v2), you may want to give it a try.
Also for reference, we are moving feature requests to V2, and only doing maintenance on this repo.
