### ISSUE TITLE
jobs-agent.js to execute a single command?

### ISSUE THREAD

**Issue by cyrusadkisson** [aws/aws-iot-device-sdk-js#308]
I'm using jobs-agent and it's great for rebooting, shutting down, and installing packages (with "installPackage") that will get fired every time jobs-agent.js is started.

But most of the time, I just want to either

1. Send a file
2. Send a file and execute a command (usually relating to the file sent)

But, for the life of me, I can't figure out how to make jobs-agent do this. It always wants to "installPackage" and then keeps attempting to run the "launchCommand" every time jobs-agent.js starts up. I just want it run once and then never again.

"autoStart" true/false doesn't seem to matter.

I could set up a system where I set installedPackages.json to "[ ]" after a package installation (which would result in one execution and then force jobs-agent to forget it) but this seems hacky.

Could I get some advice on this?

**Comment by KaibaLopez** [comment]
Hi @cyrusadkisson ,
Sorry but I'm not exactly sure what you're asking for, this sample was designed to do those steps, so yeah if you're using the sample code, your solution seems good to me.
If you want a "cleaner" solution you'd have to write the sample yourself but, we are a low on documentation and samples so I don't really have another place I can point you towards for ideas on how to do that.
That being said I would recommend that if you'll go for it and do it from scratch, try using the sdk's [V2](https://github.com/aws/aws-iot-device-sdk-js-v2), should be simpler to use and if you come across a feature request, it is more likely to be addressed as we are only doing maintenance on this version.

**Comment by jmklix** [comment]
@cyrusadkisson are you still having trouble with jobs-agent?
