### ISSUE TITLE
getting 403 when connection type is MQTT over WebSocket/TLS with SigV4 authentication using port 443

### ISSUE THREAD

**Issue by RavirajKakadeGit** [aws/aws-iot-device-sdk-js#309]
My device config
``````
const opts = {
   host: 'XXXX-ats.iot.us-east-2.amazonaws.com',
   clientId: 'rk-node-local',
   port: '443',
   protocol: 'wss',
   accessKeyId: 'XXXX',
   secretKey: 'XXX',
   debug: true
};

I'm getting while handshaking:

error { Error: unexpected server response (403)

I had tried with remove port 443 property its working fine but its on 8883, i want to run wss on port 443.

here is my device policy :

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "*"
    }
  ]
}

Any help will appreciate, Thankns in advanced.

**Comment by RavirajKakadeGit** [comment]
Tried with exiting thing-example.js with 443 same issue observed

` node ./node_modules/aws-iot-device-sdk/examples/thing-example.js -P=wss --test-mode=1 -H XXX-ats.iot.us-east-2.amazonaws.com --Debug=true --clientId=rk-node-local
`

**Comment by RavirajKakadeGit** [comment]
Do i need to pass  `port: '443' `manually for wss/TLS connection?

**Comment by Koyana-t** [comment]
I want to know following 2-point,

1) Where your aws user/role coming from?
- if you use Cognito, is that case need the "SessionToken" or static user?

2) anyway, your AWS user/role has attached the policy?

role or user has directly attached "AWSIoTDataAccess"
or
cognito user related the iot policy 
https://docs.aws.amazon.com/iot/latest/developerguide/pub-sub-policy.html#pub-sub-policy-cognito

**Comment by KaibaLopez** [comment]
Hi @RavirajKakadeGit ,
port 443 is the default for wss connection so no, it should not be necessary to explicitly assign it.
I can run the exact same command on my side though, so I'm inclined to think this is a configuration issue, either or your iot thing, policy or certifications.
