### ISSUE TITLE
 AWS IOT Device SDK not connecting with few window10 system browsers

### ISSUE THREAD

**Issue by balramgoyal** [aws/aws-iot-device-sdk-js#310]
We are using aws-iot-device-sdk javascript package (https://www.npmjs.com/package/aws-iot-device-sdk ) in our chat application in our angular application for real time messaging.

Everything is working fine in all browsers of ubuntu and mac operating systems. But in browsers of few windows operating system (chrome, firefox and edge), mqtt is not able to connect to aws iot. Moreover this error is not captured by AWS cloud watch even after enabling logs by us.

Our findings after debugging:
1.  Your aws iot mqtt based sample code (https://github.com/aws-samples/aws-iot-examples/tree/master/mqttSample ) is also not connecting with aws iot in the specific windows system where our application is not able to connect. But interesting thing is that this sample code is able to connect with other test mqtt brokers such as wss://test.mosquitto.org:8081/mqtt, ws://broker.mqttdashboard.com:8000/mqtt

So why this code on that system is able to connect with other mqtt broker but not to aws iot?

2. The above issue is not getting captured on AWS cloud watch even after enabling logs by us.

3.  Why the same code is working fine with other systems (All linux systems, all Mac systems, few windows system) but not on specific windows system?

Please find the error details which appeared on browser console.

```
 failed: Error during WebSocket handshake: Unexpected response code: 403
```

**Comment by ShunKeJiang** [comment]
@balramgoyal  Please do not connect two devices to the iot with the same name, as this setting will block the next person from entering, and the AWS iot will be refreshed repeatedly and webSocket 403 will appear

**Comment by jmklix** [comment]
Are you still running into this issue on windows 10 while making sure to use different iot device names?
