### ISSUE TITLE
有一行表述出错

### ISSUE THREAD

**Issue by ihoment-meihui** [aws/aws-iot-device-sdk-js#311]
https://github.com/aws/aws-iot-device-sdk-js/blob/master/test/device-unit-tests.js
第 85 行 "device is instantiated with no public key"
应该是 "device is instantiated with no private key" 吧

**Comment by KaibaLopez** [comment]
Hi @ihoment-meihui, thanks for pointing this out!
Could you make a pull request with this change?

**Comment by ihoment-meihui** [comment]
OK

**Comment by bretambrose** [comment]
Addressed in https://github.com/aws/aws-iot-device-sdk-js/pull/379
