### ISSUE TITLE
How to connect local greengrass core from device in group

### ISSUE THREAD

**Issue by lakinmohapatra** [aws/aws-iot-device-sdk-js#313]
How to connect local greengrass core from device in group

Please help/ advise.

**Comment by lakinmohapatra** [comment]
Will it automatically connect or we need to put host as local core ip ? Please let us know.

**Comment by jmklix** [comment]
@lakinmohapatra sorry for the slow reply. [Here](https://docs.aws.amazon.com/greengrass/latest/developerguide/quick-start.html) is a guide that include a script to get you started. That should allow it to connect automatically. Please let me know if you have any problems or other questions regarding greengrass.
