### ISSUE TITLE
Quality of service

### ISSUE THREAD

**Issue by simerpreetjassal** [aws/aws-iot-device-sdk-js#316]
Hi ,

I know AWS IOT supports QOS 0 and QOS 1. But i did not find anything regarding quality of service here in node SDK. Can you tell me how can I publish with QOS 1.

Thanks

**Comment by bretambrose** [comment]
The v1 IoT SDK is built on mqtt.js.  Consulting its [documentation](https://github.com/mqttjs/MQTT.js/blob/master/README.md#publish) will tell you how to control the quality of service parameter.
