### ISSUE TITLE
npm audit: some vulnerabilities require your attention to resolve

### ISSUE THREAD

**Issue by Igor-lkm** [aws/aws-iot-device-sdk-js#318]
To reproduce:

```
npm init
npm i aws-iot-device-sdk -S
npm audit fix
npm audit
```

Npm audit security report:
```
found 1 low severity vulnerability in 430 scanned packages
  1 vulnerability requires manual review. See the full report for details.
```

PR is there for a while: https://github.com/aws/aws-iot-device-sdk-js/pull/315

**Comment by aws-kens** [comment]
It looks like **minimist** package needed to be updated to **1.2.5** in [package.json](https://github.com/aws/aws-iot-device-sdk-js/blob/8aae59e68a37130e8fd5bb0a14a533a9b6c94529/package.json#L32)

**Comment by Igor-lkm** [comment]
Exactly and PR to do so is there https://github.com/aws/aws-iot-device-sdk-js/pull/315

**Comment by justinboswell** [comment]
It's being integrated internally and tested. At the moment, this GitHub repository is just a mirror, so the PR would just be overwritten.

**Comment by BrianRower-BR** [comment]
@justinboswell is there an ETA for the release?

**Comment by bretambrose** [comment]
2.2.4 has been published to npm just now.
