### ISSUE TITLE
Inconsistent indentation levels

### ISSUE THREAD

**Issue by Bitbored** [aws/aws-iot-device-sdk-js#32]
There seems to be some inconsistency in the indentation levels used by this SDK.

Most files seem to use an indentation level of 2 spaces, however some files, e.g [thing/index.js](https://github.com/aws/aws-iot-device-sdk-js/blob/master/thing/index.js) and [example/thing-example.js](https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/thing-example.js) use 3 spaces.

Even more OCD triggering examples are [device/index.js](https://github.com/aws/aws-iot-device-sdk-js/blob/master/device/index.js) and [examples/lib/cmdline.js](https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/lib/cmdline.js), which seem to use a mix of 2, 3 and 4 spaces indentation.

**Comment by gkwicker** [comment]
Hi Seppe, thanks for letting us know about the indentation level inconsistency.  We'll look into fixing this in an upcoming release.
