### ISSUE TITLE
.device call fails - stop reconnecting?

### ISSUE THREAD

**Issue by tronious** [aws/aws-iot-device-sdk-js#320]
If there is an invalid hostId or the service is down, the .device call never succeeds.

When this happens, the application infinitely tries to reconnect.  How do I stop this?

Summary:

1)  call .device()
2)  failure occurs establishing the websocket connection
3)  device object is never created
4)  infinitely receive "will reconnect after X seconds..." until I kill the application.

I can't call device.end() because the device is never created.

Help?  thoughts?

**Comment by tronious** [comment]
I made an update to the SDK on my end in _setupReconnect() function I'm calling _clearReconnect() after 3 attempts.  I'd rather not modify the SDK though.  If anyone knows a way to clear that interval out so it doesn't indefinitely keep trying to reconnect I would love to hear it.  Thanks

**Comment by KaibaLopez** [comment]
Hi @tronious ,
having a bit of problems picturing the situation, can you show me the code that you changed in the sdk as your workaround so I get a better idea on what exactly you're trying to do?
