### ISSUE TITLE
How to disconnect my device or things shadow from nodeJS

### ISSUE THREAD

**Issue by vic3king** [aws/aws-iot-device-sdk-js#322]
I have code like this just like in the AWS iot sdk documentation for node.
```
thingShadows.on('connect', function() {
    thingShadows.register( 'RGBLedLamp', {}, function() {
 
       var rgbLedLampState = {"state":{"desired":{"red":rval,"green":gval,"blue":bval}}};
 
       clientTokenUpdate = thingShadows.update('RGBLedLamp', rgbLedLampState  );

       if (clientTokenUpdate === null)
       {
          console.log('update shadow failed, operation still in progress');
       }
    });
});
```

I'm trying to disconnect from this connection using an update endpoint when I call it. How best can I achieve this? I've tried calling .end() but it returns an `Error: premature close` and reconnects . I need to be able to shut this down from my code... I'll appreciate any suggestions and pointers

**Comment by vic3king** [comment]
> I have code like this just like in the AWS iot sdk documentation for node.
> 
> ```
> thingShadows.on('connect', function() {
>     thingShadows.register( 'RGBLedLamp', {}, function() {
>  
>        var rgbLedLampState = {"state":{"desired":{"red":rval,"green":gval,"blue":bval}}};
>  
>        clientTokenUpdate = thingShadows.update('RGBLedLamp', rgbLedLampState  );
> 
>        if (clientTokenUpdate === null)
>        {
>           console.log('update shadow failed, operation still in progress');
>        }
>     });
> });
> ```
> 
> I'm trying to disconnect from this connection using an update endpoint when I call it. How best can I achieve this? I've tried calling .end() but it returns an `Error: premature close` and reconnects . I need to be able to shut this down from my code... I'll appreciate any suggestions and pointers

I found a way to force close the connection by calling `thingShadow.end()`. but when I do this I can no longer reconnect to the thing except I restart my server. what I'm trying to achieve is a switch functionality. where I turn a device on and off as many times as I want gracefully.

**Comment by jmklix** [comment]
Is this [issue ](https://github.com/aws/aws-iot-device-sdk-js/issues/249) similar to what you are trying to do?

**Comment by jmklix** [comment]
If you are still having problems please open a new issue and include a detailed description of what you are trying to do.
