### ISSUE TITLE
Connection lost when users opens multiple browser tabs

### ISSUE THREAD

**Issue by Bunlong** [aws/aws-iot-device-sdk-js#323]
When users opens one browser tab it work well; but connection being lost when one users opens multiple browser tabs in the same web application.

I checked the logs and could not see any errors except that offline appears and then in 1-2 seconds comes close and then in 1-2 seconds comes reconnect ... and then in 2-3 seconds come connect.

What it can be?

Regards, Bunlong

**Comment by KaibaLopez** [comment]
Hi @Bunlong , 
Sorry but it's hard to say with just this description...
 What do you mean multiple browser tabs? do you mean in the iot console? or a custom app using the sdk? Do you have sample code that replicates this behavior or are you using one of the samples?

**Comment by graebm** [comment]
It's likely that each browser tab is using the same client-id. You'll want a unique client-id per tab if you want this to work.

In MQTT, if a new connection attempt is made with the same client-id as an existing connection, then the existing connection is terminated. If your application is set up to automatically reconnect, then the two tabs will endlessly go back and forth reconnecting and kicking the other one off.

**Comment by Bunlong** [comment]
@KaibaLopez @graebm Yes, the problem is I used the same client-id. Thank your for your helpful support.
