### ISSUE TITLE
[Question] How to enable/disable IoT device using aws IoT api ?

### ISSUE THREAD

**Issue by kirantpatil** [aws/aws-iot-device-sdk-js#329]
Hi,

I would like to know,  how to enable/disable IoT device using aws IoT api ? 

I could not find in the aws documentation.

Thanks.

**Comment by kirantpatil** [comment]
Also I can deactivate the certificates using AWS IoT core management console but I don't find the API to do the same operation.

**Comment by jmklix** [comment]
Sorry for the delay. On [this](https://docs.aws.amazon.com/greengrass/latest/developerguide/deployments.html) page you can find API links to [CreateDeployment](https://docs.aws.amazon.com/greengrass/latest/apireference/createdeployment-post.html) and [ResetDeployments](https://docs.aws.amazon.com/greengrass/latest/apireference/resetdeployments-post.html). Is that what you are looking for?

**Comment by jmklix** [comment]
If you still have any questions please open a new issue and include a detailed description of what you are trying to do.
