### ISSUE TITLE
Can't resolve './aes' in aws-iot-sdk-browser-bundle.js

### ISSUE THREAD

**Issue by apotox** [aws/aws-iot-device-sdk-js#330]
Hi everyone,
I have an issue related to aws-sdk-device-js on the browser, after I generated the aws-iot-device-js bundle using Browserfy tool, I required the bundle in my web app 

`const awsIot = require("aws-iot-device-sdk/browser/aws-iot-sdk-browser-bundle");
`

but I still get an error 

```
/node_modules/aws-iot-device-sdk/browser/aws-iot-sdk-browser-bundle.js
Module not found: Can't resolve './aes' in 'example1/node_modules/aws-iot-device-sdk/browser

```

any suggestions, thanks

**Comment by jmklix** [comment]
If you haven't already you can take a look at the guidance for [building js SDK for browsers](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html).

If that doesn't help can you provide more details about what you are trying to do, your device setup, and any other relevant details.
