### ISSUE TITLE
Guidance requested: How to use cleanSession flag, or retain flag with the sdk? 

### ISSUE THREAD

**Issue by tsan1** [aws/aws-iot-device-sdk-js#335]
Hi, 

I am unable to find examples online on how to use cleanSession flag or retain flag in both publish and subcribe? 
Is there such a flag available? I have scanned through the code repo, couldn't find one . Could you please guide me.

**Comment by tsan1** [comment]
Hi,

Could anyone please help me.

**Comment by bretambrose** [comment]
For direct publishes, retain is controlled by passing it in as part of the options parameter, which gets directly forwarded to the mqtt.js client:

* https://github.com/aws/aws-iot-device-sdk-js/blob/master/device/index.js#L824
* https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L460


With respect to cleanSession, it looks like the js SDK implements its own re-sub logic: 

* https://github.com/aws/aws-iot-device-sdk-js/blob/master/device/index.js#L239
* https://github.com/aws/aws-iot-device-sdk-js/blob/master/device/index.js#L413
