### ISSUE TITLE
IOS Cordova cognito failing

### ISSUE THREAD

**Issue by tronious** [aws/aws-iot-device-sdk-js#337]
Having a very strange issue with calling out to Cognito for credentials from a Cordova Application.

The httpResponse body is empty and throwing an exception inside of the sdk.  httpResponse.body is undefined.  The response code is a 200.  Any insight into what would cause that httpResponse.body to undefined below...ONLY on IOS?

This ONLY HAPPENS on IOS...not Android...not Web.  

`                if (error.code = httpResponse.headers["x-amzn-errortype"] || "UnknownError", "string" == typeof error.code && (error.code = error.code.split(":")[0]), 0 < httpResponse.body.length) try {
`

**Comment by jmklix** [comment]
Sorry, but as stated in the [v2 sdk](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/71) we don't support this with IOS devices.
