### ISSUE TITLE
Connecting to thingShadow using atecc508a via PKCS11

### ISSUE THREAD

**Issue by Francenzo** [aws/aws-iot-device-sdk-js#341]
I am currently implementing aws-iot-device-sdk-js found at https://github.com/aws/aws-iot-device-sdk-js    to connect to AWS. 

We currently have the microchip atecc508a chip installed on our device and I wanted to know how to use the pkcs11 engine along with the above sdk to connect to the IoT service.

Here is the link to the blog post about the partner https://aws.amazon.com/blogs/apn/implementing-secure-authentication-with-aws-iot-and-microchips-trust-platform/ 

Our current use case for this setup is using our devices as with the "IoT Core" service. 
Each atecc508a chip is installed on the device relates to one device in the IoT service.
We have a process of uploading all the certificates to AWS to be validated so that the certs are already authenticated before use.
The issue lies when we try to use the aws-iot-device-sdk-js to connect to the service to communicate MQTT messages and to the thing shadow.

My question is specifically in reference to the thing shadow class:
https://github.com/aws/aws-iot-device-sdk-js#thing-shadow-class  
The class requires a key, client cert, and ca cert.

We are using p11tool and are able to obtain from the atecc508a
    - public key
    - public cert
    - signer cert

The private key of the atecc508a cannot be extracted.

I'm assuming the public cert can go into the "clientCert" parameter and the signer cert can be used for the "caCert". However since the private key cannot be extracted we cannot use it.

I wanted to know how to properly utilize the sdk to create the connection successfully.

As a side note, slightly related, there's a demo available for using pkcs11 with greengrass found here https://gist.github.com/bryan-hunt/2544b48c3a1c34a6543a35ded678fc82

**Comment by Francenzo** [comment]
From what I have found I think the tls connection made in the file device/lib/tls.js may need to be changed to add secure context using the [createSecureContext](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options) function with options to redirect to the pkcs11 engine.

There may also need to be a call made to [setEngine](https://nodejs.org/api/crypto.html#crypto_crypto_setengine_engine_flags) as well.

**Comment by TingDaoK** [comment]
Hi,

Sorry that I am not sure I fully understand your issue here and I am not familiar with the platform. 
But, from my understanding, can you try to use the certification and public/private key generated by AWS IoT core, when you onboard a device? There will be authenticated security credentials to download as you onboard a device. You can find all the required credential files there.

**Comment by TingDaoK** [comment]
Okay, thanks to @bretambrose . You request for supporting TPM is not supported by SDKs for now. And it's not supported by [v2](https://github.com/aws/aws-iot-device-sdk-js-v2) as well. 
We are moving feature requests to [v2](https://github.com/aws/aws-iot-device-sdk-js-v2), and only doing maintenance on this repo. If you still need new features, please request from [v2](https://github.com/aws/aws-iot-device-sdk-js-v2), we will consider to add the support for it.

**Comment by Francenzo** [comment]
As per the above comment, we have requested this functionality be added to v2. Closing this issue.
