### ISSUE TITLE
awsIot.thingShadow authentication

### ISSUE THREAD

**Issue by m-menon** [aws/aws-iot-device-sdk-js#343]
I have set up Google OAuth 2.0 Client and have been able to retrieve the token from Google. Is there any example or documentation on how I can use this token to access AWS IoT data? Like in the below example, is it possible to use the token to authenticate instead of the certificates? Or is there any other preferred way? 

I have tried the `get` method of AWS to get the credentials using Cognito but that doesn't work as it keeps prompting for keyPath, private key etc

```
var awsIot = require('aws-iot-device-sdk');

// Replace the values of '<YourUniqueClientIdentifier>' and '<YourCustomEndpoint>'
// with a unique client identifier and custom host endpoint provided in AWS IoT cloud
// NOTE: client identifiers must be unique within your AWS account; if a client attempts
// to connect with a client identifier which is already in use, the existing
// connection will be terminated.
//
var thingShadows = awsIot.thingShadow({
   keyPath: <YourPrivateKeyPath>,
  certPath: <YourCertificatePath>,
    caPath: <YourRootCACertificatePath>,
  clientId: <YourUniqueClientIdentifier>,
      host: <YourCustomEndpoint>
});
```

[Full example here](https://github.com/aws/aws-iot-device-sdk-js#thing-shadow-class)

Or is there any alternate (without using certs as shown above) way to authenticate this `awsIot.thingShadow`?

**Comment by rccarper** [comment]
If you use Cognito, and use a web socket connection, this should be possible.  Instead of the keyPath/certPath/caPath options, if you set 'protocol' to 'wss' and populate the 'accessKeyId', 'secretKey', and 'sessionToken' fields with what you get back from Cognito, that should do the trick.  (Just in case it helps, here's the code I'm looking at in the SDK: https://github.com/aws/aws-iot-device-sdk-js/blob/5cd0a054235199a38a7571374130424688c38f02/device/index.js#L456)

**Comment by m-menon** [comment]
@rccarper thanks. I will explore that and see how it goes.

**Comment by sborsay** [comment]
As mentioned by Ryan, using SigV4 with Websockets, and Congito is a good
alternative.

You can also use HTTP from your device to API Gateway to Lambda and
authenticate via an API Key in API Gateway or a custom authorizer in Lambda
using the query string parameters as data.

Also this new solution may work for you:

https://aws.amazon.com/about-aws/whats-new/2020/08/aws-iot-core-expands-custom-authentication-options

**Comment by m-menon** [comment]
Cool, thanks @sborsay. I will try that too shortly.

**Comment by jmklix** [comment]
Have you had any problems trying either solution? If not I will close this issue soon.

**Comment by m-menon** [comment]
I haven't had a chance to revisit because I had to tend to something else. I am guessing that one of the recommended solutions may work for me and so I'll close this issue. Thanks.
