### ISSUE TITLE
Error: Invalid "keyPath" option supplied.

### ISSUE THREAD

**Issue by gauravdhra** [aws/aws-iot-device-sdk-js#346]
/node_modules/aws-iot-device-sdk/common/lib/tls-reader.js:92
      throw new Error(exceptions.INVALID_KEY_PATH_OPTION);
      ^

Error: Invalid "keyPath" option supplied.

I am having this error please  help me out.
I am trying to use "aws-iot-device-sdk" to control the appliances (lights , fans) in nodejs 

var awsIot = require('aws-iot-device-sdk');

Thanks

**Comment by jmklix** [comment]
Have you been able to run the device-example.js? If you haven't already you can get a connection kit and start up script from the AWS IoT console. The start up script will contain the correct path the the private key which is what appears to be your problem.

**Comment by usman-whizpool** [comment]
did you get any solution for it?
