### ISSUE TITLE
Named Shadow Support

### ISSUE THREAD

**Issue by jimenaCabrejas** [aws/aws-iot-device-sdk-js#347]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html#iot-javascript-sdk) and [API reference](https://docs.aws.amazon.com/iot/latest/apireference/Welcome.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Windows

**Describe the question**
Hi! I created an IoT Thing with different shadows on the IoT console and I want to simulate it using the sdk. I haven't found any options to set the name of the shadow on the documentation, and by default it registers the Classic Shadow. I know that in the sdk v2 the named shadows are supported. Are they also supported in this sdk? If so, could you give me a link with the documentation to use them?

**Comment by jmklix** [comment]
Sorry, but named shadows are not supported in the v1 sdk. As you have noticed they are include in the v2 sdk so please use that to fully utilize the latest features including named shadows.
