### ISSUE TITLE
SDK stops receiving shadow deltas when long-running

### ISSUE THREAD

**Issue by wkoffel** [aws/aws-iot-device-sdk-js#35]
I'm having an issue with a simple node script running on a raspberry pi.  It's using IoT to trigger a siren light, and also watching for direct messages to run some servos.

I'm finding that everything works fine normally.  But when I come back a day later, the shadow is no longer receiving deltas.  It looks like:

- Device script is running
- Device script is still receiving messages on subscribed topics (the servo motor messages)
- AWS console shows out-of-sync state requiring a delta on the shadow
- No delta received

The device has connectivity.  And if I ssh in, restart the script, everything starts working immediately.

Anyone else encounter issues with long-running node scripts using this SDK?  Is there some sort of periodic "re-register" that's necessary for a thingShadow?

Relevant code:

```javascript
shadow.on('delta',
  function(thingName, stateObject) {
    console.log('received delta '+' on '+thingName+': '+ JSON.stringify(stateObject));
    updateLocalState(stateObject["state"]["siren"]);
});

shadow.on('connect', function() {
    console.log("shadow connected");
    shadow.register( 'Maxwell' );
});
```

**Comment by bhadrip** [comment]
Hello @wkoffel,

Thanks for letting us know. 

Do you send an update(with reported field alone) from raspberry pi to the shadow periodically ? 

Lets say, a mobile application updates the shadow of Siren to ON and a delta is generated by the AWS IoT Shadow service. This delta message for some reason(these MQTT publishes are QoS 0) is missed by the raspberry pi. Then till the next update to the shadow by raspberry pi with the old value(OFF) of siren, no delta message will be generated. The raspberry pi will be waiting for delta message and not receive anything. 

In the mean time, We will try to reproduce this behavior at our end.

Thanks
Bhadri

**Comment by wkoffel** [comment]
Interesting @bhadrip.  So even though the Shadow knows it's reported state and desired state are different, it may think that the message has been sent.  I suppose that's possible.  I'll keep an eye on it over the next couple days and see if the behavior is consistent, and add a periodic `update()` check.

This feels like a [Two General's Problem](https://en.wikipedia.org/wiki/Two_Generals%27_Problem)

**Comment by wkoffel** [comment]
Is it considered best-practice (for the reasons described above) for the device to periodically call update?  These are the kinds of real-world tips that we need a good FAQ for from AWS.  Feels like everyone is inventing their own approaches.  For example, I had to puzzle out how to trigger a `get()` upon boot in order to figure out the current shadow state, and instead of that coming back as a delta, it comes back as an 'approved', managed by a different handler.  Seems like a common use-case, but couldn't find a good recipe solution anywhere in my limited research.

**Comment by gkwicker** [comment]
Hi Will,

Sorry for the delay – most applications will retrieve the latest value of a shadow when starting or after connectivity has been restored.  In addition, if you want to ensure that you receive delta messages, you might try changing the qos level in the thing shadow class to 1 here (it's set to 0 by default).

https://github.com/aws/aws-iot-device-sdk-js/blob/master/thing/index.js#L182

That line of code controls the subscriptions to the special topics used for the MQTT shadow API.  Let us know if that's helpful.

**Comment by wkoffel** [comment]
The issue here doesn't seem to be reliability of the delta messages, but something else going on that causes the shadow connection to die and not be reconnected.  I've put in a call every 5 minutes to just call 'get' on the shadow state, and that seems to have made things more reliable.

I don't know enough about mqtt, but it feels like there's a lurking issue in this library or the underlying MQTT libraries that isn't totally rock-solid with connection persistence.

**Comment by johnrotach** [comment]
Hello @wkoffel,

You say adding a periodic get request improved reliability of your application.  Is this still the case?

I was able to reproduce what I suspect could be your issue on a board here in our office.  When the board experiences a network disconnect I no longer receive shadow updates.  What I believe occurs is the MQTT connection is restored (it is handled by the underlying MQTT client) but registration of the thing never happens upon reconnect.  I have the register call in my onConnect handler, however when this is called upon a reconnect the SDK believes the registration already occurred and does not re-register.

This will be fixed in an upcoming release of the SDK as we are now implementing auto-reconnect and auto-resubscribe functionality inside the SDK.  As a temporary workaround I tested that adding an thing unregister call in my onConnect handler just before doing the register call ensures the thing is re-registered upon reconnect.

Thank you for reporting this issue and for using AWS IoT.

John

**Comment by wkoffel** [comment]
Thanks @johnrotach,  what you describe definitely sounds like it could be my underlying issue.  I just confirmed in my code that I'm not doing a de-register/re-register, but simply doing a `shadow.get('MyThingId')`.  I haven't confirmed that it does a reconnect or re-register, but anecdotally, it has improved reliability, yes.  That remains the case after a week or so of running.  But it's definitely a hack, so a fix to the underlying SDK for more resilience against network failures certainly makes sense (honestly, I'd assumed that was already baked in).

Once the new version is live, I'd be happy to update to it, remove my hack, and report back.

**Comment by gkwicker** [comment]
Hi Will,

We uploaded [version 1.0.11](https://github.com/aws/aws-iot-device-sdk-js/releases/tag/v1.0.11) a few days ago; it includes some new features like auto-resubscribe which may help with the issue you noticed.  Give it a try if you have the chance and see if it helps.  Thanks for using AWS IoT.

**Comment by wkoffel** [comment]
Thanks Gary.  I've updated to the new library version and taken out my other workarounds, I'll report back on stability in a bit.

**Comment by gkwicker** [comment]
Hi @wkoffel, we haven't heard back from you on this issue so we're going to go ahead and close it.  Feel free to re-open it if you have further questions on this topic, and thanks for using AWS IoT.
