### ISSUE TITLE
How to use the mqtt client in an ecs fargate instance

### ISSUE THREAD

**Issue by joaspacce** [aws/aws-iot-device-sdk-js#350]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html#iot-javascript-sdk) and [API reference](https://docs.aws.amazon.com/iot/latest/apireference/Welcome.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Node 10

**Describe the question**
I have a code connecting to the mqtt client in my development environment, but in ecs is throwing an error of credentials not provided. It should not use the task role credentials? Or I'm missing something?

This is how I init the client.
```
const mqttClient = awsIotDevice.device({
    clientId: mqttClientId,
    host: mqttEndpoint,
    protocol: 'wss'
  });
````

**Comment by jmklix** [comment]
I am going to set this to closing soon, because you have asked the [same question](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/106) on the v2 repo. If you prefer to use v1 just comment here before it is closed.
