### ISSUE TITLE
Invalid "keyPath" option supplied.

### ISSUE THREAD

**Issue by vinaykain885426** [aws/aws-iot-device-sdk-js#352]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html#iot-javascript-sdk) and [API reference](https://docs.aws.amazon.com/iot/latest/apireference/Welcome.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
running the SDK on node js and firebase functions

**Question**
How should I authenticate with the AWS IOT devices because when i specify local paths for certificates. it doesn't work when i upload it on cloud functions. How can i give credentials in text form?

Name - Vinay Kumar

**Comment by jmklix** [comment]
You can download a connection kit from the AWS console. To do this select Onboard, then Get Started, and finally pick the OS/language that you want to use. In this case it would be Node.js. Included in the connection kit is a script to download, install, and then run device-example.js. 

Linux/OSX:
node node_modules/aws-iot-device-sdk/examples/device-example.js --host-name=${endpoint} --private-key=${thingName}.private.key --client-certificate=${thingName}.cert.pem --ca-certificate=root-CA.crt --client-id=${clientId}
Windows:
node .\node_modules\aws-iot-device-sdk\examples\device-example.js --host-name ${endpoint} --private-key .\${thingName}.private.key --client-certificate .\${thingName}.cert.pem --ca-certificate .\root-CA.crt --client-id=${clientId}

If you don't have the correct relative path the the key then that could be the cause of "Invalid 'keyPath'" error that you are getting. Please let me know if you still are getting the same error.

**Comment by pjchender** [comment]
@vinaykain885426 I think the problem occurs because the path is not read by the relative path directly. Therefore, if your program runs in a folder(e.g., src, dist), the SDK could not find the path of the key correctly.

Therefore, you should use the path module to get the right path for keyPath, such as:

```js
const device = awsIot.device({
  keyPath: path.resolve(__dirname, './certs/private.pem.key'),
  certPath: path.resolve(__dirname, './certs/certificate.pem.crt'),
  caPath: path.resolve(__dirname, './certs/AmazonRootCA1.pem'),
  //...
});
```

**Comment by jmklix** [comment]
The relative path is affected by where you execute the program from so that might be causing your error.

Path.resolve is not required, you can just use the literal string path. Where is your `certs` folder located? and which folder are you running the js file from?
