### ISSUE TITLE
not able to subscribe dynamic topic.

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [aws/aws-iot-device-sdk-js#353]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html#iot-javascript-sdk) and [API reference](https://docs.aws.amazon.com/iot/latest/apireference/Welcome.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Node/mac/

**Describe the question**
when I subscribe dynamic topic for connecting shadow. I m not able to establish connect the device. with out subscribe it's connected but not able to receive message payload.

```
 this.thingShadows = new awsiot.thingShadow({
      keyPath: keyPath,
      certPath: certPath,
      caPath: caPath,
      clientId: clientId, //"sdk-nodejs-" + clientId,
      host: host,
      debug: true,
    });

    this.thingShadows.subscribe(clientId + "/*");
```
Policy
```
 {
      "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": [
        "arn:aws:iot:ap-south-1:xxxxxxxxxxxxx:client/${iot:Connection.Thing.ThingName}"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish"
      ],
      "Resource": [
        "arn:aws:iot:us-south-1:xxxxxxxxxxxxx:topic/${iot:Connection.Thing.ThingName}/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Subscribe"
      ],
      "Resource": [
        "arn:aws:iot:us-south-1:xxxxxxxxxxxxx:topicfilter/${iot:Connection.Thing.ThingName}/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Receive"
      ],
      "Resource": [
        "arn:aws:iot:ap-south-1:xxxxxxxxxxxxx:topic/${iot:Connection.Thing.ThingName}/*"
      ]
    }
```
**Logs/output**
If applicable, add logs or error output.
```
`error Error: premature close
    at onclosenexttick (/Users/murtuzanalawala/Node/RiooNode/node_modules/end-of-stream/index.js:54:86)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
connection lost - will attempt reconnection in 128 seconds...
close
reconnect/re-register
connect
offline
error Error: premature close
    at onclosenexttick (/Users/murtuzanalawala/Node/RiooNode/node_modules/end-of-stream/index.js:54:86)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
connection lost - will attempt reconnection in 128 seconds...
close
reconnect/re-register
connect
offline
error Error: premature close
    at onclosenexttick (/Users/murtuzanalawala/Node/RiooNode/node_modules/end-of-stream/index.js:54:86)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
connection lost - will attempt reconnection in 128 seconds...`
```
*REMEMBER TO SANITIZE YOUR PERSONAL INFO*
Thanks in advance for your good suggestion.

[StackOverflow Question](https://stackoverflow.com/questions/65075458/not-able-to-subscribe-dynamic-topic-using-aws-iot-device-sdk)

**Comment by sborsay** [comment]
Normally if you have a connection but no incoming IoT payload it is a problem with your certs or policy.  However, in your case i'm guessing you have multiple devices all using:

 **_clientId: clientId__**

 MQTT PubSub normally requires unique ClientId's for each device.  So try clientId: clientId123  etc.

**Comment by jmklix** [comment]
@MurtuzaSrashtaSoft please let us know if changing the ClientId doesn't fix your problem.

**Comment by MurtuzaSrashtaSoft** [comment]
@jmklix 

Yes, this is a policy issue. I already test with a static topic it's working fine. but I need to create a pub-sub with a dynamic topic name. according to aws policy document 

[Policy-doc](https://docs.aws.amazon.com/iot/latest/developerguide/pub-sub-policy.html#registered-devices-(6))

@sborsay 

A policy that works.
```
{
  "Effect": "Allow",
  "Action": [
    "iot:Publish",
    "iot:Receive"
  ],
  "Resource": [
    "arn:aws:iot:ap-south-1:453533943651:topic/topic_1"
  ]
},
{
  "Effect": "Allow",
  "Action": [
    "iot:Subscribe"
  ],
  "Resource": [
    "arn:aws:iot:ap-south-1:453533943651:topicfilter/topic_1"
  ]
}

Code for subscribe topic
``` this.thingShadows.subscribe("topic_1"); ``` 

above code working fine 

In My case, I m register thing with my mongo db unique id .example **5fc4f9ac30c6501a5b92d8d9** and inside a thing there is 4 shadow with another unique name like *5fa3d9541f422604634b7d83* .

and now I want to subscribe to the topic like **5fc4f9ac30c6501a5b92d8d9\5fa3d9541f422604634b7d83** .  clientId is equal to  **5fc4f9ac30c6501a5b92d8d9** 
``` this.thingShadows.subscribe(clientId + "/*"); ``` 

but I m not able to achieve this.

**Comment by MurtuzaSrashtaSoft** [comment]
@jmklix @sborsay any suggestions on point!

**Comment by jmklix** [comment]
I think you are getting subscribing to a topic and shadows confused. Subscribing to a topic is for sending and receiving a message once. Shadows are for long term saving of a device's state. [This page](https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-mqtt.html) has some examples that you might be looking for. I have also included what I think you are looking for below:

Example to get shadow delta:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Subscribe"
      ],
      "Resource": [
        "arn:aws:iot:region:account:topicfilter/$aws/things/thingName/shadow/update/delta"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Receive"
      ],
      "Resource": [
        "arn:aws:iot:region:account:topic/$aws/things/thingName/shadow/update/delta"
      ]
    }
  ]
}
```

What it might look like for you:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Subscribe"
      ],
      "Resource": [
        "arn:aws:iot:ap-south-1:xxxxxxxxxxxxx:topicfilter/$aws/things/5fc4f9ac30c6501a5b92d8d9/shadow/update/delta"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Receive"
      ],
      "Resource": [
        "arn:aws:iot:ap-south-1:xxxxxxxxxxxxx:topic/$aws/things/5fc4f9ac30c6501a5b92d8d9/shadow/update/delta"
      ]
    }
  ]
}
```
Did I understand correctly what you are trying to do? and where you able to get it working?
