### ISSUE TITLE
Seg Fault with message from IOT Console

### ISSUE THREAD

**Issue by redhatva** [aws/aws-iot-device-sdk-js#355]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html#iot-javascript-sdk) and [API reference](https://docs.aws.amazon.com/iot/latest/apireference/Welcome.html)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
PubSub example works as designed. However - if I go to the IOT Test Console and publish a message to the same topic as the pubsub example app. The pubsub app seg faults. I do not know how to debug the seg fault. Also watching the test console subscribe - shows that the pubsub example is working. --verbosity debug does not show anything

**SDK version number**
Latest

**Platform/OS/Hardware/Device**
Raspberry Pi

**To Reproduce (observed behavior)**
node -v = v15.3.0

**Expected behavior**
PubSub Example app should not seg fault. I should see the message I add

**Logs/output**
Publish received on topic topic_1
{"message":"Hello world!","sequence":1}
Publish received on topic topic_1
{"message":"Hello world!","sequence":2}
Publish received on topic topic_1
{"message":"Hello world!","sequence":3}
Publish received on topic topic_1
{"message":"Hello world!","sequence":4}
Publish received on topic topic_1
{"message":"Hello world!","sequence":5}
Publish received on topic topic_1
{"message":"Hello world!","sequence":6}
Publish received on topic topic_1
{"message":"Hello world!","sequence":7}
Publish received on topic topic_1
{"message":"Hello world!","sequence":8}
Publish received on topic topic_1
{"message":"Hello world!","sequence":9}
Publish received on topic topic_1
{"message":"Hello world!","sequence":10}
Segmentation fault

**Additional context**
Not sure if this is a node issue. Running node v15 - I saw numerous deprecated warnings when installing aws-crt package

**Comment by redhatva** [comment]
Looks like the issue is related to argument --count... after changing --count to 0 - no problem existed.
Weird behavior

**Comment by redhatva** [comment]
Some odd behaviors found and a workaround... When setting --count 0 - I can publish messages to the topic via HTTPS and the pubsub example will receive the messages. If I try and mix both HTTPS and the IOT Test console - it will seg fault again.
Very weird behavior.

**Comment by jmklix** [comment]
Which raspberry pi are you using?

**Comment by jmklix** [comment]
I was unable to reproduce this on a raspberry pi 4, and this looks like the pubsub from [aws-iot-device-sdk-js-v2](https://github.com/aws/aws-iot-device-sdk-js-v2). Also it is recommended to use even nodejs versions as they have long term support.

If you are still experiencing a seg fault please open a new issue on the [v2 repo](https://github.com/aws/aws-iot-device-sdk-js-v2)
