### ISSUE TITLE
TLS privateKeyEngine and privateKeyIdentifier options to use OpenSSL engine

### ISSUE THREAD

**Issue by BenBaratte** [aws/aws-iot-device-sdk-js#359]
Hi All,

I have an OpenSSL engine in order to hold the private key of my device with a Secure Element.

In order to use it within a TLS session, NodeJS allow the usage of the privateKeyEngine and privateKeyIdentifier as parameters for the tls.connect() options.

In order to allow the usage of OpenSSL engine within the aws-iot-device-sdk-js, the tls-reader.js could add an extra check regarding the presence of both privateKeyEngine and privateKeyIdentifier at the same level as the KeyPath check.

as the options structure is directly forwarded to the NodeJS TLS component no other modification are needed in order to validate the usage of the OpenSSL engine.

I have tested this small patch in my environment using the release 2.2.5 (downloaded with npm) and I'm able to use my secure element through the OpenSSL engine.

Best Regards,

Benjamin BARATTE

**Comment by jmklix** [comment]
Are you asking for this to be added with a feature request? or are you wanting to make a PR to add this option to this sdk?

**Comment by BenBaratte** [comment]
Hi Joseph,

Basically the way the aws-iot-device-sdk-js is checking the options parameters before forward them to the NodeJS tls component is reducing the configuration we can have with a direct access to the NodeJS TLS features.

So I think it's good to add it as a feature request to the mainline of the aws-device-iot-sdk-js.

I can provide a patch with my modification if needed

Best Regards,

Benjamin BARATTE

**Comment by jmklix** [comment]
Sorry, but we aren't taking feature requests for this version anymore. Take a look at the [v2 sdk](https://github.com/aws/aws-iot-device-sdk-js-v2) for the latest features and make any feature requests here.

I would recommend commenting with your modification on this thread in case anyone else is trying to do the same thing with this sdk.
