### ISSUE TITLE
Permit 'mqtt' in protocol option

### ISSUE THREAD

**Issue by otaki-ryuta** [aws/aws-iot-device-sdk-js#36]
I want to set 'mqtt' in protocol option, but [it's not permitted currently](https://github.com/aws/aws-iot-device-sdk-js/blob/master/device/index.js#L206-L210).
I use MQTT->MQTTS proxy(ex.[SORACOM Beam](https://soracom.jp/services/beam/)), so my client doesn't need any TLS encryption with certification.
Here's my sample code, sample.js.
- http://dev.classmethod.jp/cloud/iot-device-sdk-for-nodejs-via-soracom-beam/
  - Line 10 describes the proxy
  - Line 11 describes MQTT protocol.

**Comment by gkwicker** [comment]
Hi,

Thanks for your input for our SDK; we will investigate incorporating your request in a future release.  In the meantime, feel free to fork the SDK so that you can use it in your application.

**Comment by gkwicker** [comment]
Hi, [the latest version of the SDK](https://github.com/aws/aws-iot-device-sdk-js/releases/tag/v1.0.11) should allow you to specify a different protocol option.  Thanks again for your input, and thanks for using AWS IoT.

**Comment by otaki-ryuta** [comment]
Awesome!
I recommend SORACOM users to use the SDK.
