### ISSUE TITLE
TypeError: filesys.existsSync is not a function. (In 'filesys.existsSync(options.keyPath)', 'filesys.existsSync' is undefined)

### ISSUE THREAD

**Issue by ollolollollooloo** [aws/aws-iot-device-sdk-js#360]
import Aws from 'aws-sdk/dist/aws-sdk-react-native'
import AwsIot from 'aws-iot-device-sdk'

let device = AwsIot.device({
  keyPath: path.resolve(__dirname, './certs/private.pem.key'), // '%USERPROFILE%\certs\private.pem.key',
 certPath: path.resolve(__dirname, './certs/certificate.pem.crt'), // '%USERPROFILE%\certs\certificate.pem.crt',
   caPath: path.resolve(__dirname, './certs/root-ca.pem'), // '%USERPROFILE%\certs\root-ca.pem',
 clientId: 'rasppi4',
     host: 'xxxxxxxxxx-ats.iot.us-east-2.amazonaws.com' 
});

**Comment by jmklix** [comment]
Have you followed the "browserify" instructions [here](https://github.com/aws/aws-iot-device-sdk-js#browser)?

Also here is a similar [issue](https://github.com/aws/aws-iot-device-sdk-js/issues/245) with the same problem.

**Comment by ollolollollooloo** [comment]
Hello thanks! @jmklix 
I made mine working using this:

```
const path = require('path');

const KEY = path.resolve(__dirname, './certs/private.pem.key');
const CERT = path.resolve(__dirname, './certs/certificate.pem.crt');
const CAfile = path.resolve(__dirname, './certs/root-ca.pem');
```
