### ISSUE TITLE
Failed unsubscribe with Array of Topic > 8

### ISSUE THREAD

**Issue by sandyboyz** [aws/aws-iot-device-sdk-js#361]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html#iot-javascript-sdk) and [API reference](https://docs.aws.amazon.com/iot/latest/apireference/Welcome.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Microsoft Windows 10 Home/Node.js

**Describe the question**
I want to `device.unsubscribe()` Array of Topic with length `9`, But when I try to publish the topic that already unsubscribed with AWS-IoT Test, my node.js still get the the message from `.on('message')` listener. But when I only use Array of Topic with length of `8` it's works that I never get the message from AWS-IoT Test. 

When I try to use callback from unsubscribe to get Error Message:
1. When I use length 8, I got **null** error
2. When I use length 9, I got **nothing** logged

Another test I try to loop 9 iteration to manually unsubscribe each of topic and works.

My question is how can this happen? Is the array of topic limited by 8 length? 

**Sample Code**
Array of Topic - 9 Length (Did not works)
```
device.unsubscribe([
        'dt/area/a',
        'dt/area/b',
        'dt/area/c',
        'dt/area/d',
        'dt/area/e',
        'dt/area/f',
        'dt/area/g',
        'dt/area/h',
        'dt/area/i'
      ], (err) => console.log("UNSUBSCRIBE", err)) // nothing logged, still get message from .on('message')
```
Array of Topic - 8 Length (Works)
```
device.unsubscribe([
        'dt/area/a',
        'dt/area/b',
        'dt/area/c',
        'dt/area/d',
        'dt/area/e',
        'dt/area/f',
        'dt/area/g',
        'dt/area/h
      ], (err) => console.log("UNSUBSCRIBE", err)) // null
```
Array of Topic - 9 Length with forEach unsubscribe (Also Works)
```
[
        'dt/area/a',
        'dt/area/b',
        'dt/area/c',
        'dt/area/d',
        'dt/area/e',
        'dt/area/f',
        'dt/area/g',
        'dt/area/h',
        'dt/area/i'
      ].forEach(topic => {
        device.unsubscribe(topic, (err) => console.log(err)) // null * 9
      })
```

**Logs/output**
No Error Logs Appeared, Only I still get message from topic that already unsubscribe

**Comment by sandyboyz** [comment]
Okay, I already included sample code in the issues

**Comment by jmklix** [comment]
This is an [IoT core limitation](https://docs.aws.amazon.com/general/latest/gr/iot-core.html#limits_iot) so you will have to limit it to 8 subscribe/unsubscribe operations at a time.

Maximum subscriptions per subscribe request | A single SUBSCRIBE request has a quota of 8 subscriptions.
-- | --
