### ISSUE TITLE
Connection resetting after a fixed time

### ISSUE THREAD

**Issue by khan-07** [aws/aws-iot-device-sdk-js#362]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html#iot-javascript-sdk) and [API reference](https://docs.aws.amazon.com/iot/latest/apireference/Welcome.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?

nodejs/windows and linux/amd and intel processor/sdk v 2.2.6

**Describe the question**

Hi, I have been using javascript aws-iot-device-sdk for almost 8 month. But recently something has started hapenning where the device goes offline , connection resets and then reconnects after 6 and half hour exactly.  I thought i was sending too much data or maybe hitting one of the quotas but i stopped publishing messages, now it just connects to the broker but still facing the problem.  Any kind of help would be appreciated. Reconnection used to happen before as well but they were like once every 5 /10 days and random intervals between them. 

**Logs/output**

**Status, Message,DateTime**

offline, ,Tue Apr 06 2021 16:57:02 GMT+0100 (British Summer Time)
error,Error: read ECONNRESET,Tue Apr 06 2021 16:57:02 GMT+0100 (British Summer Time)
reconnect, ,Tue Apr 06 2021 16:57:06 GMT+0100 (British Summer Time)
offline, ,Tue Apr 06 2021 23:27:07 GMT+0100 (British Summer Time)
error,Error: read ECONNRESET,Tue Apr 06 2021 23:27:07 GMT+0100 (British Summer Time)
reconnect, ,Tue Apr 06 2021 23:27:11 GMT+0100 (British Summer Time)
offline, ,Wed Apr 07 2021 05:57:12 GMT+0100 (British Summer Time)
error,Error: read ECONNRESET,Wed Apr 07 2021 05:57:12 GMT+0100 (British Summer Time)
reconnect, ,Wed Apr 07 2021 05:57:16 GMT+0100 (British Summer Time)
offline, ,Wed Apr 07 2021 12:27:16 GMT+0100 (British Summer Time)
error,Error: read ECONNRESET,Wed Apr 07 2021 12:27:16 GMT+0100 (British Summer Time)
reconnect, ,Wed Apr 07 2021 12:27:20 GMT+0100 (British Summer Time)
offline, ,Wed Apr 07 2021 18:55:59 GMT+0100 (British Summer Time)
error,Error: read ECONNRESET,Wed Apr 07 2021 18:55:59 GMT+0100 (British Summer Time)
reconnect, ,Wed Apr 07 2021 18:56:03 GMT+0100 (British Summer Time)
offline, ,Thu Apr 08 2021 01:26:04 GMT+0100 (British Summer Time)
error,Error: read ECONNRESET,Thu Apr 08 2021 01:26:04 GMT+0100 (British Summer Time)
reconnect, ,Thu Apr 08 2021 01:26:08 GMT+0100 (British Summer Time)
offline, ,Thu Apr 08 2021 07:56:09 GMT+0100 (British Summer Time)
error,Error: read ECONNRESET,Thu Apr 08 2021 07:56:09 GMT+0100 (British Summer Time)
reconnect, ,Thu Apr 08 2021 07:56:13 GMT+0100 (British Summer Time)

**Comment by jmklix** [comment]
Did you change anything recently? 

What version nodejs are you using? and is this happening on all of the OS's you mentioned?

**Comment by khan-07** [comment]
Thanks for responding.  

So the devices I was testing on were connecting to the internet using a 4g modem and the ip changed every 6 and half hours.  I guess that means there is no way to avoid these disconnect/reconnects without changing the carrier.
