### ISSUE TITLE
feature: pkcs#11 support?

### ISSUE THREAD

**Issue by brownmonkey** [aws/aws-iot-device-sdk-js#368]
If I got it right, the support for pkcs#11 is currently only available for aws-iot-device-sdk-embedded-C / FreeRTOS  but not for aws-iot-device-sdk-js and aws-iot-device-sdk-python. As my device is a Linux-based, I would like to ask if the aws-iot-device-sdk-js or aws-iot-device-sdk-python will have pkcs#11 in a near future?

**Comment by jmklix** [comment]
Sorry, but we are not planning on adding pkcs11 to any of the v1 sdks. But we are actively working on adding it to the v2 sdk's: [js-v2](https://github.com/aws/aws-iot-device-sdk-js-v2), [python-v2](https://github.com/aws/aws-iot-device-sdk-python-v2)
