### ISSUE TITLE
Update link to root-CA.crt in README.md

### ISSUE THREAD

**Issue by mjiderhamn** [aws/aws-iot-device-sdk-js#369]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
In `README.md` there is a link for "root-CA.crt: the root CA certificate" leading to https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem, which now displays "symantec.com has moved to broadcom.com"

Please update to correct URL

**Comment by TheRyanBurke** [comment]
Fixed by https://github.com/aws/aws-iot-device-sdk-js/pull/370
