### ISSUE TITLE
RE: The SeeedStudio.com/wiki

### ISSUE THREAD

**Issue by silver2row** [aws/aws-iot-device-sdk-js#37]
Hello,

I tried to get the new .pem file from the Internet at wget https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem.

I could not get this .pem file for some reason. I am using the BBG and aws IOT. 

Please send some type of information on how I can get this file. Thank you.

Sincerely,

Seth

**Comment by silver2row** [comment]
Hello Again,

I forgot to mention...I am using Cloud9 to update, upgrade, and nano to type my programs/software.

Sincerely,

Seth

**Comment by gkwicker** [comment]
Hi Seth,

If wget isn't working on your platform, you can just click that link in your browser, then copy&paste the root certificate text into a file and use that.  Let us know if that solves the issue and thanks for using AWS IoT.

**Comment by silver2row** [comment]
Hello...I could not copy and paste it. I copied it but I could not paste it for some reason. I was going to paste it in my folder for AWS on my hard drive with Win 10. Then, I was going to download it to Cloud9 while online via my BBG. Um...is there any other ways to get this file working?

Sincerely,

Seth

**Comment by gkwicker** [comment]
Have you tried curl on your target?

```sh
curl https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem > root-CA.pem
```

**Comment by silver2row** [comment]
No...I will try it. Thank you.

**Comment by silver2row** [comment]
Hello,

Okay...I tried the "curl" way. It downloaded the text but it did not save as a file. What do you think I should do from here?

Sincerely,

Seth

P.S. The text is in my screen on Cloud9 but I cannot "mess" with it.

**Comment by gkwicker** [comment]
Hi Seth, did you redirect the output of curl to a file?  Make sure to add the ' > root-CA.crt' at the end of the curl command, that sends the output to the file rather than to the console.

**Comment by silver2row** [comment]
Hey Man,

I got it now. wget is working now. Oh well. I could not get it to work last night but it is working now. Oh and about curl, thank you. I now know what to do (> root-CA-crt). Thank you.

**Comment by gkwicker** [comment]
Glad to hear it's working and thanks for using AWS IoT.
