### ISSUE TITLE
Error UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by Francenzo** [aws/aws-iot-device-sdk-js#372]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html#iot-javascript-sdk) and [API reference](https://docs.aws.amazon.com/iot/latest/apireference/Welcome.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Ubuntu Linux

**Describe the question**
I am currently trying to connect to the iot using a device certificate signed by a self signed CA.
Running an example returns **UNABLE_TO_GET_ISSUER_CERT_LOCALLY**

The CA cert has been uploaded and is both active and has auto-registration enabled.
The device certificate has been signed by the above CA cert.

Below is the setup used when instantiating the shadow:
var thingShadows = awsIot.thingShadow({
    caCert: ca_cert,
    region: 'us-east-2',
    privateKey: key,
    clientCert: cert,
    clientId: thingName,
    host: 'NON_ATS.iot.us-east-2.amazonaws.com',
});

I have tried both the ATS and NON-ATS endpoints.
I have also tried using both the device public cert as a standalone and combined with the CA pub cert.

Any suggestions would be appreciated.
Thank you. 

**Logs/output**
```
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12)
Emitted 'error' event on ThingShadowsClient instance at:
    at DeviceClient.<anonymous> (/[node_directory]/aws-iot-device-sdk/thing/index.js:335:12)
    at DeviceClient.emit (events.js:314:20)
    at MqttClient.<anonymous> (/[node_directory]/aws-iot-device-sdk/device/index.js:809:12)
    at MqttClient.emit (events.js:314:20)
    at TLSSocket.handleTLSerrors (/[node_directory]/aws-iot-device-sdk/device/lib/tls.js:29:18)
    at TLSSocket.emit (events.js:326:22)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
```

**Comment by jmklix** [comment]
Have you been able to connect with a cert gotten from the AWS IoT Console?

Also how are you generating your self signed CA? because their might be something incorrect with how you signed it

**Comment by Francenzo** [comment]
I am able to connect to the ATS endpoint using a client cert generated from AWS

I verified the x509v3 extensions configurations of the certs I generated against the AWS certificates to make sure they match.
Still no luck after recreating the client cert to match the AWS provided cert.

**[CA example output]**
```
Version: 3 (0x2)
Serial Number:
    xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
Signature Algorithm: ecdsa-with-SHA256
Issuer: O = "ORGANIZATION", CN = COMMON_NAME
Validity
    Not Before: May 17 15:00:00 2021 GMT
    Not After : May 17 15:00:00 2023 GMT
Subject: O = "ORGANIZATION", CN = SIGNER_CN
Subject Public Key Info:
    Public Key Algorithm: id-ecPublicKey
        Public-Key: (256 bit)
        pub:
            xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:
            xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:
            xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:
            xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:
            xx:xx:xx:xx:xx
        ASN1 OID: prime256v1
        NIST CURVE: P-256
X509v3 extensions:
    X509v3 Key Usage: critical
        Digital Signature, Certificate Sign, CRL Sign
    X509v3 Basic Constraints: critical
        CA:TRUE, pathlen:0
    X509v3 Subject Key Identifier: 
        xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
    X509v3 Authority Key Identifier: 
        keyid:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx

Signature Algorithm: ecdsa-with-SHA256
```

**[Client example output]**
```
Version: 3 (0x2)
Serial Number:
    xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
Signature Algorithm: ecdsa-with-SHA256
Issuer: O = "ORGANIZATION", CN = SIGNER_CN
Validity
    Not Before: Jun 22 14:15:01 2021 GMT
    Not After : Jun 16 14:15:01 2023 GMT
Subject: O = "ORGANIZATION", CN = CLIENT_CN
Subject Public Key Info:
    Public Key Algorithm: rsaEncryption
        RSA Public-Key: (2048 bit)
        Modulus:
            xxxxxxx
        Exponent: xxxx (0xXXXX)
X509v3 extensions:
    X509v3 Basic Constraints: critical
        CA:FALSE
    X509v3 Key Usage: critical
        Digital Signature
    X509v3 Subject Key Identifier: 
        xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
    X509v3 Authority Key Identifier: 
        keyid:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx

Signature Algorithm: ecdsa-with-SHA256
```

**Comment by jmklix** [comment]
What root CA are you using? because as stated in this [issue](https://github.com/aws/aws-iot-device-sdk-js/issues/240) not all of them will work.
