### ISSUE TITLE
Could you help to remove the vulnerability introduced by package crypto-js?

### ISSUE THREAD

**Issue by paimon0715** [aws/aws-iot-device-sdk-js#376]
Hi,@fengsongAWS
### Issue

   1 vulnerability (high severity) is introduced in **_aws-iot-device-sdk_**:
   Vulnerability **SNYK-JS-CRYPTOJS-548472** (high severity) is detected in package **_crypto-js_** (versions: <3.2.1,>=3.3.0 <4.0.0):  [https://snyk.io/vuln/SNYK-JS-CRYPTOJS-548472](https://snyk.io/vuln/SNYK-JS-CRYPTOJS-548472)
  The above vulnerable package is transitively referenced by **_aws-iot-device-sdk_** via:
` aws-iot-device-sdk@2.2.8 ➔ crypto-js@3.1.6`

### Solution
Since **_aws-iot-device-sdk@2.2.*_** is transitively referenced by **72** downstream projects (e.g., [iobroker.iot 1.8.22](https://www.npmjs.com/package/iobroker.iot) (latest version),
[@servisbot/servisbot-cli 10.6.1](https://www.npmjs.com/package/@servisbot/servisbot-cli) (latest version), [@mhlabs/aws-iot-ws-broker 4.0.2](https://www.npmjs.com/package/@mhlabs/aws-iot-ws-broker)  (latest version), [@reactoo/watchtogether-sdk-js 2.3.63](https://www.npmjs.com/package/@reactoo/watchtogether-sdk-js) (latest version), [@inplayer-org/inplayer.js 3.11.2](https://www.npmjs.com/package/@inplayer-org/inplayer.js)(latest version)), 

**_aws-iot-device-sdk@1.0.*_** is referenced by **7** downstream projects (e.g., [node-red-contrib-managed-iot-cloud 1.0.3](https://www.npmjs.com/package/node-red-contrib-managed-iot-cloud) (latest version), [c9m 0.1.2](https://www.npmjs.com/package/c9m) (latest version), [jonas.axelsson 1.0.4](https://www.npmjs.com/package/jonas.axelsson) (latest version), [enebular-agent-aws-iot 1.0.1](https://www.npmjs.com/package/enebular-agent-aws-iot) (latest version), [iot-mock-clients 1.0.5](https://www.npmjs.com/package/iot-mock-clients) (latest version))

If **_aws-iot-device-sdk_** removes the vulnerable package from the above versions, then its fixed versions can help downstream users decrease their pain.

Could you help update packages in these versions?

### Fixing suggestions

(1）In **_aws-iot-device-sdk@2.2.*_**, you can kindly perform the following upgrades (not crossing their major versions):
`crypto-js 3.1.6 ➔ 3.2.1`;  

**Note:**
_crypto-js@3.2.1 has fixed the vulnerability SNYK-JS-CRYPTOJS-548472_

(2）In **_aws-iot-device-sdk@1.0.*_**, you can kindly perform the following upgrades (not crossing their major versions):
`crypto-js 3.1.6 ➔ 3.2.1`;  

**Note:**
_crypto-js@3.2.1 has fixed the vulnerability SNYK-JS-CRYPTOJS-548472_

Thanks for your contributions to the npm ecosystem!

Best regards,
Paimon

**Comment by paimon0715** [comment]
Lots of downstream users transitively use aws-iot-device-sdk@1.0.* via unmaintained packages (the unmaintained packages cannot upgrade aws-iot-device-sdk from 1.0.* to version 2).So if you can kindly release fixed 1.0.* version, the downstream users can avoid introducing the vulnerablity.

**Comment by bretambrose** [comment]
I will try and do a release for 2.x today.  1.x I'm not as sure about and will require some team consultation.

**Comment by bretambrose** [comment]
Looking further, we are not directly affected by the vulnerability in that we only use crypto-js for Sha256 calculations.  That being said, we'll still look into the upgrade but it might take a bit longer priority-wise.

**Comment by paimon0715** [comment]
@bretambrose Thanks for your help.

**Comment by bretambrose** [comment]
2.2.9 contains the relevant crypto version bump.  Currently, we are not considering a 1.x backport given the need to by-hand test and publish.  Admittedly, that may change based on feedback/pressure in the future.
