### ISSUE TITLE
Invalid "keyPath" option supplied.

### ISSUE THREAD

**Issue by usman-whizpool** [aws/aws-iot-device-sdk-js#387]
/node_modules/aws-iot-device-sdk/common/lib/tls-reader.js:92
throw new Error(exceptions.INVALID_KEY_PATH_OPTION);
^

Error: Invalid "keyPath" option supplied.

I am having this error please help me out.
I am trying to use "aws-iot-device-sdk" to control the appliances (lights , fans) in nodejs

var awsIot = require('aws-iot-device-sdk');

Thanks

**Comment by bretambrose** [comment]
Looking at tls-reader.js, it appears to be checking the path you supplied in your configuration and it's not a valid path to a key file.

**Comment by usman-whizpool** [comment]
The path is valid, files exists at path given

**Comment by usman-whizpool** [comment]
<img width="485" alt="Screen Shot 2021-07-16 at 10 06 28 AM" src="https://user-images.githubusercontent.com/5094671/125894735-13bc8d7d-d992-4c75-bf8d-15d6a09d1ccd.png">

**Comment by usman-whizpool** [comment]
resolved issue with following code.

const thingShadows = awsIot.thingShadow({
  keyPath: (__dirname + '/cert_files/private.pem.key'),
  certPath: (__dirname + '/cert_files/certificate.pem.crt'),
  caPath: (__dirname + '/cert_files/AmazonRootCA1.pem'),
  host: 'am36w2kaw63l-ats.iot.ap-southeast-1.amazonaws.com',
  clientId: 'Smartpump-001',
  region: 'ap-southeast-1',
});

I think it expect complete path to the file. appending __dirname at start of the folder path worked
