### ISSUE TITLE
Package doesn't include examples when downloaded via AWS Management Console

### ISSUE THREAD

**Issue by Dazza65** [aws/aws-iot-device-sdk-js#389]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html#iot-javascript-sdk) and [API reference](https://docs.aws.amazon.com/iot/latest/apireference/Welcome.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
start.sh does not complete and reports an error that it cannot find module '/Users/*****/Development/AWS/IoT/things/thing1/node_modules/aws-iot-device-sdk/examples/device-example.js'

Also, why is v2 of the SDK not used in this scenario as v1 is no longer receiving updates?

**SDK version number**
2.2.10

**Platform/OS/Hardware/Device**
MacOS v 11.4 / MacBook Air / Node v14.15.5

**To Reproduce (observed behavior)**
Use the AWS Management Console -> IoT Core -> Onboard -> Getting Started
Select Linux/OSX & Node.js
Complete the thing name and download the "connection kit"
sh ./start.sh

**Expected behavior**
The code should send messages to IoT Core for display in the management console.

**Logs/output**
Running pub/sub sample application...
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/Users/*****/Development/AWS/IoT/things/thing1/node_modules/aws-iot-device-sdk/examples/device-example.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Additional context**
The referenced examples directory does not exist in the aws-iot-device-sdk module, however I can see that it's part of the source code if I download it from github.

**Comment by bretambrose** [comment]
Samples got filtered out in a recent revamp of the release process; I didn't realize the console scripts would be affected.  I'll update the .npmignore and do a re-release.

**Comment by bretambrose** [comment]
This should be addressed by the latest version (2.2.11)
