### ISSUE TITLE
WebSocket connection to 'wss://a85xxxxxxxx.iot.us-west-1.amazonaws.com/mqtt?....' failed

### ISSUE THREAD

**Issue by harshkoralwala** [aws/aws-iot-device-sdk-js#393]
Hello All,

I am facing some weird issues when the reconnection workflow is executed.

"aws-iot-device-sdk": "^2.2.1",

MQTT connection successfully established with AWS IoT.

When UI is idle it starts to reconnect workflow.

But unfortunately, it didn't get succeed and continuously retry after some time.

**I can not find any reason for such behavior from error.**

When I searched for a similar issue I can see for others it shows errors like handshake failure etc.

![image psd](https://user-images.githubusercontent.com/33347464/132003575-4f967274-fc39-4b11-82b4-7d271e632d3e.jpg)

My connection configuration looks like(Angular 6):

`
var awsIot = require('aws-iot-device-sdk');
  this.iotDevice = new awsIot.device({
      host: <Endpoint>,
      clientId: <clientId>,
      accessKeyId:<accessKeyId>,
      secretKey: <secretAccessKey>,
      sessionToken: <sessionToken>,
      protocol: 'wss',
      baseReconnectTimeMs: 1000,
      debug: false
    });
`

Thanks in advance.

**Comment by jmklix** [comment]
You should try using the ats endpoint: `<prefix>-ats.iot.<region>.amazonaws.com`

**Comment by harshkoralwala** [comment]
@jmklix Thank you for your reply.

My whole Endpoint looks like this: a85xxxxxxxxxxx-ats.iot.us-wast-1.amazonaws.com

So it looks like the URL schema is already matching as per your suggestion.

Any other suggestions?

**Comment by jmklix** [comment]
Can you include more details about how you have your setup? and which example you are trying to run. 

I experience no websocket connections issues when running the mqtt-explorer example without angular 6

**Comment by heyralfs** [comment]
Any updates? same problem here

**Comment by harshkoralwala** [comment]
@jmklix @heyralfs 

The issue was with local storage.
My application was clearing all local storage data on some activity.
So it looks like for the re-connect scenario, the module needs some stored data from local storage.
After not removing local storage data, the Same issue was not found.

Hope this helps

**Comment by jmklix** [comment]
@harshkoralwala glad you where able to fix your problem!

@heyralfs hopefully your problem was solved, but if it wasn't please open a new ticket detailing your specific problem.
