### ISSUE TITLE
Not able to connect to wss through network proxy

### ISSUE THREAD

**Issue by karanberiwal** [aws/aws-iot-device-sdk-js#394]
I am trying to connect to wss://<> through network proxy but i am getting connection timeout. 

code snippet:

 
  
   const device = deviceModule({
      protocol: "wss-custom-auth",
      customAuthHeaders: {
      },
      clientId: clientId,
      region: config.region,
      port: config.port,
      host: config.host,
      debug: config.debug
   });

**Comment by karanberiwal** [comment]
How to provide network proxy support for the above device

**Comment by jmklix** [comment]
As mentioned in this [issue](https://github.com/aws/aws-iot-device-sdk-js/issues/230) its probably blocking the web socket upgrade. The previously mentioned issue was set as a feature request, but it was never added to this sdk. Please take a look the [v2 sdk](https://github.com/aws/aws-iot-device-sdk-js-v2) as we are no longer accepting any feature requests for this v1 sdk.

**Comment by bhaskars99** [comment]
@karanberiwal  i'm having same issue. is there any break through for this?
