### ISSUE TITLE
AWS iot device disconnect method

### ISSUE THREAD

**Issue by arslanalidev** [aws/aws-iot-device-sdk-js#395]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html#iot-javascript-sdk) and [API reference](https://docs.aws.amazon.com/iot/latest/apireference/Welcome.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Browser

**Describe the question**
I am using the AWS iOT device for the notifications in browser. It's make the connection with the device but when I loggedout I didn't find any method to disconnect it?

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

**Comment by bretambrose** [comment]
https://github.com/aws/aws-iot-device-sdk-js/blob/master/device/index.js#L896
