### ISSUE TITLE
How to create device shadow automatically? 

### ISSUE THREAD

**Issue by pdt590** [aws/aws-iot-device-sdk-js#396]
I have a huge iot devices, i want to create device shadow for each device automatically 
How can i do that without using aws console? 

Thank you so much

**Comment by jmklix** [comment]
I think you are looking for 
```python
thingShadows.register( 'RGBLedLamp', {}, function() {
```

For a full example you can take a look at the documentation [here](https://github.com/aws/aws-iot-device-sdk-js#thing-shadow-class). Is this what you are wanting to do?

**Comment by pdt590** [comment]
Thank you so much for your reply 
Currently, my project consist of 2 entities: IoT device and Mobile App. 
Mobile App and IoT device communicate to an another via AWS-IoT. 
Do you know any solution that Mobile App can send request to AWS-IoT to create a thing shadow for the device? 
For example, AWS-Lambda can receive the request from app to do that.

**Comment by jmklix** [comment]
AWS Amplify might be what you are looking for and should work. But it doesn't look like it will manage the shadow for you as you will have to pub/sub to the device shadow topics.

https://github.com/aws-amplify/amplify-js/issues/728#issuecomment-384422311
