### ISSUE TITLE
How to connect IoT Core from MQTT client behind HTTP Proxy

### ISSUE THREAD

**Issue by Vishal8523** [aws/aws-iot-device-sdk-js#397]
I have devices behind HTTP Proxy (Port: 80 / 443 opened). 
I want to make these devices connect to AWS IoT Core (a MQTT broker) and publish/subscribe MQTT message by using AWS IoT Device SDK.

So how should I do to config IoT Device SDK to use HTTP Proxy ?

**Comment by jmklix** [comment]
Is [this](https://forums.aws.amazon.com/thread.jspa?threadID=217903) what you are looking for?
```js
  aws.config.update({
        httpOptions: { agent: proxy('http://proxy.example.com:8080') },
```

Also you might want to take a look at the v2 sdk and how to use proxy with those examples [here](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/d6aa50865132bed43c909640faefb40a83b5f481/samples/util/cli_args.js#L163)

**Comment by Vishal8523** [comment]
@jmklix : Yes, [this ](https://forums.aws.amazon.com/thread.jspa?threadID=217903) is what I was looking for.
Is it possible in aws-iot-device-sdk v1 ?

**Comment by jmklix** [comment]
Sorry, but no this isn't possible with the v1 sdk
