### ISSUE TITLE
device-example.js topics

### ISSUE THREAD

**Issue by liunamz-aws** [aws/aws-iot-device-sdk-js#398]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html#iot-javascript-sdk) and [API reference](https://docs.aws.amazon.com/iot/latest/apireference/Welcome.html)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
In https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/device-example.js, 
In line 63, `topic_2` should be `topic_1`, and  in line 67, `topic_1` should be `topic_2`.

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the sdk on?
EC2 instance

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
https://docs.aws.amazon.com/iot/latest/developerguide/iot-quick-start.html#iot-quick-start-install-run

**Expected behavior**

**Logs/output**
If applicable, add logs or error output.

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

**Additional context**

**Comment by bretambrose** [comment]
I don't think the connection kit sample and device-example are the same thing nor should they behave the same.  The device example for js v1 was set up with the intention that you run it twice, one run in each mode.  Done this way, the two separate runs then communicate to each other.  There wouldn't be a need for two separate modes if each mode just talked to its own subscription.

**Comment by adamgruber** [comment]
> I don't think the connection kit sample and device-example are the same thing

@bretambrose In the current implementation, the connection kit runs the device-example.
