### ISSUE TITLE
more than 5 fleet indexes

### ISSUE THREAD

**Issue by evergreendrose** [aws/aws-iot-device-sdk-js#406]
### Describe the feature

what is the timeline like for adding more than 5 fields for fleet indexing?

### Use Case

i can't add more than 5 fields 

### Proposed Solution

add 10+ fields

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1

### Environment details (OS name and version, etc.)

1

**Comment by bretambrose** [comment]
It's not clear what you're talking about here.  Can you give some more details?  Also, the client SDKs have little insight into IoT Core feature evolution, so if you're wondering about IoT Core/Service features, the AWS forums might be a better venue for queries.
