### ISSUE TITLE
Unable to connect to socks proxy

### ISSUE THREAD

**Issue by iamkishu** [aws/aws-iot-device-sdk-js#414]
### Describe the bug

Connect to AWS IOT Core using aws-iot-device-sdk over socks proxy. Upon disconnection of socks proxy server the client tends to reconnect. If the socks proxy server comes alive, the client still be reconnecting instead of constant/stable connection to IOT Core

### Expected Behavior

The client using aws-iot-device-sdk should be connecting to AWS IoT Core over the proxy network.

### Current Behavior

The client is reconnecting over and over again.

### Reproduction Steps

- Connect to AWS IOT Core using aws-iot-device-sdk over socks proxy.
- Upon disconnection of socks proxy server the client tends to reconnect.
- If the socks proxy server comes alive, the client still be reconnecting instead of constant/stable connection to IOT Core

### Possible Solution

Check for underlying wrapper over mqtt.js, while passing the options while creating thing object.

### SDK version used

2.2.11

### Environment details (OS name and version, etc.)

Windows-10, node-16.13.0

**Comment by jmklix** [comment]
Sorry, but we have not added support for socks proxy to this sdk and this is not a feature that we plan on adding. We have stopped taking feature requests for the v1 sdk's but this specific feature request is on our backlog of things to add the the [v2 sdk's](https://github.com/aws/aws-iot-device-sdk-java-v2/issues/86)
