### ISSUE TITLE
Could not find a declaration file for module 'aws-iot-device-sdk'

### ISSUE THREAD

**Issue by mvadrev** [aws/aws-iot-device-sdk-js#417]
### Describe the issue

Trying to setup using this example on angular13: Check links

After i npm install and try to import : import * as AWSIoTData from "aws-iot-device-sdk";

it complains that:

```
'AWSIoTData' is declared but its value is never read.ts(6133)
Could not find a declaration file for module 'aws-iot-device-sdk'. 'c:/Users/mvadr/OneDrive/Desktop/aws-mqtt/node_modules/aws-iot-device-sdk/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/aws-iot-device-sdk` if it exists or add a new declaration (.d.ts) file containing `declare module 'aws-iot-device-sdk';`ts(7016)
```

npm i --save-dev @types/aws-iot-device-sdk does not seem to be working

Any updated tutorial as i see there seem to be some issues with angular 12+?

### Links

https://github.com/eelayoubi/aws-examples/blob/master/aws-examples/src/app/app.component.ts

https://dev.to/eelayoubi/decoupling-an-app-using-aws-iot-577a

**Comment by jmklix** [comment]
Can you try both of these [options](https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam):

> When a module is not yours - try to install types from @types:
> 
> npm install -D @types/module-name
> If the above install errors - try changing import statements to require:
> 
> // import * as yourModuleName from 'module-name';
> const yourModuleName = require('module-name');
