### ISSUE TITLE
where is config.json

### ISSUE THREAD

**Issue by lamiastella** [aws/aws-iot-device-sdk-js#42]
So in the following command, how should I create the config.json and where to put it. It was missing from the tutorial:
node examples/echo-example.js -F ../config.json -f ~/certs --thing-name testThing1

**Comment by gkwicker** [comment]
Hi Mona,

The config.json file is optional, you don't have to use it if you don't want to.  In the AWS IoT console, if you select a thing and then click the 'Connect a device' button, you'll be guided through a workflow to create the device's identity and configuration information to connect one of the SDKs.  For the Node.js SDK, the configuration information is represented as a config.json file, with a format like this:

```sh
{
	"host": <Your endpoint>,
	"port": 8883,
	"clientId": <Your client ID>,
	"thingName": <Your thing name>,
	"caCert": <Your root CA certificate filename>,
	"clientCert": <Your client certificate filename>,
	"privateKey":  <Your private key filename>
}
```
The console generates this for you, or you can create your own using the above template.  You also have the option of not using a config.json file and just specifying the options directly using command line parameters.  Let us know if that answers your question, and thanks for using AWS IoT.

**Comment by gkwicker** [comment]
Hi @lamiastella.  We haven't heard back from you on this issue, so we're going to go ahead and close it.  Feel free to re-open it if you have further questions on this topic, and thanks for using AWS IoT.
