### ISSUE TITLE
when we generate build file with aws-iot-device-sdk in node js .. it has connection issue..

### ISSUE THREAD

**Issue by patson12** [aws/aws-iot-device-sdk-js#421]
### Describe the bug

Hello,
i have an node app using aws-iot-device-sdk working fine in development mode when i change it in production mode and create executable file with pkg. using this lib https://www.npmjs.com/package/pkg.. it gives me connection error.. otherwise its working finewhen i run through source code.. only issue with  executable linux file..

### Expected Behavior

it should work as smooth and without bugs like development mode..

### Current Behavior

connection issue i guess. its in production mode error so cant clearly rectifyu..

### Reproduction Steps

just created pkg file with aws-iot-client ..

### SDK version used

version": "2.2.12

### Environment details (OS name and version, etc.)

linux, node 14.17.0, npm 6.14.14

**Comment by yasminetalby** [comment]
Hello @patson12 ,

Thank you very much for your submission.

As requested previously could you please provide more information on this issue. 
What is the exact connection error message are you receiving? 

Best,

Yasmine

**Comment by patson12** [comment]
hello yasmine , now my problem is solved .. it was permission issue when we create executable files.. thank you so much for your help :)

**Comment by yasminetalby** [comment]
Hello @patson12,

Thank you very much for the update on both submission! I am glad to hear that your issue was resolved. 

If you have any questions or need any support in the future, feel free to reach out with an issue submission or discussion. I will be happy to assist you.

I wish you a great day!

Sincerely,

Yasmine
