### ISSUE TITLE
V2.* doesn't work with node 4.2.6

### ISSUE THREAD

**Issue by wiewiur667** [aws/aws-iot-device-sdk-js#425]
### Describe the bug

I'm trying to run latest version of package using node 4.2.6(only available on target device)

When trying to run examples using nvm it fails, issue is that _mqtt-packet_ is using classes and _mqtt_ dependencies are using _Buffer.from_ which is not available in that node version.

Downgrading _mqtt_ to version 1.11.2 and _websocket-stream_ to ^3.1.0 used in V1.* solves problem

### Expected Behavior

Be able to use package in node 4.2.6

### Current Behavior

root:/mnt/f/src/aws-iot-device-sdk-js# nvm exec 4.2 node ./examples/device-example.js
Running node v4.2.6 (npm v2.14.12)
/mnt/f/src/aws-iot-device-sdk-js/node_modules/mqtt-packet/parser.js:7
class Parser extends EventEmitter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/mnt/f/src/aws-iot-device-sdk-js/node_modules/mqtt-packet/mqtt.js:1:80)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

### Reproduction Steps

clone git repository
_npm install_ 
_nvm exec 4.2 node ./examples/device-example.js_

### Possible Solution

Downgrade packages 

### SDK version used

2.2.13

### Environment details (OS name and version, etc.)

Ubuntu WSL 22.04 - nvm with node 4.2.6

**Comment by jmklix** [comment]
Is there a specific reason why you can't update to a more recent version of node? Version [4.2.6](https://nodejs.org/en/blog/release/v4.4.6) was last supported in 2018, so I would not recommended trying to use it. We can't guarantee that this sdk will work with such an old version of node. Please update your node version to a more recent one and let me know if you have any problems with the sdk.

**Comment by wiewiur667** [comment]
Hi,

 I can't update it as it's the only version Samsung SSSP4 SoC supports. I don't mind using v1.* as it works, but it's confusing that your package.json says that you support node 4.0.0.

 Maybe you could bump up the _engines_ version to avoid confusion in future.

**Comment by jmklix** [comment]
I've tested this sdk with the older versions of node and 8.17 is the oldest release that works. I've also created a PR to update our documentation. Please let me know if this works for you and/or you have any other questions about this sdk.

**Comment by bretambrose** [comment]
One other thing: I imagine if you look back in versions, you will eventually hit one that can be used with node 4.  I'm pretty sure the version bump came about due to the need to update dependencies from a CVE perspective.  In general, almost all of the CVE updates we've done don't represent an actual vulnerability while using the SDK, so if you're comfortable using an older version that will throw up a lot of npm audit warnings, that might be the right direction.
