### ISSUE TITLE
Device registry confusion

### ISSUE THREAD

**Issue by chadhobson** [aws/aws-iot-device-sdk-js#46]
I'm confused by the concept of the "Device Registry" and while I know this isn't a help forum, it begs the question anyway, so here goes. At first I thought it was a Device MODEL Registry but as I read more in the docs, it appears to be a literal 1:1 Device Registry where every single serial numbered device needs to be registered. I'm fine with either approach but....

I thought the AWS IoT dashboard was just a friendly hand-holding exercise to introduce the concept and that's fine. But let's say I need to add thousands of devices to the registry? Maybe I have 50K devices that exist now and I'm shipping 1K devices every week.

I need to register these existing devices somehow as well as future ones that I'm shipping. I'm obviously not going to do that through the dashboard one at a time nor would I do that from AWS CLI, so what part of the docs am I completely missing? How does a newborn device attaining internet access for the first time provision itself with AWS IoT?

None of the examples show a device registering itself with the registry right?

**Comment by johnrotach** [comment]
Hello @chadhobson,

Creating registry entries for a device is optional.  If this is something that fits your workflow then the registry provides a convenient way to store thing-related attributes.  The only requirement when a device connects to AWS IoT is an authentication method (certificate or AWS credentials) with appropriate [AWS IoT policy](http://docs.aws.amazon.com/iot/latest/developerguide/authorization.html).  Depending on your workflow these can be provisioned ahead of time and placed on the device or acquired at the time of connection through a flow with [Amazon Cognito](https://aws.amazon.com/cognito/).

In the future we may expose life cycle events such as a first connect event that would allow for actions to be taken much like existing Rules Engine actions (a Lambda function for example).  This flow could trigger updates to the registry automatically on first connect.  We are still working on requirements for such a feature so nothing more specific to share regarding timing.

I hope this helps answer your questions.  Thank you for using AWS IoT!

John

**Comment by gkwicker** [comment]
Hi Chad,

We haven't heard back from you on this issue, so we're going to go ahead and close it.  Feel free to re-open it if you have further questions on this topic, and thanks for using AWS IoT.
