### ISSUE TITLE
Off Topic: MQTT Browser Client

### ISSUE THREAD

**Issue by nexeh** [aws/aws-iot-device-sdk-js#47]
I apologize for opening an issue that is not directly related to this project but i'm not sure how else to engage with AWS Javascript teams. I am hopeful that you could get me or point me to the information.

In AWS IoT there is a tab for "MQTT Client" which is a GREAT testing tool. Is that source could something that could be made available?

**Comment by johnrotach** [comment]
Hello @nexeh,

Take a look at the [mqttSample](https://github.com/awslabs/aws-iot-examples/tree/master/mqttSample) in the [aws-iot-examples repo](https://github.com/awslabs/aws-iot-examples) under [AWS Labs](https://github.com/awslabs).  This isn't exactly the MQTT debug client implemented in the console but it is a good example of enabling MQTT in a web application.

John

**Comment by nexeh** [comment]
Thank you @johnrotach ! I will take a look at that in the morning. Again, thank you for taking the time to respond.

**Comment by gkwicker** [comment]
Fixed in [version 1.0.12](https://github.com/aws/aws-iot-device-sdk-js/releases/tag/v1.0.12)

**Comment by Mindbowser** [comment]
@gkwicker  can you help me configuring the same? I used MQTT topic provided under IoT Dashboard under Things detail which looks like, "$aws/things/XXXX/shadow/update", now we used this demo and published to above topic and at the same time subscribed from MQTT client provided under IoT dashboard, but we are not able to see anything there, but in this demo if we subscribe then we can see the data that we published, but we want to see it on other clients who also subscribed for same, any idea how this can be achieved?

**Comment by rongsaws** [comment]
It should work. One thing to check is in the AWS IoT console, make sure you are connected to the same AWS region as the one you used in the mqttSample. 

Although unrelated, just want to point out that "$aws/things/XXXX/shadow/update" is a reserved topic that is used for updating the device shadow (more details see http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-mqtt.html). For your testing, you could use any custom topics.

**Comment by Mindbowser** [comment]
@rongsaws  Thanks.

So cant we update Device shadow?

Also even if we use custom topics why MQTT client subscriber not showing any data on the dashboard? As well as can we forward messages from custom topic to SQS so that we can process on backend?

**Comment by Mindbowser** [comment]
Also I checked region, it is same still MQTT client on IoT dashboard not showing any messages when I subscribe to those, though these are shown under this sample. Thoughts?

**Comment by rongsaws** [comment]
> So cant we update Device shadow?

Yes, of course. You can update the device shadow by sending updates to the shadow specific topics. The data is in JSON format. Data schema can be found here http://docs.aws.amazon.com/iot/latest/developerguide/using-thing-shadows.html.

>can we forward messages from custom topic to SQS so that we can process on backend?

You don't have to, but yes. AWS IoT RulesEngine (http://docs.aws.amazon.com/iot/latest/developerguide/iot-rules.html) could help you with that.

>Also I checked region, it is same still MQTT client on IoT dashboard not showing any messages when 
I subscribe to those, though these are shown under this sample. Thoughts?

I've attached a screenshot of my test, could you please check to see if my setup is different to yours?

![mqtt](https://cloud.githubusercontent.com/assets/19155175/17745221/e44193ea-645f-11e6-8346-eb8b58c87a99.JPG)

**Comment by Mindbowser** [comment]
Thanks. I will cross check again but thing topic is not working for sure, something must be wrong. Any pointers?like access key and secret key can make the difference?

**Comment by rongsaws** [comment]
The fact that the MQTT sample was able to publish & receive messages to and from the thing update topic suggests that the IAM credentials are valid. 

I would suggest (again) to double check your endpoint region matches with the region you select on the console. Another thing to check is to enable the CloudWatch logs for IoT (through Console -> AWS IoT -> Settings -> CloudWatch Logs) and then double check the CW logs to see if your messages appear in the logs.
