### ISSUE TITLE
Issue with Index.js for aws-iot-device-sdk module

### ISSUE THREAD

**Issue by naveenbalani** [aws/aws-iot-device-sdk-js#5]
The index.js is missing quotes for device and thing.

It should be -
module.exports.device = require('./device');
module.exports.thingShadow = require('./thing');

instead of -

module.exports.device = require(./device);
module.exports.thingShadow = require(./thing);

After makes the changes , I was able to import the module - require('aws-iot-device-sdk') and connect to AWS IoT platform and send/receive messages. The library made is quite easier, cool !!

**Comment by gkwicker** [comment]
Hello,
 
Thanks for letting us know about this issue.  We will fix this in the next release, but in the meantime you can fix it yourself by adding quotes in the index.js as shown below.  Thanks again for helping us find this problem.
 
```sh
diff --git a/index.js b/index.js
index e2664ee..9366824 100644
--- a/index.js
+++ b/index.js
@@ -16,5 +16,5 @@
 /*
 * Expose AWS IoT Embedded Javascript SDK modules
 */
-module.exports.device = require(./device);
-module.exports.thingShadow = require(./thing);
+module.exports.device = require('./device');
+module.exports.thingShadow = require('./thing’);
 ```
