### ISSUE TITLE
When using the wss protocol missing region is not checked

### ISSUE THREAD

**Issue by JohanZackrisson** [aws/aws-iot-device-sdk-js#50]
When using the wss protocol, you might forget to include the region parameter. This is said to be defaulted, but the generated wss protocol url doesn't include the defaulted region. Instead it shows up as undefined in the string. This is how i noticed the issue.
Instead verify and error out if the region option is not set correctly, or at least use the defaulted value.

**Comment by gkwicker** [comment]
Hi @JohanZackrisson, thanks for letting us know about this issue and for using AWS IoT.  We'll add a check in the next release to make sure the region is set correctly when connecting via wss.

**Comment by gkwicker** [comment]
Fixed in [version 1.0.12](https://github.com/aws/aws-iot-device-sdk-js/releases/tag/v1.0.12)
