### ISSUE TITLE
Cannot update/get after thingShadow reconnect 

### ISSUE THREAD

**Issue by wjy617** [aws/aws-iot-device-sdk-js#51]
After thingShadow offline, it will try to reconnect automatically, but the problem I come across is , even after it reconnect, there will be no more response from aws - iot for new update/get operation, and the thingShadow will be silent for ever. Did I miss some thing about reconnect? 
And will timeout  trigger reconnect in aws-iot?

Thanks

**Comment by gkwicker** [comment]
Hi @wjy617, do you see this behavior when running the example applications or is this only happening when running your own code?  If it's happening only in your code, can you post a sample so that we can have a look at it?  Thanks for using AWS IoT.
