### ISSUE TITLE
How to trigger delta event when want to delete an element inside desired section 

### ISSUE THREAD

**Issue by wjy617** [aws/aws-iot-device-sdk-js#52]
I have a thing shadow state like
```
{
  "desired": {
    "color": "RED"
  },
  "reported": {
    "color": "GREEN"
  }
}
```
and I can delete the "color" element from desired, by set "color" : null, but this delete will not trigger delta event,  so is there some other way or what is the best of practice to delete an element, which can send a delta event to thingShadow listener? Thanks

**Comment by gkwicker** [comment]
Hi @wjy617, one thing you might do in this case is a shadow update containing an invalid property value just prior to deleting the shadow.  All listeners who have registered the shadow will receive the delta event containing the invalid property value and will interpret this to mean that the shadow is about to be deleted.  In the example you list above, the program that wants to delete the shadow might set the desired color to "DELETING" and then update the shadow; after receiving the 'accepted' status event for this operation, it could then proceed to delete the shadow.  Listeners which had registered the shadow would interpret their delta event containing "DELETED" as the property value for "color" to mean that the shadow is about to be deleted and could unregister from the shadow at that point.  Depending on how many listeners might be updating this shadow, there could be a race condition if one was about to delete while another was about to update, but this could happen with any strategy you choose.

Let us know if this information helps, and thanks for using AWS IoT.
