### ISSUE TITLE
Question about connect, reconnect, offline events in aws-iot

### ISSUE THREAD

**Issue by wjy617** [aws/aws-iot-device-sdk-js#56]
At which instance will "connect', 'reconnect' and 'offline' these three events triggered? And after thing shadow offline, will it reconnect to iot by itself, or should I manually reconnect it by some way? If by manual, what is the best practice to do that?  

Thanks

**Comment by johnrotach** [comment]
Hello @wjy617,

The events will be emitted under the following conditions:

- connect: when the MQTT client receives a CONACK indicating a successful connection to the service
- offline: when the MQTT client determines the connection has dropped
- reconnect: when the client is attempting to reconnect after a quiet period (see below)

The thingShadow instance will automatically reconnect according the options passed.  See [here](https://github.com/aws/aws-iot-device-sdk-js#awsiotdeviceoptions).  This includes an automatic backoff feature that will increase the quiet time between unsuccessful reconnect attempts.

John
AWS IoT

**Comment by wjy617** [comment]
Thanks John, I have further question about offline event. Here is a time line log from my test program, after the first time thingshadow offline, the program runs like below circularly. The weird thing is after 03:05:49 thingshadow connect, just after 2 seconds, 03:05:51 thingshadow offline again, do you have any idea of how this happened?  Thanks 

```
May 10  03:03:40          thingshadow offline
May 10  03:03:40          thingshadow close
May 10  03:03:40          thingshadow.unregister(001)
May 10  03:03:40          thingshadow.register(001)
May 10  03:03:42          thingshadow.get(001)
May 10  03:03:52          thingshadow.get(001) timeout
May 10  03:05:48          thingshadow attempt to reconnect
May 10  03:05:48          thingshadow.register(001)
May 10  03:05:49          thingshadow connect
May 10  03:05:51          thingshadow offline
May 10  03:05:51          thingshadow close
```

**Comment by johnrotach** [comment]
There are a couple easy things to check which may be misconfigured and cause looping connection issues such as this.

The first would be having a policy misconfigured.  If you are connecting using an AWS IoT certificate please confirm you have a policy attached to that certificate and that policy specifies the necessary permissions required to connect and publish/subscribe to the topics needed for your example.  An easy way to start is to allow iot:* permissions and then reduce this down to the minimum required after you verify connectivity.  If you are connecting with WebSockets ensure the role attached to your IAM credentials has the same AWS IoT permissions described above.

FYI, this [getting started webinar](https://www.youtube.com/watch?v=tTazcL61JG8) walks through creating a policy and attaching it to a certificate.

The next possible issue is you could have another client connected which is using the same client ID.  If you are only running one instance of this program you should be fine.  If you are running multiple instances at once please ensure you are indeed using unique client IDs.  Client ID can be passed in on the command line in the NodeJS examples or by setting the clientId option when instantiating the thing.

Double check both of those and let us know what you find.

**Comment by yayolius** [comment]
Hello @johnrotach 
Claudio Again here, i followed your recomendations, checked al parameters, checked policies and certificates but keep getting the same issue.
Best Regards
Claudio

**Comment by typemismatch** [comment]
Are you running more than one copy of this script/app at a time? If you are, are you changing your clientId? If you aren't then you'll get into these loops as each clients gets disconnected and reconnects killing off other connections with the same id.

**Comment by yayolius** [comment]
I am running only one script on one device, the only thing is that my
clientId for now has the same name of the "Thing", can that generate an
issue?

2016-05-15 23:27 GMT-03:00 Craig Williams <notifications@github.com>:

**Comment by johnrotach** [comment]
Hello @yayolius,

The ThingName in the shadow example can be the same as the MQTT client ID.  There is not a correlation between the two such as a duplicated client ID.

I see you have also posted in #55.  Let's use that issue to further discuss your MQTT connection issue.

John
AWS IoT
