### ISSUE TITLE
Question: Shadow Device

### ISSUE THREAD

**Issue by Hillsie** [aws/aws-iot-device-sdk-js#57]
I am not clear on the reason for a shadow device. The reason I am confused is that I understood the MQTT "Last Will and testament"  to fulfil this function.

> The client will (or message) 
> When a client connects to a server, it can inform the server that it has a will, or a message, that will be published to a specific topic or topics in the event of an unexpected disconnection. A will is particularly useful in alarm or security settings where system managers must know immediately when a remote sensor has lost contact with the network.

Otherwise, why do you care. The device comes online and begins it comms.

**Comment by johnrotach** [comment]
Hello @Hillsie,

There are two major features of device shadows which offer benefits over an LWT, "I'm no longer connected" message.

The first feature is a mechanism to persist state about your device regardless of its connection state.  When built using the shadow a device can be online and updating its state in the shadow.  These updates are reflected immediately and would be available immediately to a business application built on top of the shadow.  Likewise, if you were to use the shadow as a means of updating state from the application down to the device these updates would be recognized by the device immediately.  What makes using the shadow more interesting is when the device looses connectivity or possibly goes offline regularly to save power.  Your business application still has access to the latest state via the shadow and update state in the shadow while the device is offline.  When the device comes back online it can update its current state in the shadow and also receive any new state information that it missed while offline.

The second feature is the flexibility provided to your application through the shadow REST API.  In this way your application is free to use MQTT or the traditional REST GET/UPDATE/DELETE semantics on the shadow state regardless of how your devices are connected.

While either of these features could be built using other AWS services such as DynamoDB, device shadows provide these out of the box as part of the service.

I hope this helps.  You can find more information in our [marketing materials](http://aws.amazon.com/iot/how-it-works/) or in the [device shadow section](http://docs.aws.amazon.com/iot/latest/developerguide/iot-thing-shadows.html) of our developer guide.

John
AWS IoT

**Comment by Hillsie** [comment]
@johnrotach @gkwicker  Late comment on this functionality. Could you explain how to handle race conditions with the device shadow.

**Comment by typemismatch** [comment]
Shadow updates are all versioned so lots of rapid changes or published changes out of order are resolved by making sure you don't accept older shadow versions.

**Comment by Hillsie** [comment]
Many thanks, I better read the doco more carefully.
