### ISSUE TITLE
Question: React Native

### ISSUE THREAD

**Issue by rkelly92** [aws/aws-iot-device-sdk-js#59]
Hello 😀 . I'd like to know if there's any advise regarding using this with React Native. I'm aware of certain node core dependencies and that a browser version would be more suitable. I got the Paho browser client working and was able to successfully communicate with the AWS MQTT broker but using that approach would mean implementing by myself certain functionality which is already present in the AWS IoT JS SDK. So I tried both the browserize script (with a slight modification to generate a UMD bundle) and using webpack with the options seen in https://github.com/aws/aws-iot-device-sdk-js/pull/58 but the code I ran did nothing (no errors popped up, which is good, but got no successful output either). I haven't done front end development for a while so I really don't know what I'm doing in the bundling process. Any pointers would be appreciated.

**Comment by rkelly92** [comment]
Don't fully understand the issue but here's how I solved it:
Changed https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L246 to actually log connection errors and saw that I was getting a "Not supported data type" from react native's websocket. Introduced changes in data type detection seen here https://github.com/facebook/react-native/pull/6961/files aaaand done, worked as expected. Such a relief!

**Comment by tslater** [comment]
@rkelly92  Are you saying that your problem went away with this update to React Native? Any other tips on getting this to work?

**Comment by alfonsodev** [comment]
Can we reopen this issue until there are clear instructions on how to make it work on react-native ?
I tried adding 
```
 "browser": {
    "fs": false,
    "tls": false,
    "net": false
  },
```
to package.json of `aws-iot-device-sdk-js` module , but I just get the message
Unable to resolve module events from node_modules/aws-iot-device-sdk/device/index.js Inable to find this module in its module map or any of the node+modules directories...

@tslater @rkelly92  any idea?
Thanks.

**Comment by rkelly92** [comment]
Hey @tslater. Sorry, totally missed your question. Basically yeah. It has been a while since I implemented my project so don't remember all the details but I had started working with react native 0.25 and websocket support had limitations. 0.26 was fine but until that got released I used the code from that PR. And the line I reference in the mqttjs repo is now wrong (it changed) but the issue was that due to `this.stream.on('error', nop)` no error was showing up, so replacing nop with a basic console.log led me to the solution (digging through react native issues and PRs).
Apart from that, I couldn't use npm 3. I ended up using the browserize script from this repo with the browserify standalone option and added the bundle to version control. For some reason, with nested dependencies (the way npm 2 resolves them) that approach worked fine but with the flat resolution (of npm 3) I got the node core modules problem again. I have little to no experience with browserify and webpack so simply kept using what I was able to get working. Haven't revisited the problem either.

**Comment by rkelly92** [comment]
@alfonsodev ^ what I describe there is what I did to get it working in my case. Didn't end up using #58 so don't know what the issue could be there.

**Comment by stephenkeep** [comment]
I think there is a bigger issue getting this to work:

 https://github.com/aws/aws-sdk-js/issues/740

We have had to move to another service instead of AWS because of the lack of documented support for react native.

**Comment by tslater** [comment]
I think the cloud service is good, but the client looks too daunting.
ᐧ

**Comment by jamesjara** [comment]
Well, guys, finally; I have finished the MQTT RN Component for` SHADOWS` only but you can access directly to the awsiotdata,if you need to use `device` object. 
I hope can be useful for you, we are using this in our products 

https://github.com/jamesjara/aws-iot-device-sdk-js-react-native#debug
```js
<AWSIoTShadows
    ref={(ref) => { this.AWSIoTShadows = ref; }}
    region="us-west-2"
    host="asdasd.iot.aws.com"
    onReconnect={() => this.onConnect()}
    onConnect={() => this.onConnect()}
    onDelta={(thingId, stateObject) => this.onDelta(thingId, stateObject)}
    onStatus={(thingId, statusType, clientToken, stateObject) =>
        this.onStatus(thingId, statusType, clientToken, stateObject)}
    onThingConnected={(thingId) => { this.onThingConnected(thingId); }}
/>
```
