### ISSUE TITLE
How to stream data over AWS IoT

### ISSUE THREAD

**Issue by ducnus** [aws/aws-iot-device-sdk-js#63]
Dear All, 
My goal is to connect a control device and an EA-Hub (i.e., an MySQL database of real-time data) via AWS IoT. I already installed aws-iot-device-sdk-js on my control device and EA-Hub (they are Linux-based systems). Now I want to perform the action that when the control device publishes a message to IoT device gateway, the EA-Hub as a subscriber will stream the data from its mySQL table to IoT device gateway, and require the AWS service to perform an analysis (e.g., K-mean clustering) on the data, finally send the result to the control device. Note that the connection between the EA-Hub, the control device is based on MQTT. 
Please let me know whether or not the MQTT connection is suitable for streaming data from my EA-Hub to AWS IoT device gateway? Which AWS service should I use to perform the data analysis like K-mean clustering via AWS IoT? 
I would appreciate much if anyone can give me any advice to implement my system. 

Thank in advanced!

**Comment by gkwicker** [comment]
Assuming that you don't exceed any of the [service limits](http://docs.aws.amazon.com/iot/latest/developerguide/iot-limits.html#throttling-limits), you should be able to use AWS IoT in your application.  If you don't want to run the K-Means Clustering algorithm locally, you could run it in [AWS Lambda](https://aws.amazon.com/lambda/) or host the code on an [EC2 Instance](https://aws.amazon.com/ec2/).  For general AWS questions like this, we recommend the [AWS Forums](https://forums.aws.amazon.com).  Let us know if you have any other questions, and thanks for using AWS IoT.
