### ISSUE TITLE
 Cannot resolve module 'tls

### ISSUE THREAD

**Issue by davecarlson** [aws/aws-iot-device-sdk-js#65]
Got the folllowing error after doing an npm install of the module today ( latest version)

```
ERROR in ./~/aws-iot-device-sdk/device/lib/tls.js
Module not found: Error: Cannot resolve module 'tls' in /PROJECT/node_modules/aws-iot-device-sdk/device/lib
 @ ./~/aws-iot-device-sdk/device/lib/tls.js 17:10-24
```

**Comment by gkwicker** [comment]
Hi @davecarlson, tls is an [npm core module](https://nodejs.org/api/tls.html#tls_tls_ssl) so there should be no problems finding it.  Can you post the complete `npm install` console log as well as your node and npm versions  (use `npm --version` and `node --version`)?  Also, are you doing browserify or webpack on this module?  Any other information about your installation/setup/use case would be helpful.  Thanks for using AWS IoT.

**Comment by davecarlson** [comment]
I'll grab that later - it's webpack, so there browse rise.sh is never
called
On Thu, 2 Jun 2016 at 17:28, Gary Wicker <notifications@github.com> wrote:

> Hi @davecarlson <https://github.com/davecarlson>, tls is an npm core
> module <https://nodejs.org/api/tls.html#tls_tls_ssl> so there should be
> no problems finding it. Can you post the complete npm install console log
> as well as your node and npm versions (use npm --version and node
> --version)? Also, are you doing browserify or webpack on this module? Any
> other information about your installation/setup/use case would be helpful.
> Thanks for using AWS IoT.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/aws/aws-iot-device-sdk-js/issues/65#issuecomment-223346205>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AASStm2e0Bv1UGmIChay39463ylG9Ea9ks5qHwTGgaJpZM4IsdaI>
> .
>

-- 
*Fast Web Media Ltd, Digital World Centre, 1 Lowry Plaza, Media City, 
Manchester. M50 3UB*
*PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS E-MAIL*
This e-mail is intended solely for the addressee and is strictly 
confidential. If you are not the addressee, please do not read, print, 
re-transmit, store or act in reliance on it or any attachments. Instead 
please e-mail it back to the sender and delete the message from your 
computer. Fast Web Media accepts no liability for changes made to this 
e-mail (and any attachments) after it was sent or for viruses arising as a 
result of this e-mail transmission. Any unauthorised reproduction, 
dissemination, copying, disclosure, modification, distribution and/or 
publication of this e-mail message is strictly prohibited. Fast Web Media 
reserve the right to monitor all e-mail communications through its networks.
Fast Web Media Ltd is registered in England with Company Number - 2946537, 
the Registered Office is c/o Haines Watts, 1st Floor, Northern Assurance 
Buildings, Albert Square, 9/21 Princess Street, Manchester, M2 4DN. Part of 
mporium Group PLC

--

**Comment by gkwicker** [comment]
Hi @davecarlson, we haven't tested this module using webpack but it looks like users of other modules have [reported this issue](https://github.com/request/request/issues/1529) as well.  If you google `Error: Cannot resolve module 'tls' ` you'll see a number of webpack-related hits as well as some tips for resolving the issue.

Have you tried using `npm run-script browserize`?  This script packages the aws-iot-device-sdk module and all of its dependencies using [browserify](http://browserify.org/).  You can read more about using this SDK in browser applications [here](https://github.com/aws/aws-iot-device-sdk-js#browser).  Let us know if you have any other questions, and thanks for using AWS IoT.
