### ISSUE TITLE
thingShadow#unsubscribe

### ISSUE THREAD

**Issue by linqOxelar** [aws/aws-iot-device-sdk-js#67]
in [awsIot.thingShadow#unsubscribe(topic, [options], [callback])](https://github.com/aws/aws-iot-device-sdk-js#unsubscribe),please precise that this is not identical to mqtt.Client#unsubscribe()  ! 
It does not accept topic array !

**Comment by johnrotach** [comment]
Hello @linqOxelar,

You are correct, unsubscribe should support the same functionality as the underlying client (such as https://github.com/aws/aws-iot-device-sdk-js/blob/master/device/index.js#L693).  We'll fix this and update this issue when the fix is released.

John
AWS IoT

**Comment by fengsongAWS** [comment]
Fix in v1.0.14

**Comment by linqOxelar** [comment]
@fengsongAWS - could be more efficient to correct / update online documentation before closing an issue : as usual, online AWS is not precise, hence incorrect !

if awsIot.thingShadow#unsubscribe() is now like mqtt.Client#unsubscribe(), [awsIot.thingShadow#unsubscribe(topic, [options], [callback])](https://github.com/aws/aws-iot-device-sdk-js#unsubscribe) must become awsIot.thingShadow#unsubscribe(topic/topic array/topic object, [options], [callback])
