### ISSUE TITLE
when shadow has been deleted, version should revert to 1

### ISSUE THREAD

**Issue by linqOxelar** [aws/aws-iot-device-sdk-js#68]
When shadow has been deleted from AWS IOT console, should the version number not revert to 1 as documented in  [thing/index.js](aws-iot-device-sdk-js/thing/index.js) line 205 ?

Deleting the shadow, emit a foreignStateChange and then it is impossible to get shadow or to update it ; get will trigger a 404 error and update a 409 error due to bad version number !

It seems that the only way to solve that is to unregister and register again !

**Comment by TheRyanBurke** [comment]
linqOxelar, can you elaborate what action you are taking when you say "shadow has been deleted from AWS IOT console" ? There is no explicit action to delete shadow in AWS IoT console. Deleting the thing does not clear or delete the shadow at this time. Have you tried using the REST API to delete the shadow?

**Comment by linqOxelar** [comment]
hi Ryan
Of course there is explicit action to delete shadow in AWS IOT console in  'update shadow' menu ! 

![image](https://cloud.githubusercontent.com/assets/18004866/16396033/1cc3bb6e-3cbd-11e6-8155-b94a800cee9a.png)

**Comment by TheRyanBurke** [comment]
linqOxelar, thanks for pointing that out (forgot it was there). Yes, this button should delete the Shadow as you are expecting. I will test the behavior and follow up based on your original post. Did you intend to close this issue?

**Comment by linqOxelar** [comment]
sorry? why to close it?

the trouble is that when i delete the shadow, there is no other way to update it or to get it in the THING ! Getting a deleted shadow leads to 404 and updating the shadow from the THING leads to 409 because version number in state sent is not revert to 1 as commented in the thing/index.js line 205.

So just update this file so that when a delete event occur, version number is corrected/reverted to avoid 409

**Comment by TheRyanBurke** [comment]
linqOxelar, can you provide more details about the scenario where you get 409? I tried deleting a shadow from AWS IoT console with version 89, then used aws-iot-device-sdk-js to connect and update the shadow for that thing. I had no errors and the shadow version did correctly revert to 1 after deleting the shadow and updating it the first time.

**Comment by linqOxelar** [comment]
i used aws-iot-device-sdk-js to connect and update the shadow of a thing and then i deleted the shadow with the console, and then trying to update/set the shadow back from the thing to console.

**Comment by TheRyanBurke** [comment]
linqOxelar, I'm doing the same. Could you please share a gist.github.com clip of your code using the aws-iot-device-sdk-js (with any sensitive data removed) to compare? [Here is a gist of my simple shadow app](https://gist.github.com/TheRyanBurke/89676f7a46ae9f33d0bcd4207e520533) which I'm using to update the shadow before and after deleting the shadow in the console.

**Comment by linqOxelar** [comment]
well a bit too complex for that.

the main difference is that you certainly deleted the shadow before you connected the thing (which clearly works smoothly)
I am testing the deletion of shadow when the thing is registered and connected and running (so after first get/update).

Then at receiving at foreignStateChange event, the thing sends an update of his state to try and rebuild the shadow with his state.

**Comment by bhadrip** [comment]
Hello @linqOxelar ,

Thanks for bringing this issue to our notice. I was able to reproduce the update failure after the shadow delete. 

It is a bug in the [ thing/index.js ] (https://github.com/aws/aws-iot-device-sdk-js/blob/master/thing/index.js#L241) code. The internal version counter is not being reset to 0 on receiving a delete/accepted for the thingName. The delete/accepted message has the version of the last known version of the document before deleting it. 

We will fix this bug in the next release. 

Bhadri

**Comment by fengsongAWS** [comment]
shadow version exposed in v2.2.0 and behavior changes. Please create a new thread if you still have questions.
