### ISSUE TITLE
websocket connection does not work

### ISSUE THREAD

**Issue by syin2** [aws/aws-iot-device-sdk-js#69]
First I cloned this repo. Configured my aws iot.
Then I run the following command in rpi 2.
`node examples/device-example.js -f examples/certs/ -P mqtts  -p 8883`
This command works fine. I can get the following message
`connect`
When I debug with mqtt client in aws iot console, I see the following message

```
{
  "mode1Process": 3
}
```

```
{
  "mode1Process": 2
}
```

```
{
  "mode1Process": 1
}
```

Once I change it  to 
`node examples/device-example.js -f examples/certs/ -P wss -p 443`
It does not work. Always show me

```
offline
close 
reconnect.
```

Before I run this command, I have configured the access key and secret key as well.

**Comment by bhadrip** [comment]
Hello @syin2 ,

Can you share the attached policies for the credentials used ?
`offline` message is emitted when the connection to the server is closed. I have seen a similar error when the right credentials are not used. 

Thanks
Bhadri

**Comment by syin2** [comment]
Hi Bhadri,

The policy file is posted:
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "*"
    }
  ]
}`

Thanks,
-syin

**Comment by syin2** [comment]
According to [https://github.com/aws/aws-iot-device-sdk-js#connections](url)

I can make it work for the first connection type using port 8883.
But for second connection type. It always give me offline messages.

Thanks,
-Shengrong

**Comment by bhadrip** [comment]
Hello @syin2 ,

I am not able to reproduce this issue. Just want to make sure the policy you have pasted here is attached to the the IAM user ?

If you are using AWS CLI, then following command will get the attached policies to the user,

```
aws iam list-attached-user-policies --user-name <user name the access & secret key belong to>
{
    "AttachedPolicies": [
        {
            "PolicyName": "AWSIoTDataAccess", 
            "PolicyArn": "arn:aws:iam::aws:policy/AWSIoTDataAccess"
        }, 
        {
            "PolicyName": "AWSIoTFullAccess", 
            "PolicyArn": "arn:aws:iam::aws:policy/AWSIoTFullAccess"
        }
    ]
}
```

Make sure the user you are using to connect the web sockets example is having the policy you have pasted. 


Thanks
Bhadri
