### ISSUE TITLE
CORS issues? 

### ISSUE THREAD

**Issue by eman2611** [aws/aws-iot-device-sdk-js#71]
Hi there - 

Using `AWS.IoTData` function in the SDK works as it should with a code like this:

```
function getThingShadow(beaconName) {
  let deferred = $q.defer();
  let iotdata = new AWS.IotData({ endpoint: 'a3nyyb4zax558u.iot.us-east-1.amazonaws.com' });
  iotdata.getThingShadow({
    thingName: beaconName
  }, (err, data) => {
    if (err) {
      return deferred.reject(err);
    }
    deferred.resolve(data);
  });
  return deferred.promise;
}
```

It sends the request, successfully connects to the IoT shadow and gives me what I need BUT to call a similar function named `listThings` using `AWS.Iot` fails. I have tried with both patterns specifying the endpoint in options:

```
var iot = new AWS.Iot({
  endpoint: 'a3nyyb4zax558u.iot.us-east-1.amazonaws.com',
  accessKey: '@accessKeyId',
  secretKey: '@secretAccessKey',
  sessionToken: '@sessionToken',
  region: 'us-east-1'
});
iot.listThings({}, function (err, data) {
  if (err) {
    $log.error(err, err.stack); // an error occurred
  } else {
    $log.log(data); // successful response
  }
});
```

and without it:

```
var iot = new AWS.Iot({
  accessKey: '@accessKeyId',
  secretKey: '@secretAccessKey',
  sessionToken: '@sessionToken',
  region: 'us-east-1'
});
iot.listThings({}, function (err, data) {
  if (err) {
    $log.error(err, err.stack); // an error occurred
  } else {
    $log.log(data); // successful response
  }
});
```

and it fails in both cases. 

The REST API endpoint for all of my things start with: "https://a3nyyb4zax558u.iot.us-east-1.amazonaws.com/things", like: "https://a3nyyb4zax558u.iot.us-east-1.amazonaws.com/things/{thingNamo}/shadow" but when calling the API to get the list of all things it fails with 404 (Not Found). 

Does this mean that even though `AWS.Iot` is in the AWS IoT SDK for browser but doesn't actually support in-browser SDK calls?

**Comment by bhadrip** [comment]
Hello @eman2611 ,

Thanks for using the SDK in the browser. 

`listThings ` is a control plane call and currently there is no CORS support for control plane calls in the AWS IoT service. Only date plane calls have the support.

Unfortunately we cannot provide a release date at this moment. We will update this thread once we have the feature ready.

`aws-sdk` is included for `Cognito` and `DynamoDb` (used in [Lifecycle example](https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/browser/lifecycle/index.js)) 

Also, please use `var AWSIoTData = require('aws-iot-device-sdk');` for data plane calls(MQTT) and `var AWS = require('aws-sdk');` for HTTP REST calls. [Lifecycle events](https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/browser/lifecycle/index.js#L23) is a good example of this.

Hope this helps.

Thanks
Bhadri

**Comment by hernangarcia** [comment]
I just noticed i am having this same issue. I can not call iot.listThings from my javascript. Any update on this one?

Thanks a lot!

**Comment by dimonomid** [comment]
I'm calling `iot.attachPrincipalPolicy`, and getting CORS error:

```
XMLHttpRequest cannot load https://iot.eu-west-1.amazonaws.com/principal-policies/MyDevicePolicy. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://s3-eu-west-1.amazonaws.com' is therefore not allowed access. The response had HTTP status code 403.
```
So I assume there's no solution for this?

**Comment by groteworld** [comment]
While I don't have a direct answer to your question, it seems this question is for https://github.com/aws/aws-sdk-js

This repository is specific to the AWS IoT Devices SDK, not the JavaScript AWS IoT API which you seem to be using.

**Comment by fengsongAWS** [comment]
Thanks for your interest in AWS IoT Device SDK. We will close this issue for now and please feel free to open another thread if you have more questions.

**Comment by dimonomid** [comment]
Why closing it? Is it fixed?

**Comment by fengsongAWS** [comment]
Hi @dimonomid ,
This is a question for AWS SDK  which provide control plane API and not for AWS IOT Device SDK. Please open a thread at https://github.com/aws/aws-sdk-js if you have more questions. Thanks
