### ISSUE TITLE
awsIot.thingShadow#subscribe : documentation about callback is incorrect !

### ISSUE THREAD

**Issue by linqOxelar** [aws/aws-iot-device-sdk-js#72]
Callback of subscribe returns **3 arguments instead of 2**, which is not documented in [awsIot.thingShadow#subscribe(topic, [options], [callback])](https://github.com/aws/aws-iot-device-sdk-js#subscribe) !

awsIot.thingShadow#subscribe(topic, [options], [callback]) is supposed to inherit from [mqtt.Client#subscribe(topic/topic array/topic object, [options], [callback])](https://github.com/mqttjs/MQTT.js/blob/master/README.md#subscribe) and there is only 2 arguments in callback.

**First arguments seems to be the topic, second arguments is Error (i suppose) and third arguments is granted (topic and options).**

Again documentation fails and makes us WAIST time in developping/debug AWS IOT !
(mentionning former and related issue of March 24 in [thingShadow.subscribe & event (message)](https://github.com/aws/aws-iot-device-sdk-js/issues/44)

**Comment by linqOxelar** [comment]
Well suddenly close to 10:49 European Time, it seems that we are back to the original 2 arguments as documented !!

So i suppose that was not from SDK, but from AWS IOT MQTT server... 

Please transmit them all my kindest regards !

**Comment by rongsaws** [comment]
Hmm, could you share your example for the suback callback being invoked with 3 arguments? 

I did a quick test with a slightly modified device-example.js like this

```
   if (args.testMode === 1) {
       device.subscribe('topic_1', {qos: 1}, function() {
           console.log(arguments);
      });
   } 
```

The output showed the callback had two arguments:
``` 
   { '0': null, '1': [ { topic: 'topic_1', qos: 1 } ] }
```

**Comment by linqOxelar** [comment]
hello,

my code is

```
this.subscribe(normalizedTopic, {qos:options.qos || 0, retain : false}, function(gtopic, err, granted){
	if (!err) {
		if (this.subscribedTopics.indexOf(normalizedTopic) < 0) this.subscribedTopics.push(normalizedTopic);
		console.log(arguments);
	} else console.log('thing error subscribe');
}.bind(this, normalizedTopic));
```

and the output show the following : 
...
{ '0':'blablabla/Topic', '1':null, '2':[{topic:'blablabla/Topic', qos:0}]}
...
and when doing repl : 
...
{ '0':'blablabla/Topic', '1':null, '2':[{topic:'blablabla/Topic', qos:0}], length:3, callee:undefined, caller:undefined, undefined:[function]}
...

i am using aws-iot-device-sdk@1.0.12 and node 4.4.7

**Comment by rongsaws** [comment]
I'm guessing you called that bound function, which prepended the extra topic argument for you?

**Comment by linqOxelar** [comment]
i tested further : you are right !

this is the bound var 'normalizedTopic' which appears as first argument !

sorry for disturbance !

**Comment by rongsaws** [comment]
No problem! I'm also looking into the comments you made in another two issues, which are valid, and I'll try to speed up the documentation and/or code fix for them. 

Thanks again for using AWS IoT and providing us valuable feedback.
