### ISSUE TITLE
apply policy on the fly

### ISSUE THREAD

**Issue by nqd** [aws/aws-iot-device-sdk-js#73]
Hello all,

Well this is not an issue, but a question on best practice using of policy: how to apply policy on-the-fly.

At first we want to allow one principle to have full access with this policy
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "*"
    }
  ]
}
```

, a client now can connect and do pub/sub.

Then we no longer want this client to connect, or strictly allow it to pub/sub to some specific topic. We create new version of the policy, say
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Deny",
      "Action": "iot:*",
      "Resource": "*"
    }
  ]
}
```

It seems to me that the client still can connect and do pub/sub.

How could we make the new policy work instantly?

Many thanks.

**Comment by liuszeng** [comment]
Hi @nqd ,

Thank you very much for using AWS IoT!

AWS IoT policies are used to grant proper permissions to different AWS IoT clients and are attached to certificates to apply those permissions. You can always create another version of the policy and change the details. One thing to keep in mind is that you will need to set the new version of the policy as **default** in order to make it work. You can find the configuration option in AWS IoT Console after you click on your policy for details.

Please let us know if you have more questions.

Thanks,
Liusu

**Comment by nqd** [comment]
Hello @liuszeng,

Thanks for your response. Yes I did change the policy to default. This is the process.

- set policy to accept everything
- connect principal (client) to aws iot broker, make pub to /topic every one second
- client run for some time
- make new version, deny everything. Set this second version default.
- seeing: the client still keep connect, and pub every second. Expected: it should be disconnected.

Do I miss something in this process @liuszeng ?

Thanks again,

Dinh

**Comment by liuszeng** [comment]
Hi Dinh,

Thank you for providing the detailed information.

You are following the correct steps to configure the policy and make it active. The issue you are experiencing is, for persistent and long lived connections, it will take some time to sync the in-flight policy changes to the connected client, which depends on the service cache refresh rate and could take up to 5 minutes. After you made in-flight policy changes, the connected client will be disconnected eventually. Note that for new connections established after policy changes, the latest version will be cached and should take effect immediately.

Hope that answers your question.

Thanks,
Liusu

**Comment by nqd** [comment]
Hi Liusu,

Thanks for the information. The cache fired within ~300 seconds with my testing.

I think this infor should put somewhere explicitly in the official docs.

Best wishes,

Dinh
