### ISSUE TITLE
Add .end() function to thingShadow

### ISSUE THREAD

**Issue by lukin0110** [aws/aws-iot-device-sdk-js#8]
Allow `end(froce, cb)` function on the thingShadow client. Similar to the `end` function on the mqtt client: https://github.com/mqttjs/MQTT.js/blob/master/README.md#end

I've created an AWS Lambda function where I try to put the state on a thingShadow. Once that is done I want to close the client. If i'm not closing the client the AWS Lambda function acts erratic. When I push a state it tries to push the previous state as well which results in a 409 error conflict. This should be solved when i'm able to close the client.

I've tested it by adding the following snippet directly to `thing/index.js`:

````
   this.end = function(force, callback) {
     device.end(force, callback);
   }
````

**Comment by gkwicker** [comment]
Hi Maarten, 

To update a Thing Shadow from a Lambda function using JavaScript, you'll want to use the AWS SDK for JavaScript (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IotData.html ), not the AWS IoT Device SDK, which is designed to be used in client device environments.  The AWS SDK for JavaScript API for updating a Thing Shadow is: 

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IotData.html#update... 

This API will use HTTP to update the Thing Shadow, so you won't have any MQTT issues.  However, note that the AWS SDK for JavaScript version included in the Lambda execution environment has not yet been updated to include the AWS IoT APIs, but it will be updated very soon.  We will keep this issue open and will post a notice here when the Lambda execution environment is updated with the new AWS IoT APIs.  Please let us know if you have any other questions.

**Comment by lukin0110** [comment]
Thanks Gary. I was not yet aware of the fact that it was already included in de standard SDK, this will fix my issues with Lambda
