### ISSUE TITLE
Pure Javascript client without node

### ISSUE THREAD

**Issue by Mindbowser** [aws/aws-iot-device-sdk-js#81]
Hi am unable to find clear instructions or package for plain javascript sdk to communicate with MQTT/Thing Shadows, any idea from where I can download those from?

Also given instructions for npm module and compiling them is giving lot of trouble, please provide us proper steps.

**Comment by rongsaws** [comment]
In the README file, there's a section about browserifying the code to allow the SDK and its samples to run in browsers. Browser based samples can be found under this directory https://github.com/aws/aws-iot-device-sdk-js/tree/master/examples/browser.

Which part of the npm commands are you having trouble with? We'll be glad to help if you could explain the problems you are facing. Thanks.

**Comment by fengsongAWS** [comment]
Close issue since no response for a while.
