### ISSUE TITLE
Sorry to ask, is this library considered "production ready"?

### ISSUE THREAD

**Issue by yayolius** [aws/aws-iot-device-sdk-js#82]
Hi, we are a really small company in the IoT field and we are really interested in this library, but we are not 100% sure if the library is ready for production.
Thanks
Claudio

**Comment by rongsaws** [comment]
Thanks for your interests in this library. The library is released to the public as an open-source project under the terms of Apache License Version 2.0 (https://github.com/aws/aws-iot-device-sdk-js/blob/master/LICENSE.txt). We also have engineering teams constantly improve and support this library.
