### ISSUE TITLE
Echo example never connects

### ISSUE THREAD

**Issue by danwoods** [aws/aws-iot-device-sdk-js#84]
Hello,
  When running the echo example it seems like I'm having trouble connecting, but there's no errors shown, so I'm not sure where to start looking to sort out the issue.

If I run `node examples/device-example.js -k ~/certs/client.key -c ~/certs/client.cert -a ~/certs/root-CA.pem -g us-west-2 --test-mode=1`, I get the following output:

offline
close
reconnect
offline
close
reconnect
offline
close
reconnect
offline
close
reconnect
offline
close
reconnect
offline
close

And the same thing happens w/ the temperature example. Any idea where to start looking?

Thanks in advance,
Dan

**Comment by rongsaws** [comment]
I would first check in the IoT console to see if the certificate is attached to a valid policy - a policy that allows the client to connect, subscribe and so on. A simple and permissive policy would be like this

`
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "iot:*"
      ],
      "Resource": [
        "*"
      ],
      "Effect": "Allow"
    }
  ]
}
`

When you are familiar with the IoT policy and permissions, you could set up more fine-grained policies. See this page for details http://docs.aws.amazon.com/iot/latest/developerguide/authorization.html.

**Comment by danwoods** [comment]
Thanks @rongsaws, I'll check it out. Closing the issue, will re-open if this doesn't solve the problem...
