### ISSUE TITLE
ShadowThing keeps disconnecting and reconnection every 30 to 60 seconds

### ISSUE THREAD

**Issue by yayolius** [aws/aws-iot-device-sdk-js#85]
Thanks for all your help in advance.
I am successfully working with registering a device, getting and updating a shadow, but for some reason every so and so i get disconected and reconnected to the shadow, getting 'offline' and then 'connect' events, also everytime that i get connected i get the shadow and check if the timestamp has changed since last time that i got the shadow.

I don't know if it a "expected behavior" or is a problem with my install/configuration. Can you guide me on this?

Best regards
Claudio

**Comment by rongsaws** [comment]
Were you trying to send messages every 30 seconds or so? Did you check if your policy prevents messages being sent? Also, how is your internet connection like? Were there a lot of packet losses?

**Comment by fengsongAWS** [comment]
No response for a while. Assume resolved.

**Comment by gaieges** [comment]
To those reading this and having the same problem, what I was doing wrong was that I was using both the shadow and the device approach.  Reducing it to just the shadow and taking advantage of the topic subscriptions there helped.
