### ISSUE TITLE
update things shadow from lambda

### ISSUE THREAD

**Issue by williamlai** [aws/aws-iot-device-sdk-js#87]
Hi,
I'm try to update things shadow from lambda but failed. Here is the code from online editor of lambda. I've remove some irrelevant code.

    var AWS = require('aws-sdk');
    AWS.config.region = "us-east-1";
    var iotData = new AWS.IotData({endpoint: "a2zweh2b7yb784.iot.us-east-1.amazonaws.com"});
    
    exports.handler = function (event, context) {
        try {
            console.log("event.session.application.applicationId=" + event.session.application.applicationId);
    
            if (event.session.new) {
                onSessionStarted({requestId: event.request.requestId}, event.session);
            }
    
            if (event.request.type === "LaunchRequest") {
                onLaunch(event.request,
                    event.session,
                    function callback(sessionAttributes, speechletResponse) {
                        context.succeed(buildResponse(sessionAttributes, speechletResponse));
                    });
            } else if (event.request.type === "IntentRequest") {
                onIntent(event.request,
                    event.session,
                    function callback(sessionAttributes, speechletResponse) {
                        context.succeed(buildResponse(sessionAttributes, speechletResponse));
                    });
            } else if (event.request.type === "SessionEndedRequest") {
                onSessionEnded(event.request, event.session);
                context.succeed();
            }
        } catch (e) {
            context.fail("Exception: " + e);
        }
    };
    
    function setLightInSession(intent, session, callback) {
        var cardTitle = intent.name;
        var OnOffRequest = intent.slots.OnOff;
        var repromptText = "";
        var sessionAttributes = {};
        var shouldEndSession = false;
        var speechOutput = "";
    
        if (OnOffRequest) {
            var OnOffState = OnOffRequest.value;
    		var paramsUpdate = {
    			"thingName" : "mything",
    			"payload" : '{"state": {"desired": {"led":1}}}}'
    		};
    
            console.log("try updateThingShadow");
    
    		//Update Device Shadow
    		iotData.updateThingShadow(paramsUpdate, function(err, data) {
    		    console.log("updateThingShadow callback");
    			if (err){
    				console.log(err, err.stack);
    			}
    			else {
    				console.log(data);
    
            		sessionAttributes = createOnOffStateAttributes(OnOffState);
                    speechOutput = "I now know you want to turn " + OnOffState + " the light";
                    repromptText = "I now know you want to turn " + OnOffState + " the light";
                    callback(sessionAttributes,buildSpeechletResponse(cardTitle, speechOutput, repromptText, shouldEndSession));
    			}	
    		});
        } else {
            speechOutput = "Please try again";
            repromptText = "Please try again";
        }
    	callback(sessionAttributes,buildSpeechletResponse(cardTitle, speechOutput, repromptText, shouldEndSession));
    }
    
    function createOnOffStateAttributes(OnOffState) {
        return {
            OnOffState: OnOffState
        };
    }
    
    // --------------- Helpers that build all of the responses -----------------------
    
    function buildSpeechletResponse(title, output, repromptText, shouldEndSession) {
        return {
            outputSpeech: {
                type: "PlainText",
                text: output
            },
            card: {
                type: "Simple",
                title: "SessionSpeechlet - " + title,
                content: "SessionSpeechlet - " + output
            },
            reprompt: {
                outputSpeech: {
                    type: "PlainText",
                    text: repromptText
                }
            },
            shouldEndSession: shouldEndSession
        };
    }
    
    function buildResponse(sessionAttributes, speechletResponse) {
        return {
            version: "1.0",
            sessionAttributes: sessionAttributes,
            response: speechletResponse
        };
    }

But it seems the callback of updateThingShadow is not actually being called. Here is the log:

    START RequestId: 29e6e550-6940-11e6-b1a4-8bcdcd0859a9 Version: $LATEST
    2016-08-23T14:44:58.353Z	29e6e550-6940-11e6-b1a4-8bcdcd0859a9	event.session.application.applicationId=amzn1.echo-sdk-ams.app.[unique-value-here]
    2016-08-23T14:44:58.353Z	29e6e550-6940-11e6-b1a4-8bcdcd0859a9	onIntent requestId=request5678, sessionId=session1234
    2016-08-23T14:44:58.353Z	29e6e550-6940-11e6-b1a4-8bcdcd0859a9	try updateThingShadow
    END RequestId: 29e6e550-6940-11e6-b1a4-8bcdcd0859a9
    REPORT RequestId: 29e6e550-6940-11e6-b1a4-8bcdcd0859a9	Duration: 2.17 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 25 MB	

I also created thing with thing name "mything" in AWS IoT console. And I use MQTT client to subscribe topic "$aws/things/mything/shadow/update/delta" but nothing comes in.

I checked the policy, and my lambda function use role with allowed policy on AdministratorAccess, AWSIoTFullAccess, and AWSLambdaFullAccess.

Could you provide some suggestions on tracing this problem?

**Comment by rongsaws** [comment]
There appears to be an extra closing brace '}' in your shadow document string.  Can you try removing it and see if it works?

**Comment by williamlai** [comment]
I tried it and it's all the same include the log output.

**Comment by johnrotach** [comment]
Hello @williamlai,

I believe the issue is your Lambda ends by invoking the callback at the end of setLightInSession before the updateThingShadow response returns.  Try removing this callback and relying on the callback you already have in the success case of updateThingShadow.

Let us know if this helps.

John

**Comment by williamlai** [comment]
Hi John,

Yes, it seems it's the problem. Thanks a lot.
