### ISSUE TITLE
Which will cause get thing shadow timeout

### ISSUE THREAD

**Issue by wjy617** [aws/aws-iot-device-sdk-js#89]
Hi, 

Sometimes when try to get a thing shadow through a given awsIot.device connection, it always causes timeout, but after creating a new awsIot.device connection, it will get the shadow successfully. Any idea?

Thanks

**Comment by liuszeng** [comment]
Hi @wjy617 ,

Thank you very much for using AWS IoT Node.js SDK.

Can you include any error messages you see when you are experiencing the issue? It would be really helpful for us to dig into it with the information.

Thanks,
Liusu

**Comment by wjy617** [comment]
Hi Liusu,

Thanks for your reply, I have come across this issue randomly. I open an
device connection and register a new thing shadow, when I try to get the
thing shadow, most of time it will get successfully, but  sometimes it will
show time out. And if I keep get it every half  a minute, it will keep
showing time out. How can I debug this? Or should I keep trying to get, and
it will get the shadow finally?

Thanks

**Comment by chaurah** [comment]
Hi @wjy617,
   There are a couple of things you can try here.
1) Try increasing the operation timeout. The default value is 10 secs. Try increasing this to 30secs or even higher. You can see an example of how to do this in the sample code [here|https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/thing-example.js#L58]. You should keep in mind that your keepalive value should be higher than this timeout to make sure the server doesn't disconnect you.
2) Have you tried running the SDK on a different faster network? That would at least confirm if it is a network related issue or not.

Please try the above and let us know how it went. Thank you for using AWS IoT.

Rahul

**Comment by liuszeng** [comment]
Hi @wjy617 ,

We haven't heard from you for a while. We will close the issue for now. If you have any further questions, please feel free to reopen the issue or start another thread to call out.

Thanks,
Liusu
