### ISSUE TITLE
Raspberry Pi and ESP8266 Node Devices for IOT

### ISSUE THREAD

**Issue by nbibin001** [aws/aws-iot-device-sdk-js#93]
Hi, I was trying to get started with the AWS IOT. Currently I have a Raspberry Pi running MQTT server on it and have two ESP8266 based node devices, one works as a control switch device and other works as a light node device. The switch and the light communicates using the MQTT messages through the raspberry pi MQTT server. On a local network everything works fine. I just wanted to introduce the AWS IOT into this so that I can try controlling the light from outside the local network. Hope that is possible using this platform. I am looking for some directions here. Appreciate your help.

**Comment by liuszeng** [comment]
Hi @nbibin001 ,

Thank you very much for your interest in AWS IoT!

In this case, you can replace the your local MQTT server with AWS IoT and run AWS IoT Device Node.js SDK on your Node devices to transmit device status and receive commands in MQTT backed by AWS IoT MQTT messaging.

You can take a look at the [Thermostat sample](https://github.com/aws/aws-iot-device-sdk-js/tree/master/examples/temperature-control) and see how device transmits data and syncs status through AWS IoT.

You can also check out some cool projects that use the AWS IoT Device SDKs here:
https://www.hackster.io/contests/AWSIoTMegaContest

Hope the above helps.

Thanks,
Liusu

**Comment by nbibin001** [comment]
Hi Liusu, Thanks a lot for your quick response suggestions and examples. One question I had is as mentioned earlier, my Node devices are based on ESP8266, which will not support Node js I guess. Right now I am using Arduino IDE to program it. I have come across this link https://github.com/internetofhomethings/AWS-ESP8266-API. So I should be able to use this with my ESP8266 based node devices, is that right ? Appreciate your help.

**Comment by liuszeng** [comment]
Hi @nbibin001 ,

Thank you very much for providing the information.

Currently we do not have an official AWS IoT Device SDK that supports ESP8266. As long as the device is able to do TLSv1.2 for certificate based MQTT connection, it should be able to connect to AWS IoT. In fact, the TLS v1.2 support seems to be available already. You can check out this commit: https://github.com/esp8266/Arduino/commit/c2414a2252d14afaf29860b11664a1d64e0e8dc1

Thanks,
Liusu

**Comment by fengsongAWS** [comment]
Thanks for your interest in AWS IoT Device SDK. We will close this issue for now and please feel free to open another thread if you have more questions.
