### ISSUE TITLE
No operationTimeout option on for register

### ISSUE THREAD

**Issue by niik** [aws/aws-iot-device-sdk-js#96]
The [thing-example.js](https://github.com/aws/aws-iot-device-sdk-js/blob/97b0b468d59e02e2f6a1dce321000d914cb47894/examples/thing-example.js#L120) and [thing-passthrough-example.js](https://github.com/aws/aws-iot-device-sdk-js/blob/97b0b468d59e02e2f6a1dce321000d914cb47894/examples/thing-passthrough-example.js#L116) make reference to an `operationTimout` setting for `register`. Reading [the code for register](https://github.com/aws/aws-iot-device-sdk-js/blob/97b0b468d59e02e2f6a1dce321000d914cb47894/thing/index.js#L545-L564), however no such option is used, there's an `operationTimeout` option for the [thingShadow](https://github.com/aws/aws-iot-device-sdk-js/blob/97b0b468d59e02e2f6a1dce321000d914cb47894/thing/index.js#L112) itself but no register-specific one.

I'm assuming this is either an oversight in the examples or that the option should exist but is never handled in `register`.

**Comment by fengsongAWS** [comment]
Hi @niik ,

Yes, you are correct. The operationTimeout here is part of generic thingShadowoptions which should not be passed as shadow specific options. This is an oversight in the example. Thanks for pointing that out and we will fix it in the future release.

Thanks,
Fengyi

**Comment by fengsongAWS** [comment]
Issue fixed in release 1.0.14.
